package pojos;
// Generated 01-f�vr.-2011 13:10:18 by Hibernate Tools 3.2.1.GA



/**
 * Impact generated by hbm2java
 */
public class Impact  implements java.io.Serializable, Comparable {


     private int impactId;
     private Site site;
     private Character impactType;
     private Character impactRank;
     private String impactCode;
     private Character impactPollutionCode;
     private Character impactOccurrence;
    /**
     *
     */
    public Impact() {
    }

    /**
     *
     * @param impactId
     */
    public Impact(int impactId) {
        this.impactId = impactId;
    }
    /**
     *
     * @param impactId
     * @param site
     * @param impactType
     * @param impactRank
     * @param impactCode
     * @param impactPollutionCode
     * @param impactOccurrence
     */
    public Impact(int impactId, Site site, Character impactType, Character impactRank, String impactCode, Character impactPollutionCode, Character impactOccurrence) {
       this.impactId = impactId;
       this.site = site;
       this.impactType = impactType;
       this.impactRank = impactRank;
       this.impactCode = impactCode;
       this.impactPollutionCode = impactPollutionCode;
       this.impactOccurrence = impactOccurrence;
    }
    /**
     *
     * @return The identifier of the impact
     */
    public int getImpactId() {
        return this.impactId;
    }
    /**
     *
     * @param impactId
     */
    public void setImpactId(int impactId) {
        this.impactId = impactId;
    }
    /**
     *
     * @return The site
     */
    public Site getSite() {
        return this.site;
    }
    /**
     *
     * @param site
     */
    public void setSite(Site site) {
        this.site = site;
    }
    /**
     *
     * @return
     */
    public Character getImpactType() {
        return this.impactType;
    }
    /**
     *
     * @param impactType
     */
    public void setImpactType(Character impactType) {
        this.impactType = impactType;
    }
    /**
     *
     * @return
     */
    public Character getImpactRank() {
        return this.impactRank;
    }
    /**
     *
     * @param impactRank
     */
    public void setImpactRank(Character impactRank) {
        this.impactRank = impactRank;
    }
    /**
     *
     * @return
     */
    public String getImpactCode() {
        return this.impactCode;
    }
    /**
     *
     * @param impactCode
     */
    public void setImpactCode(String impactCode) {
        this.impactCode = impactCode;
    }
    /**
     *
     * @return
     */
    public Character getImpactPollutionCode() {
        return this.impactPollutionCode;
    }
    /**
     *
     * @param impactPollutionCode
     */
    public void setImpactPollutionCode(Character impactPollutionCode) {
        this.impactPollutionCode = impactPollutionCode;
    }
    /**
     *
     * @return
     */
    public Character getImpactOccurrence() {
        return this.impactOccurrence;
    }
    /**
     *
     * @param impactOccurrence
     */
    public void setImpactOccurrence(Character impactOccurrence) {
        this.impactOccurrence = impactOccurrence;
    }

    /**
     * 
     * @param o
     * @return
     */
    public int compareTo(Object o) {
        Impact impact = (Impact) o;
        if (this.getImpactRank() == null){
            return 1;
        }
        else if (impact.getImpactRank() == null){
            return -1;
        }
        else if (this.getImpactRank().equals(impact.getImpactRank())) {
            return this.getImpactCode().compareTo(impact.getImpactCode());
        }
        else if (this.getImpactRank().equals('H')) {
            return -1;
        }
        else if (impact.getImpactRank().equals('H')){
            return 1;
        }
        else if (this.getImpactRank().equals('M')) {
            return -1;
        }
        else if (impact.getImpactRank().equals('M')){
            return 1;
        }
        else {
            return -1;
        }
    }
}


