package pojos;
// Generated 01-fvr.-2011 13:10:18 by Hibernate Tools 3.2.1.GA


/**
 * MgmtPlan generated by hbm2java
 */
public class MgmtPlan implements java.io.Serializable {

     private int mgmtPlanId;
     private Mgmt mgmt;
     private String mgmtPlanName;
     private String mgmtPlanUrl;


     /**
      *
      */
     public MgmtPlan() {
    }


     /**
      *
      * @param mgmtPlanId
      */
    public MgmtPlan(int mgmtPlanId) {
        this.mgmtPlanId = mgmtPlanId;
    }

    /**
     *
     * @param mgmtPlanId
     * @param mgmt
     * @param mgmtPlanName
     * @param mgmtPlanUrl
     */
    public MgmtPlan(int mgmtPlanId, Mgmt mgmt, String mgmtPlanName, String mgmtPlanUrl) {
       this.mgmtPlanId = mgmtPlanId;
       this.mgmt = mgmt;
       this.mgmtPlanName = mgmtPlanName;
       this.mgmtPlanUrl = mgmtPlanUrl;
    }

    /**
     *
     * @return
     */
    public int getMgmtPlanId() {
        return this.mgmtPlanId;
    }

    /**
     *
     * @param mgmtPlanId
     */
    public void setMgmtPlanId(int mgmtPlanId) {
        this.mgmtPlanId = mgmtPlanId;
    }

    /**
     *
     * @return
     */
    public Mgmt getMgmt() {
        return this.mgmt;
    }

    /**
     *
     * @param mgmt
     */
    public void setMgmt(Mgmt mgmt) {
        this.mgmt = mgmt;
    }

    /**
     *
     * @return
     */
    public String getMgmtPlanName() {
        return this.mgmtPlanName;
    }

    /**
     *
     * @param mgmtPlanName
     */
    public void setMgmtPlanName(String mgmtPlanName) {
        this.mgmtPlanName = mgmtPlanName;
    }

    /**
     *
     * @return
     */
    public String getMgmtPlanUrl() {
        return this.mgmtPlanUrl;
    }

    /**
     *
     * @param mgmtPlanUrl
     */
    public void setMgmtPlanUrl(String mgmtPlanUrl) {
        this.mgmtPlanUrl = mgmtPlanUrl;
    }

}


