package pojos;
// Generated 01-fvr.-2011 13:10:18 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Mgmt generated by hbm2java
 */
public class Mgmt implements java.io.Serializable {


     private int mgmtId;
     private Character mgmtStatus;
     private String mgmtConservMeasures;
     private Set mgmtBodies = new HashSet(0);
     private Set mgmtPlans = new HashSet(0);
     private Set sites = new HashSet(0);
    /**
     * 
     */
    public Mgmt() {
    }


    public Mgmt(int mgmtId) {
        this.mgmtId = mgmtId;
    }
    public Mgmt(int mgmtId, Character mgmtStatus, String mgmtConservMeasures, Set mgmtBodies, Set mgmtPlans, Set sites) {
       this.mgmtId = mgmtId;
       this.mgmtStatus = mgmtStatus;
       this.mgmtConservMeasures = mgmtConservMeasures;
       this.mgmtBodies = mgmtBodies;
       this.mgmtPlans = mgmtPlans;
       this.sites = sites;
    }

    public int getMgmtId() {
        return this.mgmtId;
    }

    public void setMgmtId(int mgmtId) {
        this.mgmtId = mgmtId;
    }
    public Character getMgmtStatus() {
        return this.mgmtStatus;
    }

    public void setMgmtStatus(Character mgmtStatus) {
        this.mgmtStatus = mgmtStatus;
    }
    public String getMgmtConservMeasures() {
        return this.mgmtConservMeasures;
    }

    public void setMgmtConservMeasures(String mgmtConservMeasures) {
        this.mgmtConservMeasures = mgmtConservMeasures;
    }
    public Set getMgmtBodies() {
        return this.mgmtBodies;
    }

    public void setMgmtBodies(Set mgmtBodies) {
        this.mgmtBodies = mgmtBodies;
    }
    public Set getMgmtPlans() {
        return this.mgmtPlans;
    }

    public void setMgmtPlans(Set mgmtPlans) {
        this.mgmtPlans = mgmtPlans;
    }
    public Set getSites() {
        return this.sites;
    }

    public void setSites(Set sites) {
        this.sites = sites;
    }

}


