package pojos;
// Generated 01-f�vr.-2011 13:10:18 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Ownership generated by hbm2java
 */
public class Ownership  implements java.io.Serializable{


     private int ownershipId;
     private String ownershipType;
     private String ownershipCode;
     private Set siteOwnerships = new HashSet(0);

    public Ownership() {
    }


    public Ownership(int ownershipId) {
        this.ownershipId = ownershipId;
    }
    public Ownership(int ownershipId, String ownershipType, String ownershipCode, Set siteOwnerships) {
       this.ownershipId = ownershipId;
       this.ownershipType = ownershipType;
       this.ownershipCode = ownershipCode;
       this.siteOwnerships = siteOwnerships;
    }

    public int getOwnershipId() {
        return this.ownershipId;
    }

    public void setOwnershipId(int ownershipId) {
        this.ownershipId = ownershipId;
    }
    public String getOwnershipType() {
        return this.ownershipType;
    }

    public void setOwnershipType(String ownershipType) {
        this.ownershipType = ownershipType;
    }
    public String getOwnershipCode() {
        return this.ownershipCode;
    }

    public void setOwnershipCode(String ownershipCode) {
        this.ownershipCode = ownershipCode;
    }
    public Set getSiteOwnerships() {
        return this.siteOwnerships;
    }

    public void setSiteOwnerships(Set siteOwnerships) {
        this.siteOwnerships = siteOwnerships;
    }

    @Override
    public boolean equals(Object o) {
        if (! (o instanceof Ownership)) return false;
        Ownership ow = (Ownership) o;
        if (this.getOwnershipId() == ow.getOwnershipId()){
            return true;
        }
        else{
            return false;
        }
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 47 * hash + this.ownershipId;
        hash = 47 * hash + (this.ownershipType != null ? this.ownershipType.hashCode() : 0);
        return hash;
    }

    
}


