package pojos;
// Generated 01-fvr.-2011 13:10:18 by Hibernate Tools 3.2.1.GA



/**
 * RefHabitats generated by hbm2java
 */
public class RefHabitats  implements java.io.Serializable {


     private int refHabitatsId;
     private String refHabitatsCode;
     private Short refHabitatsPriority;
     private String refHabitatsDescEn;
     private String refHabitatsDescFr;
     private String refHabitatsDescDe;
     private String refHabitatsDescEs;
     private String refHabitatsDescIt;
     private String refHabitatsDescNl;
     private String refHabitatsDescPt;
     private String refHabitatsDescDk;
    

    public RefHabitats() {
    }


    public RefHabitats(int refHabitatsId) {
        this.refHabitatsId = refHabitatsId;
    }
    public RefHabitats(int refHabitatsId, String refHabitatsCode, Short refHabitatsPriority, String refHabitatsDescEn, String refHabitatsDescFr) {
       this.refHabitatsId = refHabitatsId;
       this.refHabitatsCode = refHabitatsCode;
       this.refHabitatsPriority = refHabitatsPriority;
       this.refHabitatsDescEn = refHabitatsDescEn;
       this.refHabitatsDescFr = refHabitatsDescFr;
       
    }

    public int getRefHabitatsId() {
        return this.refHabitatsId;
    }

    public void setRefHabitatsId(int refHabitatsId) {
        this.refHabitatsId = refHabitatsId;
    }
    public String getRefHabitatsCode() {
        return this.refHabitatsCode;
    }

    public void setRefHabitatsCode(String refHabitatsCode) {
        this.refHabitatsCode = refHabitatsCode;
    }
    public Short getRefHabitatsPriority() {
        return this.refHabitatsPriority;
    }

    public void setRefHabitatsPriority(Short refHabitatsPriority) {
        this.refHabitatsPriority = refHabitatsPriority;
    }
    public String getRefHabitatsDescEn() {
        return this.refHabitatsDescEn;
    }

    public void setRefHabitatsDescEn(String refHabitatsDescEn) {
        this.refHabitatsDescEn = refHabitatsDescEn;
    }
    public String getRefHabitatsDescFr() {
        return this.refHabitatsDescFr;
    }

    public void setRefHabitatsDescFr(String refHabitatsDescFr) {
        this.refHabitatsDescFr = refHabitatsDescFr;
    }

    /**
     * @return the refHabitatsDescDe
     */
    public String getRefHabitatsDescDe() {
        return refHabitatsDescDe;
    }

    /**
     * @param refHabitatsDescDe the refHabitatsDescDe to set
     */
    public void setRefHabitatsDescDe(String refHabitatsDescDe) {
        this.refHabitatsDescDe = refHabitatsDescDe;
    }

    /**
     * @return the refHabitatsDescEs
     */
    public String getRefHabitatsDescEs() {
        return refHabitatsDescEs;
    }

    /**
     * @param refHabitatsDescEs the refHabitatsDescEs to set
     */
    public void setRefHabitatsDescEs(String refHabitatsDescEs) {
        this.refHabitatsDescEs = refHabitatsDescEs;
    }

    /**
     * @return the refHabitatsDescIt
     */
    public String getRefHabitatsDescIt() {
        return refHabitatsDescIt;
    }

    /**
     * @param refHabitatsDescIt the refHabitatsDescIt to set
     */
    public void setRefHabitatsDescIt(String refHabitatsDescIt) {
        this.refHabitatsDescIt = refHabitatsDescIt;
    }

    /**
     * @return the refHabitatsDescNl
     */
    public String getRefHabitatsDescNl() {
        return refHabitatsDescNl;
    }

    /**
     * @param refHabitatsDescNl the refHabitatsDescNl to set
     */
    public void setRefHabitatsDescNl(String refHabitatsDescNl) {
        this.refHabitatsDescNl = refHabitatsDescNl;
    }

    /**
     * @return the refHabitatsDescPt
     */
    public String getRefHabitatsDescPt() {
        return refHabitatsDescPt;
    }

    /**
     * @param refHabitatsDescPt the refHabitatsDescPt to set
     */
    public void setRefHabitatsDescPt(String refHabitatsDescPt) {
        this.refHabitatsDescPt = refHabitatsDescPt;
    }

    /**
     * @return the refHabitatsDescDk
     */
    public String getRefHabitatsDescDk() {
        return refHabitatsDescDk;
    }

    /**
     * @param refHabitatsDescDk the refHabitatsDescDk to set
     */
    public void setRefHabitatsDescDk(String refHabitatsDescDk) {
        this.refHabitatsDescDk = refHabitatsDescDk;
    }
   
}


