package pojos;
// Generated 19-avr.-2011 13:02:40 by Hibernate Tools 3.2.1.GA



/**
 * RefHabClasses generated by hbm2java
 */
public class RefHabClassesEmerald implements java.io.Serializable {


     private int refHabClassesid;
     private String refHabClassesCode;
     private String refHabClassesDescrEn;
     private String refHabClassesDescrFr;

    public RefHabClassesEmerald() {
    }

    public RefHabClassesEmerald(int refHabClassesid) {
       this.refHabClassesid = refHabClassesid;
    }

    public int getRefHabClassesId() {
        return this.refHabClassesid;
    }

    public void setRefHabClassesId(int refHabClassesid) {
        this.refHabClassesid = refHabClassesid;
    }

    public String getRefHabClassesCode() {
        return refHabClassesCode;
    }

    public void setRefHabClassesCode(String refHabClassesCode) {
        this.refHabClassesCode = refHabClassesCode;
    }

    public String getRefHabClassesDescrEn() {
        return refHabClassesDescrEn;
    }

    public void setRefHabClassesDescrEn(String refHabClassesDescrEn) {
        this.refHabClassesDescrEn = refHabClassesDescrEn;
    }

    public String getRefHabClassesDescrFr() {
        return refHabClassesDescrFr;
    }

    public void setRefHabClassesDescrFr(String refHabClassesDescrFr) {
        this.refHabClassesDescrFr = refHabClassesDescrFr;
    }
}


