package pojos;
// Generated 01-fvr.-2011 13:10:18 by Hibernate Tools 3.2.1.GA



/**
 * RefImpacts generated by hbm2java
 */
public class RefImpacts implements java.io.Serializable {


     private int refImpactsId;
     private String refImpactsCode;
     private String refImpactsDescr;
     private String refImpactsRemarks;
     private String refImpactsOldcode;
     private String refImpactsOldcodeRepport;

    public RefImpacts() {
    }


    public RefImpacts(int refImpactsId) {
        this.refImpactsId = refImpactsId;
    }
    public RefImpacts(int refImpactsId, String refImpactsCode, String refImpactsDescr, String refImpactsRemarks, String refImpactsIucn, String refImpactsOldcodeRepport, String refImpactsOldcode) {
       this.refImpactsId = refImpactsId;
       this.refImpactsCode = refImpactsCode;
       this.refImpactsDescr = refImpactsDescr;
       this.refImpactsRemarks = refImpactsRemarks;
       this.refImpactsOldcodeRepport = refImpactsOldcodeRepport;
       this.refImpactsOldcode = refImpactsOldcode;
       
       
    }

    public int getRefImpactsId() {
        return this.refImpactsId;
    }

    public void setRefImpactsId(int refImpactsId) {
        this.refImpactsId = refImpactsId;
    }
    public String getRefImpactsCode() {
        return this.refImpactsCode;
    }

    public void setRefImpactsCode(String refImpactsCode) {
        this.refImpactsCode = refImpactsCode;
    }
    public String getRefImpactsDescr() {
        return this.refImpactsDescr;
    }

    public void setRefImpactsDescr(String refImpactsDescr) {
        this.refImpactsDescr = refImpactsDescr;
    }
    public String getRefImpactsRemarks() {
        return this.refImpactsRemarks;
    }

    public void setRefImpactsRemarks(String refImpactsRemarks) {
        this.refImpactsRemarks = refImpactsRemarks;
    }
    
    
    public String getRefImpactsOldcode() {
        return this.refImpactsOldcode;
    }

    public void setRefImpactsOldcode(String refImpactsOldcode) {
        this.refImpactsOldcode = refImpactsOldcode;
    }

    /**
     * @return the refImpactsOldcodeRepport
     */
    public String getRefImpactsOldcodeRepport() {
        return refImpactsOldcodeRepport;
    }

    /**
     * @param refImpactsOldcodeRepport the refImpactsOldcodeRepport to set
     */
    public void setRefImpactsOldcodeRepport(String refImpactsOldcodeRepport) {
        this.refImpactsOldcodeRepport = refImpactsOldcodeRepport;
    }

}


