package pojos;
// Generated 01-fvr.-2011 13:10:18 by Hibernate Tools 3.2.1.GA



/**
 * RefNuts generated by hbm2java.
 */
public class RefNutsEmerald implements java.io.Serializable {


     private int refNutsId;
     private String refNutsCode;
     private String refNutsDescription;

    public RefNutsEmerald() {
    }

    /** create object.
     * @param refNutsId id
     */
    public RefNutsEmerald(int refNutsId) {
        this.refNutsId = refNutsId;
    }
    public RefNutsEmerald(int refNutsId, String refNutsCode, String refNutsDescription) {
       this.refNutsId = refNutsId;
       this.refNutsCode = refNutsCode;
       this.refNutsDescription = refNutsDescription;
    }

    public int getRefNutsId() {
        return this.refNutsId;
    }

    public void setRefNutsId(int refNutsId) {
        this.refNutsId = refNutsId;
    }
    public String getRefNutsCode() {
        return this.refNutsCode;
    }

    public void setRefNutsCode(String refNutsCode) {
        this.refNutsCode = refNutsCode;
    }
    public String getRefNutsDescription() {
        return this.refNutsDescription;
    }

    public void setRefNutsDescription(String refNutsDescription) {
        this.refNutsDescription = refNutsDescription;
    }

}


