package pojos;
// Generated 01-fvr.-2011 13:10:18 by Hibernate Tools 3.2.1.GA



/**
 * RefSpecies generated by hbm2java
 */
public class RefSpecies implements java.io.Serializable {


     private int refSpeciesId;
     private String refSpeciesCode;
     private String refSpeciesName;
     private Character refSpeciesGroup;
     private String refSpeciesAltName;
     private String refSpeciesHdName;
     private String refSpeciesCodeNew;
     private String refSpeciesAnnexII;
     private String refSpeciesAnnexIV;
     private String refSpeciesAnnexV;
     private String refSpeciesRes6;




    public RefSpecies() {
    }


    public RefSpecies(int refSpeciesId) {
        this.refSpeciesId = refSpeciesId;
    }
    public RefSpecies(int refSpeciesId, String refSpeciesCode, String refSpeciesName, Character refSpeciesGroup) {
       this.refSpeciesId = refSpeciesId;
       this.refSpeciesCode = refSpeciesCode;
       this.refSpeciesName = refSpeciesName;
       this.refSpeciesGroup = refSpeciesGroup;
    }

    public int getRefSpeciesId() {
        return this.refSpeciesId;
    }

    public void setRefSpeciesId(int refSpeciesId) {
        this.refSpeciesId = refSpeciesId;
    }
    public String getRefSpeciesCode() {
        return this.refSpeciesCode;
    }

    public void setRefSpeciesCode(String refSpeciesCode) {
        this.refSpeciesCode = refSpeciesCode;
    }
    public String getRefSpeciesName() {
        return this.refSpeciesName;
    }

    public void setRefSpeciesName(String refSpeciesName) {
        this.refSpeciesName = refSpeciesName;
    }
    public Character getRefSpeciesGroup() {
        return this.refSpeciesGroup;
    }

    public void setRefSpeciesGroup(Character refSpeciesGroup) {
        this.refSpeciesGroup = refSpeciesGroup;
    }

    /**
     * @return the refSpeciesAltName
     */
    public String getRefSpeciesAltName() {
        return refSpeciesAltName;
    }

    /**
     * @param refSpeciesAltName the refSpeciesAltName to set
     */
    public void setRefSpeciesAltName(String refSpeciesAltName) {
        this.refSpeciesAltName = refSpeciesAltName;
    }

    /**
     * @return the refSpeciesHdName
     */
    public String getRefSpeciesHdName() {
        return refSpeciesHdName;
    }

    /**
     * @param refSpeciesHdName the refSpeciesHdName to set
     */
    public void setRefSpeciesHdName(String refSpeciesHdName) {
        this.refSpeciesHdName = refSpeciesHdName;
    }

    /**
     * @return the refSpeciesCodeNew
     */
    public String getRefSpeciesCodeNew() {
        return refSpeciesCodeNew;
    }

    /**
     * @param refSpeciesCodeNew the refSpeciesCodeNew to set
     */
    public void setRefSpeciesCodeNew(String refSpeciesCodeNew) {
        this.refSpeciesCodeNew = refSpeciesCodeNew;
    }

    /**
     * @return the refSpeciesAnnexII
     */
    public String getRefSpeciesAnnexII() {
        return refSpeciesAnnexII;
    }

    /**
     * @param refSpeciesAnnexII the refSpeciesAnnexII to set
     */
    public void setRefSpeciesAnnexII(String refSpeciesAnnexII) {
        this.refSpeciesAnnexII = refSpeciesAnnexII;
    }

    /**
     * @return the refSpeciesAnnexIV
     */
    public String getRefSpeciesAnnexIV() {
        return refSpeciesAnnexIV;
    }

    /**
     * @param refSpeciesAnnexIV the refSpeciesAnnexIV to set
     */
    public void setRefSpeciesAnnexIV(String refSpeciesAnnexIV) {
        this.refSpeciesAnnexIV = refSpeciesAnnexIV;
    }

    /**
     * @return the refSpeciesAnnexV
     */
    public String getRefSpeciesAnnexV() {
        return refSpeciesAnnexV;
    }

    /**
     * @param refSpeciesAnnexV the refSpeciesAnnexV to set
     */
    public void setRefSpeciesAnnexV(String refSpeciesAnnexV) {
        this.refSpeciesAnnexV = refSpeciesAnnexV;
    }


    public String getRefSpeciesRes6() {
        return refSpeciesRes6;
    }


    public void setRefSpeciesRes6(String refSpeciesRes6) {
        this.refSpeciesRes6 = refSpeciesRes6;
    }

}


