package pojos;
// Generated 01-fvr.-2011 13:10:18 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.Set;

/**
 * Site generated by hbm2java
 */
public class Site implements java.io.Serializable {


     private String siteCode;
     private Map map;
     private Doc doc;
     private Mgmt mgmt;
     private Resp resp;
     private Character siteType;
     private String siteName;
     private Date siteCompDate;
     private Date siteUpdateDate;
     private Date siteSpaDate;
     private String siteSpaLegalRef;
     private Date siteSciPropDate;
     private Date siteSciConfDate;
     private Date siteSacDate;
     private String siteSacLegalRef;
     private String siteExplanations;
     private Double siteLongitude;
     private Double siteLatitude;
     private Double siteArea;
     private Double siteMarineArea;
     private Double siteLength;
     private String siteCharacteristics;
     private String siteQuality;
     private String siteDesignation;
     private Set habitatClasses = new HashSet(0);
     private Set specieses = new HashSet(0);
     private Set habitats = new HashSet(0);
     private Set siteRelations = new HashSet(0);
     private Set siteOwnerships = new HashSet(0);
     private Set nationalDtypes = new HashSet(0);
     private Set regions = new HashSet(0);
     private Set otherSpecieses = new HashSet(0);
     private Set siteBiogeos = new HashSet(0);
     private Set impacts = new HashSet(0);
     private Date siteDateCreation;
     private Date siteDateDeletion;
     private Date siteDateUpdate;

    public Site() {
    }


    public Site(String siteCode) {
        this.siteCode = siteCode;
    }
    public Site(String siteCode, Map map, Doc doc, Mgmt mgmt, Resp resp, Character siteType, String siteName, Date siteCompDate, Date siteUpdateDate, Date siteSpaDate, String siteSpaLegalRef, Date siteSciPropDate, Date siteSciConfDate, Date siteSacDate, String siteSacLegalRef, String siteExplanations, Double siteLongitude, Double siteLatitude, Double siteArea, Double siteMarineArea, Double siteLength, String siteCharacteristics, String siteQuality, String siteDesignation, Set habitatClasses, Set specieses, Set habitats, Set siteRelations, Set siteOwnerships, Set nationalDtypes, Set regions, Set otherSpecieses, Set siteBiogeos, Set impacts) {
       this.siteCode = siteCode;
       this.map = map;
       this.doc = doc;
       this.mgmt = mgmt;
       this.resp = resp;
       this.siteType = siteType;
       this.siteName = siteName;
       this.siteCompDate = siteCompDate;
       this.siteUpdateDate = siteUpdateDate;
       this.siteSpaDate = siteSpaDate;
       this.siteSpaLegalRef = siteSpaLegalRef;
       this.siteSciPropDate = siteSciPropDate;
       this.siteSciConfDate = siteSciConfDate;
       this.siteSacDate = siteSacDate;
       this.siteSacLegalRef = siteSacLegalRef;
       this.siteExplanations = siteExplanations;
       this.siteLongitude = siteLongitude;
       this.siteLatitude = siteLatitude;
       this.siteArea = siteArea;
       this.siteMarineArea = siteMarineArea;
       this.siteLength = siteLength;
       this.siteCharacteristics = siteCharacteristics;
       this.siteQuality = siteQuality;
       this.siteDesignation = siteDesignation;
       this.habitatClasses = habitatClasses;
       this.specieses = specieses;
       this.habitats = habitats;
       this.siteRelations = siteRelations;
       this.siteOwnerships = siteOwnerships;
       this.nationalDtypes = nationalDtypes;
       this.regions = regions;
       this.otherSpecieses = otherSpecieses;
       this.siteBiogeos = siteBiogeos;
       this.impacts = impacts;
    }

    public String getSiteCode() {
        return this.siteCode;
    }

    public void setSiteCode(String siteCode) {
        this.siteCode = siteCode;
    }
    public Map getMap() {
        return this.map;
    }

    public void setMap(Map map) {
        this.map = map;
    }
    public Doc getDoc() {
        return this.doc;
    }

    public void setDoc(Doc doc) {
        this.doc = doc;
    }
    public Mgmt getMgmt() {
        return this.mgmt;
    }

    public void setMgmt(Mgmt mgmt) {
        this.mgmt = mgmt;
    }
    public Resp getResp() {
        return this.resp;
    }

    public void setResp(Resp resp) {
        this.resp = resp;
    }
    public Character getSiteType() {
        return this.siteType;
    }

    public void setSiteType(Character siteType) {
        this.siteType = siteType;
    }
    public String getSiteName() {
        return this.siteName;
    }

    public void setSiteName(String siteName) {
        this.siteName = siteName;
    }
    public Date getSiteCompDate() {
        return this.siteCompDate;
    }

    public void setSiteCompDate(Date siteCompDate) {
        this.siteCompDate = siteCompDate;
    }
    public Date getSiteUpdateDate() {
        return this.siteUpdateDate;
    }

    public void setSiteUpdateDate(Date siteUpdateDate) {
        this.siteUpdateDate = siteUpdateDate;
    }
    public Date getSiteSpaDate() {
        return this.siteSpaDate;
    }

    public void setSiteSpaDate(Date siteSpaDate) {
        this.siteSpaDate = siteSpaDate;
    }
    public String getSiteSpaLegalRef() {
        return this.siteSpaLegalRef;
    }

    public void setSiteSpaLegalRef(String siteSpaLegalRef) {
        this.siteSpaLegalRef = siteSpaLegalRef;
    }
    public Date getSiteSciPropDate() {
        return this.siteSciPropDate;
    }

    public void setSiteSciPropDate(Date siteSciPropDate) {
        this.siteSciPropDate = siteSciPropDate;
    }
    public Date getSiteSciConfDate() {
        return this.siteSciConfDate;
    }

    public void setSiteSciConfDate(Date siteSciConfDate) {
        this.siteSciConfDate = siteSciConfDate;
    }
    public Date getSiteSacDate() {
        return this.siteSacDate;
    }

    public void setSiteSacDate(Date siteSacDate) {
        this.siteSacDate = siteSacDate;
    }
    public String getSiteSacLegalRef() {
        return this.siteSacLegalRef;
    }

    public void setSiteSacLegalRef(String siteSacLegalRef) {
        this.siteSacLegalRef = siteSacLegalRef;
    }
    public String getSiteExplanations() {
        return this.siteExplanations;
    }

    public void setSiteExplanations(String siteExplanations) {
        this.siteExplanations = siteExplanations;
    }
    public Double getSiteLongitude() {
        return this.siteLongitude;
    }

    public void setSiteLongitude(Double siteLongitude) {
        this.siteLongitude = siteLongitude;
    }
    public Double getSiteLatitude() {
        return this.siteLatitude;
    }

    public void setSiteLatitude(Double siteLatitude) {
        this.siteLatitude = siteLatitude;
    }
    public Double getSiteArea() {
        return this.siteArea;
    }

    public void setSiteArea(Double siteArea) {
        this.siteArea = siteArea;
    }
    public Double getSiteMarineArea() {
        return this.siteMarineArea;
    }

    public void setSiteMarineArea(Double siteMarineArea) {
        this.siteMarineArea = siteMarineArea;
    }
    public Double getSiteLength() {
        return this.siteLength;
    }

    public void setSiteLength(Double siteLength) {
        this.siteLength = siteLength;
    }
    public String getSiteCharacteristics() {
        return this.siteCharacteristics;
    }

    public void setSiteCharacteristics(String siteCharacteristics) {
        this.siteCharacteristics = siteCharacteristics;
    }
    public String getSiteQuality() {
        return this.siteQuality;
    }

    public void setSiteQuality(String siteQuality) {
        this.siteQuality = siteQuality;
    }
    public String getSiteDesignation() {
        return this.siteDesignation;
    }

    public void setSiteDesignation(String siteDesignation) {
        this.siteDesignation = siteDesignation;
    }
    public Set getHabitatClasses() {
        return this.habitatClasses;
    }

    public void setHabitatClasses(Set habitatClasses) {
        this.habitatClasses = habitatClasses;
    }
    public Set getSpecieses() {
        return this.specieses;
    }

    public void setSpecieses(Set specieses) {
        this.specieses = specieses;
    }
    public Set getHabitats() {
        return this.habitats;
    }

    public void setHabitats(Set habitats) {
        this.habitats = habitats;
    }
    public Set getSiteRelations() {
        return this.siteRelations;
    }

    public void setSiteRelations(Set siteRelations) {
        this.siteRelations = siteRelations;
    }
    public Set getSiteOwnerships() {
        return this.siteOwnerships;
    }

    public void setSiteOwnerships(Set siteOwnerships) {
        this.siteOwnerships = siteOwnerships;
    }
    public Set getNationalDtypes() {
        return this.nationalDtypes;
    }

    public void setNationalDtypes(Set nationalDtypes) {
        this.nationalDtypes = nationalDtypes;
    }
    public Set getRegions() {
        return this.regions;
    }

    public void setRegions(Set regions) {
        this.regions = regions;
    }
    public Set getOtherSpecieses() {
        return this.otherSpecieses;
    }

    public void setOtherSpecieses(Set otherSpecieses) {
        this.otherSpecieses = otherSpecieses;
    }
    public Set getSiteBiogeos() {
        return this.siteBiogeos;
    }

    public void setSiteBiogeos(Set siteBiogeos) {
        this.siteBiogeos = siteBiogeos;
    }
    public Set getImpacts() {
        return this.impacts;
    }

    public void setImpacts(Set impacts) {
        this.impacts = impacts;
    }

    /**
     * @return the siteDateCreation
     */
    public Date getSiteDateCreation() {
        return siteDateCreation;
    }

    /**
     * @param siteDateCreation the siteDateCreation to set
     */
    public void setSiteDateCreation(Date siteDateCreation) {
        this.siteDateCreation = siteDateCreation;
    }

    /**
     * @return the siteDateDeletion
     */
    public Date getSiteDateDeletion() {
        return siteDateDeletion;
    }

    /**
     * @param siteDateDeletion the siteDateDeletion to set
     */
    public void setSiteDateDeletion(Date siteDateDeletion) {
        this.siteDateDeletion = siteDateDeletion;
    }

    /**
     * @return the sitedateUpdate
     */
    public Date getSiteDateUpdate() {
        return siteDateUpdate;
    }

    /**
     * @param sitedateUpdate the sitedateUpdate to set
     */
    public void setSiteDateUpdate(Date siteDateUpdate) {
        this.siteDateUpdate = siteDateUpdate;
    }


//    public Site duplicate(Site site) {
//
//
//    }


}


