package pojos;
// Generated 01-fvr.-2011 13:10:18 by Hibernate Tools 3.2.1.GA



/**
 * SiteOwnershipId generated by hbm2java
 */
public class SiteOwnershipId implements java.io.Serializable {


     private int ownershipId;
     private String siteCode;

    public SiteOwnershipId() {
    }

    public SiteOwnershipId(int ownershipId, String siteCode) {
       this.ownershipId = ownershipId;
       this.siteCode = siteCode;
    }

    public int getOwnershipId() {
        return this.ownershipId;
    }

    public void setOwnershipId(int ownershipId) {
        this.ownershipId = ownershipId;
    }
    public String getSiteCode() {
        return this.siteCode;
    }

    public void setSiteCode(String siteCode) {
        this.siteCode = siteCode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) {
             return true;
         }
         if ( (other == null ) ) {
             return false;
         }
         if ( !(other instanceof SiteOwnershipId) ) {
             return false;
         }
         SiteOwnershipId castOther = ( SiteOwnershipId ) other;

         return (this.getOwnershipId() == castOther.getOwnershipId())
 && ( (this.getSiteCode() == castOther.getSiteCode()) || ( this.getSiteCode() != null && castOther.getSiteCode() != null && this.getSiteCode().equals(castOther.getSiteCode()) ) );
   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + this.getOwnershipId();
         result = 37 * result + ( getSiteCode() == null ? 0 : this.getSiteCode().hashCode() );
         return result;
   }


}


