insert ignore into ref_hab_classes values (1,'N01','Marine areas, Sea inlets','Mer, Bras de Mer');
insert ignore into ref_hab_classes values (2,'N02','Tidal rivers, Estuaries, Mud flats, Sand flats, Lagoons (including saltwork basins)','Rivi�res et Estuaires soumis � la mar�e, Vasi�res et bancs de sable, Lagunes  (incluant les bassins de production de sel)');
insert ignore into ref_hab_classes values (3,'N03','Salt marshes, Salt pastures, Salt steppes','Marais salants, Pr�s sal�s, Steppes sal�es');
insert ignore into ref_hab_classes values (4,'N04','Coastal sand dunes, Sand beaches, Machair','Dunes, Plages de sables, Machair');
insert ignore into ref_hab_classes values (5,'N05','Shingle, Sea cliffs, Islets','Galets, Falaises maritimes, Ilots');
insert ignore into ref_hab_classes values (6,'N06','Inland water bodies (Standing water, Running water)','Eaux douces int�rieures (Eaux stagnantes, Eaux courantes)');
insert ignore into ref_hab_classes values (7,'N07','Bogs, Marshes, Water fringed vegetation, Fens','Marais (vegetation de ceinture), Bas-marais, Tourbi�res,');
insert ignore into ref_hab_classes values (8,'N08','Heath, Scrub, Maquis and Garrigue, Phygrana','Landes, Broussailles, Recrus, Maquis et Garrigues, Phrygana');
insert ignore into ref_hab_classes values (9,'N09','Dry grassland, Steppes','Pelouses s�ches, Steppes');
insert ignore into ref_hab_classes values (10,'N10','Humid grassland, Mesophile grassland','Prairies semi-naturelles humides, Prairies m�sophiles am�lior�es');
insert ignore into ref_hab_classes values (11,'N11','Alpine and sub-Alpine grassland','Pelouses alpine et sub-alpine');
insert ignore into ref_hab_classes values (12,'N12','Extensive cereal cultures (including Rotation cultures with regular fallowing)','Cultures c�r�ali�res extensives   (incluant les cultures en rotation avec une jach�re r�guli�re)');
insert ignore into ref_hab_classes values (13,'N13','Ricefields','Rizi�res');
insert ignore into ref_hab_classes values (14,'N14','Improved grassland','Prairies amelior�es');
insert ignore into ref_hab_classes values (15,'N15','Other arable land','Autres terres arables');
insert ignore into ref_hab_classes values (16,'N16','Broad-leaved deciduous woodland','For�ts caducifoli�es');
insert ignore into ref_hab_classes values (17,'N17','Coniferous woodland','For�ts de r�sineux');
insert ignore into ref_hab_classes values (18,'N18','Evergreen woodland','For�ts sempervirentes non r�sineuses');
insert ignore into ref_hab_classes values (19,'N19','Mixed woodland','For�ts mixtes');
insert ignore into ref_hab_classes values (20,'N20','Artificial forest monoculture (e.g. Plantations of poplar or Exotic trees)','For�t artificielle en monoculture (ex: Plantations de peupliers ou d''Arbres exotiques)');
insert ignore into ref_hab_classes values (21,'N21','Non-forest areas cultivated with woody plants (including Orchards, groves, Vineyards, Dehesas)','Zones de plantations d''arbres  (incluant les Vergers, Vignes,  Dehesas)');
insert ignore into ref_hab_classes values (22,'N22','Inland rocks, Screes, Sands, Permanent Snow and ice','Rochers int�rieurs, Eboulis rocheux,  Dunes int�rieures, Neige ou glace permanente');
insert ignore into ref_hab_classes values (23,'N23','Other land (including Towns, Villages, Roads, Waste places, Mines, Industrial sites)','Autres terres  (incluant les Zones urbanis�es et industrielles, Routes, D�charges, Mines)');
insert ignore into ref_hab_classes values (24,'N24','Marine and coastal habitats (general)','Habitats marins et c�tiers (en g�n�ral)');
insert ignore into ref_hab_classes values (25,'N25','Grassland and scrub habitats (general)','Prairies et broussailles (en g�n�ral)');
insert ignore into ref_hab_classes values (26,'N26','Woodland habitats (general)','For�ts (en g�n�ral)');
insert ignore into ref_hab_classes values (27,'N27','Agricultural habitats (general)','Agriculture (en g�n�ral)');
