update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A001';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A002';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A003';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A004';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A005';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A006';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A007';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Podiceps caspicus (A549)' where REF_BIRDS_CODE='A008';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A009';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Procellaria diomedea (A503)' where REF_BIRDS_CODE='A010';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A011';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A012';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A013';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A014';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A015';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Sula bassana' where REF_BIRDS_CODE='A016';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A017';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A018';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A019';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A020';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A021';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A022';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A023';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A024';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A025';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A026';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Casmerodius albus,  Ardea alba' where REF_BIRDS_CODE='A027';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A028';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A029';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A030';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A031';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A032';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A033';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A034';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A035';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A036';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Cygnus bewickii' where REF_BIRDS_CODE='A037';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A038';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A039';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A040';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A041';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A042';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A043';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A044';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A045';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A046';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A048';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A050';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A051';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A052';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A053';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A054';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A055';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A056';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A057';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A058';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A059';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A060';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A061';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A062';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A063';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A064';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A065';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A066';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A067';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Mergellus albellus' where REF_BIRDS_CODE='A068';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A069';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A070';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A071';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A072';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A073';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A074';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A075';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A076';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A077';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A078';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A079';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A080';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A081';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A082';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A083';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A084';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A085';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A086';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A087';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A088';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A089';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A090';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A091';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A092';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Aquila fasciatus' where REF_BIRDS_CODE='A093';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A094';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A095';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A096';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A097';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A098';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A099';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A100';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A101';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A102';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A103';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A104';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A105';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Lagopus muta' where REF_BIRDS_CODE='A106';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A107';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A108';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A109';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A110';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A111';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A112';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A113';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A115';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Turnix sylvaticus' where REF_BIRDS_CODE='A117';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A118';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A119';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A120';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A121';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A122';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A123';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A124';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A125';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A126';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A127';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A128';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A129';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A130';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A131';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A132';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A133';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A134';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A135';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A136';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A137';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A138';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Eudromias morinellus' where REF_BIRDS_CODE='A139';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A140';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A141';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A142';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A143';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A144';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A145';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A146';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A147';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A148';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A149';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A150';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A151';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A152';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A153';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A154';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A155';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A156';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A157';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A158';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A159';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A160';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A161';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A162';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A163';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A164';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A165';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A166';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Tringa cinerea (A518)' where REF_BIRDS_CODE='A167';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A168';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A169';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A170';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Phalaropus fulicaria' where REF_BIRDS_CODE='A171';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A172';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A173';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A174';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Stercorarius skua' where REF_BIRDS_CODE='A175';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A176';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A177';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Xema sabini' where REF_BIRDS_CODE='A178';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A179';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A180';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A181';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A182';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A183';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A184';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A185';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A186';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A187';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A188';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Sterna nilotica' where REF_BIRDS_CODE='A189';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A190';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A191';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A192';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A193';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A194';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A195';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Chlidonias hybrida' where REF_BIRDS_CODE='A196';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A197';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A198';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A199';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A200';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A202';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A203';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A204';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A205';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='livia and domestica' where REF_BIRDS_CODE='A206';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A207';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A208';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A209';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A210';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A211';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A212';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A213';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A214';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A215';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Bubo scandiaca' where REF_BIRDS_CODE='A216';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A217';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A218';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A219';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A220';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A221';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A222';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A223';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A224';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A225';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A226';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A227';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Apus melba' where REF_BIRDS_CODE='A228';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A229';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A230';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A231';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A232';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A233';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A234';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A235';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A236';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A237';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A238';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A239';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A240';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Dendrocopos tridactylus' where REF_BIRDS_CODE='A241';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A242';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A243';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A244';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A245';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A246';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A247';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A248';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A249';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Hirundo rupestris' where REF_BIRDS_CODE='A250';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A251';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A252';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Delichon urbicum' where REF_BIRDS_CODE='A253';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Anthus novaeseelandiae (A526)' where REF_BIRDS_CODE='A254';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A255';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A256';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A257';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A258';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A259';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A260';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Motacilla finere (A527)' where REF_BIRDS_CODE='A261';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A262';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A263';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A264';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A265';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A266';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A267';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Erythropygia galactotes' where REF_BIRDS_CODE='A268';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A269';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A270';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A271';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A272';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A273';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A274';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A275';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Saxicola torquata, Phoenicurus torquata (A567)' where REF_BIRDS_CODE='A276';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A277';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A278';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A279';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A280';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A281';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A282';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A283';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A284';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A285';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A286';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A287';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A288';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A289';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A290';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A291';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A292';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A293';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A294';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A295';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A296';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A297';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A298';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A299';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A300';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A301';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A302';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A303';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A304';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A305';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A306';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A307';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A308';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A309';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A310';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A311';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A312';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A313';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A314';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A315';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A316';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A317';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A318';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A319';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A320';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A321';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A322';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A323';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A324';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A325';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A326';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A327';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A328';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A329';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A330';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A331';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A332';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A333';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A334';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A335';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A336';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A337';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A338';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A339';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A340';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A341';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A342';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A343';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A344';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A345';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A346';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A347';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A348';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A349';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A350';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A351';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A352';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A353';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A354';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A355';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A356';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A357';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A358';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A359';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A360';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A361';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Serinus citrinella'  where REF_BIRDS_CODE='A362';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Carduelis chloris' where REF_BIRDS_CODE='A363';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A364';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A365';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A366';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A367';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A368';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A369';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A370';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A371';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A372';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A373';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A374';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A375';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A376';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A377';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A378';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A379';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A380';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A381';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A382';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Miliaria calandra' where REF_BIRDS_CODE='A383';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Puffinus mauretanicus' where REF_BIRDS_CODE='A384';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Pterodroma mollis madeira' where REF_BIRDS_CODE='A385';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Pterodroma mollis feae' where REF_BIRDS_CODE='A386';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A387';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A388';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A389';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A390';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A391';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A392';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A393';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A394';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A395';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A396';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A397';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A398';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A399';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A400';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A401';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A402';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A403';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A404';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Aquila heliaca adalberti' where REF_BIRDS_CODE='A405';
update ref_birds set REF_BIRDS_CODE_NEW='0'and  REF_BIRDS_ALT_SCIENTIFIC_NAME ='Lagopus muta pyrenaica' where REF_BIRDS_CODE='A407';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Lagopus muta helvetica' where REF_BIRDS_CODE='A408';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A409';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A410';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A411';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A412';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A413';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A414';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A415';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A416';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A417';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Vanellus spinosus' where REF_BIRDS_CODE='A418';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A419';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A420';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A421';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A422';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A423';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A424';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A425';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A426';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A427';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A428';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A429';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A430';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A431';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Anthus berthelotti' where REF_BIRDS_CODE='A432';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A433';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A434';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A435';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A436';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A437';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Hippolais pallida' where REF_BIRDS_CODE='A438';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A439';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A440';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Muscicapa latirostris' where REF_BIRDS_CODE='A441';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A442';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A443';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A444';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A445';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A446';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A447';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A448';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A449';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A450';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A451';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Rhodopechys githaginea (A546)' where REF_BIRDS_CODE='A452';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Pyrrhula pyrrhula murina' where REF_BIRDS_CODE='A453';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Cyanopica cyana' where REF_BIRDS_CODE='A454';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A455';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A456';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A457';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Larus argentatus cachinnans' where REF_BIRDS_CODE='A459';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A460';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A461';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Lagopus lagopus scotica' where REF_BIRDS_CODE='A462';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A463';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Puffinus puffinus yelkouan' where REF_BIRDS_CODE='A464';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A465';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A466';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Saxicola cypriaca, Oenanthe pleschanka cypriaca' where REF_BIRDS_CODE='A467';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A468';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A469';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A470';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A501';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A502';
update ref_birds set REF_BIRDS_CODE_NEW='1', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Calonectris diomedea' where REF_BIRDS_CODE='A503';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A504';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A505';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A506';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A507';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A508';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Aquila rapax nipalensis' where REF_BIRDS_CODE='A509';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Aquila rapax rapax' where REF_BIRDS_CODE='A510';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A511';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A512';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A513';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Grus virgo' where REF_BIRDS_CODE='A514';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A515';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A516';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A517';
update ref_birds set REF_BIRDS_CODE_NEW='1', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Xenus cinereus' where REF_BIRDS_CODE='A518';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A519';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A520';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A521';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A522';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A523';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A524';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A525';
update ref_birds set REF_BIRDS_CODE_NEW='1', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Anthus richardi' where REF_BIRDS_CODE='A526';
update ref_birds set REF_BIRDS_CODE_NEW='1', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Motacilla cinerea' where REF_BIRDS_CODE='A527';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A528';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A529';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A530';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A531';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Oenanthe finischii' where REF_BIRDS_CODE='A532';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A533';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A534';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Regulus regulus teneriffae' where REF_BIRDS_CODE='A535';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A536';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A537';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A538';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A539';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A540';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Emberiza leucocephala' where REF_BIRDS_CODE='A541';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A542';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A543';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A544';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A545';
update ref_birds set REF_BIRDS_CODE_NEW='1', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Bucanetes githagineus' where REF_BIRDS_CODE='A546';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A547';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A548';
update ref_birds set REF_BIRDS_CODE_NEW='1', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Podiceps nigricollis' where REF_BIRDS_CODE='A549';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A550';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A551';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Ardea virescens, Butorides striatus' where REF_BIRDS_CODE='A552';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A553';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A554';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A555';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A556';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A557';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A558';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A559';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A560';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A561';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A562';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A563';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A564';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A565';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A566';
update ref_birds set REF_BIRDS_CODE_NEW='1', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Saxicola torquata, Saxicola torquatus' where REF_BIRDS_CODE='A567';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A568';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A602';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A603';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Larus argentatus michahellis' where REF_BIRDS_CODE='A604';
update ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A605';
update ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Vanellus gregarius' where REF_BIRDS_CODE='A606';
insert ignore into ref_birds VALUES (537,'A607','Platalea leucorodia leucorodia','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (538,'A608','Motacilla citreola','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (539,'A609','Luscinia svecica svecica','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (540,'A610','Nycticorax nycticorax nycticorax','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (541,'A611','Luscinia svecica namnetum','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (542,'A612','Luscinia svecica cyanecula','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (543,'A613','Phylloscopus canariensis','0','0','0','0','0','0','Ph1lloscopus coll1bita canariensis');
insert ignore into ref_birds VALUES (544,'A614','Limosa limosa limosa','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (545,'A615','Corvus cornix','0','0','0','0','0','0','Corvus corone cornix');
insert ignore into ref_birds VALUES (546,'A616','Limosa limosa islandica','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (547,'A617','Ixobrychus minutus minutus','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (548,'A618','Phylloscopus ibericus','0','0','0','0','0','0','Ph1lloscopus coll1bita ibericus');
insert ignore into ref_birds VALUES (549,'A619','Accipiter gentilis gentilis','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (550,'A620','Passer domesticus','0','0','0','0','0','0','Passer domesticus domesticus');
insert ignore into ref_birds VALUES (551,'A621','Passer italiae','0','0','0','0','0','0','Passer domesticus italiae');
insert ignore into ref_birds VALUES (552,'A623','Carduelis citrinella','0','0','0','0','0','0','Serinus citrinella citrinella');
insert ignore into ref_birds VALUES (553,'A624','Chettusia leucura','0','0','0','0','0','0','Va0ellus leucurus');
insert ignore into ref_birds VALUES (554,'A625','Glareola pratincola pratincola','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (555,'A626','Lagopus mutus mutus','0','0','0','0','0','0','Lagopus muta muta');
insert ignore into ref_birds VALUES (556,'A627','Corvus corone','0','0','0','0','0','0','Corvus corone corone');
insert ignore into ref_birds VALUES (557,'A628','Lagopus mutus millaisi','0','0','0','0','0','0','Lagopus muta millaisi');
insert ignore into ref_birds VALUES (558,'A629','Lagopus lagopus rossica','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (559,'A630','Oceanodroma monteiroi','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (560,'A631','Sterna albifrons albifrons','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (561,'A632','Pluvialis apricaria apricaria','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (562,'A633','Accipiter nisus nisus','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (563,'A634','Ardea purpurea purpurea','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (564,'A635','Ardeola ralloides ralloides','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (565,'A636','Fringilla teydea teydea','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (566,'A637','Certhia brachydactyla all others','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (567,'A638','Grus grus all others','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (568,'A639','Grus grus grus','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (569,'A640','Larus fuscus fuscus','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (570,'A641','Larus fuscus intermedius','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (571,'A642','Podiceps auritus auritus','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (572,'A643','Fringilla teydea polatzeki','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (573,'A644','Perdix perdix all others','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (574,'A645','Sylvia undata undata','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (575,'A646','Sylvia undata dartfordiensis','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (576,'A647','Sylvia cantillans moltonii','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (577,'A648','Sylvia cantillans cantillans','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (578,'A649','Regulus regulus sanctaemariae','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (579,'A650','Regulus regulus inermis','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (580,'A651','Regulus regulus azoricus','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (581,'A652','Regulus madeirensis','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (582,'A653','Lanius excubitor excubitor','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (583,'A654','Mergus merganser merganser','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (584,'A655','Lanius excubitor meridionalis','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (585,'A656','Parus ater all others','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (586,'A657','Fringilla coelebs all others','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (587,'A658','Dendrocopos major all others','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (588,'A659','Tetrao urogallus all others','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (589,'A660','Gelochelidon nilotica nilotica','0','0','0','0','0','0','Sterna Nilotica');
insert ignore into ref_birds VALUES (590,'A661','Tetrao urogallus aquitanicus','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (591,'A662','Uria aalge albionis','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (592,'A663','Phoenicopterus roseus','0','0','0','0','0','0','Phoenicopterus ruber roseus');
insert ignore into ref_birds VALUES (593,'A664','Larus fuscus graellsii','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (594,'A665','Podiceps grisegena grisegena','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (595,'A666','Anthus petrosus','0','0','0','0','0','0','Anthus spinoletta petrosus');
insert ignore into ref_birds VALUES (596,'A667','Ciconia ciconia ciconia','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (597,'A668','Charadrius leschenaultii columbinus','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (598,'A669','Carduelis corsicana','0','0','0','0','0','0','Serinus citrinella corsicana');
insert ignore into ref_birds VALUES (599,'A670','Calidris maritima maritima','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (600,'A671','Calidris canutus islandica','0','0','0','0','0','0','Calidris canutus islandicus');
insert ignore into ref_birds VALUES (601,'A672','Calidris alpina alpina','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (602,'A673','Burhinus oedicnemus oedicnemus','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (603,'A674','Branta bernicla hrota','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (604,'A675','Branta bernicla bernicla','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (605,'A676','Troglodytes troglodytes all others','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (606,'A677','Apus affinis','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (607,'A678','Uria aalge aalge','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (608,'A679','Acrocephalus dumetorum','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (609,'A680','Acrocephalus agricola','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (610,'A681','Carduelis cabaret','0','0','0','0','0','0','Carduelis flammea cabaret');
insert ignore into ref_birds VALUES (611,'A682','Charadrius alexandrinus alexandrinus','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (612,'A683','Phalacrocorax carbo carbo','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (613,'A684','Phalacrocorax aristotelis aristotelis','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (614,'A685','Melanitta fusca fusca','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (615,'A686','Iduna caligata','0','0','0','0','0','0','Hippolais caligata');
insert ignore into ref_birds VALUES (616,'A687','Columba palumbus palumbus','0','0','0','0','0','0','');
insert ignore into ref_birds VALUES (617,'A688','Botaurus stellaris stellaris','0','0','0','0','0','0','');
commit;
