insert ignore into natura2000.`ownership` (`OWNERSHIP_ID`,`OWNERSHIP_TYPE`,`OWNERSHIP_CODE`) VALUES (1,'National/Federal','National/Federal');
insert ignore into natura2000.`ownership` (`OWNERSHIP_ID`,`OWNERSHIP_TYPE`,`OWNERSHIP_CODE`) VALUES (2,'State/Province','State/Province');
insert ignore into natura2000.`ownership` (`OWNERSHIP_ID`,`OWNERSHIP_TYPE`,`OWNERSHIP_CODE`) VALUES (3,'Local/Municipal','Local/Municipal');
insert ignore into natura2000.`ownership` (`OWNERSHIP_ID`,`OWNERSHIP_TYPE`,`OWNERSHIP_CODE`) VALUES (4,'Any public','Any public');
insert ignore into natura2000.`ownership` (`OWNERSHIP_ID`,`OWNERSHIP_TYPE`,`OWNERSHIP_CODE`) VALUES (5,'Joint or Co-Ownership','Joint or Co-Ownership');
insert ignore into natura2000.`ownership` (`OWNERSHIP_ID`,`OWNERSHIP_TYPE`,`OWNERSHIP_CODE`) VALUES (6,'Private','Private');
insert ignore into natura2000.`ownership` (`OWNERSHIP_ID`,`OWNERSHIP_TYPE`,`OWNERSHIP_CODE`) VALUES (7,'Unknown','Unknown');
update natura2000.ownership set ownership_code='publicNational' where ownership_id=1;
update natura2000.ownership set ownership_code='publicState' where ownership_id=2;
update natura2000.ownership set ownership_code='publicLocal' where ownership_id=3;
update natura2000.ownership set ownership_code='publicAny' where ownership_id=4;
update natura2000.ownership set ownership_code='joint' where ownership_id=5;
update natura2000.ownership set ownership_code='private' where ownership_id=6;
update natura2000.ownership set ownership_code='unknown' where ownership_id=7;
commit;