insert ignore into ref_designations values(1, 'AT00','Ohne Schutzstatus','');
insert ignore into ref_designations values(2, 'AT01','Nationalpark','A');
insert ignore into ref_designations values(3, 'AT02','Naturpark','A');
insert ignore into ref_designations values(4, 'AT03','Naturschutzgebiet','A');
insert ignore into ref_designations values(5, 'AT04','Landschaftsschutzgebiet','A');
insert ignore into ref_designations values(6, 'AT05','Ruhegebiet','A');
insert ignore into ref_designations values(7, 'AT06','Geschützter Landschaftsteil','A');
insert ignore into ref_designations values(8, 'AT07','Geschützte Grünbestände','A');
insert ignore into ref_designations values(9, 'AT08','Geschützte Naturgebilde von örtlicher Bedeutung','A');
insert ignore into ref_designations values(10, 'AT09','Sonstige Landschaftsteile','A');
insert ignore into ref_designations values(11, 'AT10','Naturdenkmal','A');
insert ignore into ref_designations values(12, 'AT11','Naturhöhlen','A');
insert ignore into ref_designations values(13, 'AT12','Baumschutz (in der Stadt Salzburg)','A');
insert ignore into ref_designations values(14, 'AT13','Moorschutz','A');
insert ignore into ref_designations values(15, 'AT14','Feuchtgebietsschutz','A');
insert ignore into ref_designations values(16, 'AT15','Auwaldschutz','A');
insert ignore into ref_designations values(17, 'AT16','Schutz stehender Gewässer (einschließlich Uferbereich)','A');
insert ignore into ref_designations values(18, 'AT17','Schutz fließender Gewässer (einschließlich Uferbereich)','A');
insert ignore into ref_designations values(19, 'AT18','Schutz der Gletscher','A');
insert ignore into ref_designations values(20, 'AT19','Schutz der Alpinregion (bzw. d. Alpinen Ödlandes)','A');
insert ignore into ref_designations values(21, 'AT20','','A');
insert ignore into ref_designations values(22, 'AT21','Seltene und bedrohte Planzenarten  (aufgelistet) sowie deren Lebensräume','A');
insert ignore into ref_designations values(23, 'AT22','Pilze','A');
insert ignore into ref_designations values(24, 'AT23','Geschützter Lebensraum','A');
insert ignore into ref_designations values(25, 'AT24','Besonders geschützte Höhle','A');
insert ignore into ref_designations values(26, 'AT25','Pflanzenschutzgebiet','A');
insert ignore into ref_designations values(27, 'AT26','Sümpfe und Quellfluren','A');
insert ignore into ref_designations values(28, 'AT27','Bruch- und Galeriewälder','A');
insert ignore into ref_designations values(29, 'AT28','Magerwiesen','A');
insert ignore into ref_designations values(30, 'AT29','Biosphärenpark','A');
insert ignore into ref_designations values(31, 'AT30','Europaschutzgebiet','A');
insert ignore into ref_designations values(32, 'AT31','Naturwaldzellen (Forstrecht)','B');
insert ignore into ref_designations values(33, 'AT32','Erholungswald (Forstrecht)','B');
insert ignore into ref_designations values(34, 'AT33','Schutzwald (Forstrecht)','B');
insert ignore into ref_designations values(35, 'AT34','Wasserschutzgebiete (Wasserrecht)','B');
insert ignore into ref_designations values(36, 'AT35','Wasserschongebiete (Wasserrecht)','B');
insert ignore into ref_designations values(37, 'AT36','Ökologisch besonders wertvolle Gebiete (Raumordnung)','B');
insert ignore into ref_designations values(38, 'AT37','Wasserwirtschaftliche Rahmenpläne','B');
insert ignore into ref_designations values(39, 'AT38','Wasserwirtschaftliche Rahmenverfügungen','B');
insert ignore into ref_designations values(40, 'AT46','Beweidungsprämien (zumeist in Halbtrockenrasen oder Almbereich)','C');
insert ignore into ref_designations values(41, 'AT51','Ökologische Entwicklungsfläche','A');
insert ignore into ref_designations values(42, 'AT52','Ex-lege-Schutz Wald und Wiesengürtel','A');
insert ignore into ref_designations values(43, 'AT53','Seen','A');
insert ignore into ref_designations values(44, 'AT54','Sonderschutzgebiete','A');
insert ignore into ref_designations values(45, 'AT98','Lake Protection Area','B');
insert ignore into ref_designations values(46, 'AT99','Anderen','');
insert ignore into ref_designations values(47, 'BE00','Geen beschermingsstatus - Aucun status de protection','');
insert ignore into ref_designations values(48, 'BE01','Réserve naturelle domaniale','A');
insert ignore into ref_designations values(49, 'BE02','Réserve naturelle agréée','A');
insert ignore into ref_designations values(50, 'BE03','Bosreservaat','A');
insert ignore into ref_designations values(51, 'BE04','Réserve Forestière','A');
insert ignore into ref_designations values(52, 'BE05','Parc naturel','B');
insert ignore into ref_designations values(53, 'BE06','Forêt certifiée','C');
insert ignore into ref_designations values(54, 'BE07','Vlaams natuurreservaat','A');
insert ignore into ref_designations values(55, 'BE08','Erkend natuurreservaat','A');
insert ignore into ref_designations values(56, 'BE09','Erkend boserervaat','A');
insert ignore into ref_designations values(57, 'BE10','Militaire domeinen onder het protocol','B');
insert ignore into ref_designations values(58, 'BE11','Beschermd duingebied','B');
insert ignore into ref_designations values(59, 'BE12','Gerangschikt landschap','B');
insert ignore into ref_designations values(60, 'BE13','Openbaar bos','B');
insert ignore into ref_designations values(61, 'BE14','Site naturel d''interêt scientifique','A');
insert ignore into ref_designations values(62, 'BE15','Andere - Autres','');
insert ignore into ref_designations values(63, 'BE16','Vlaams Ecologisch Netwerk','B');
insert ignore into ref_designations values(64, 'BE21','Réserve naturelle privée','C');
insert ignore into ref_designations values(65, 'BE30','Réserve naturelle régionale - Regionaal natuurreservaat','A');
insert ignore into ref_designations values(66, 'BE31','Réserve naturelle agréée - Erkend natuurreservaat','A');
insert ignore into ref_designations values(67, 'BE32','Réserve forestière - Bosreservaat','A');
insert ignore into ref_designations values(68, 'BE33','Zone de protection en forêt -  Beschermingszone in het bos','B');
insert ignore into ref_designations values(69, 'BE34','Zone vertes de haute valeur biologique - Groengebieden met hoogbiologische waarde','B');
insert ignore into ref_designations values(70, 'BE99','Andere - Autres','');
insert ignore into ref_designations values(71, 'BG00','No Protection Status','');
insert ignore into ref_designations values(72, 'BG01','Rezervat','A');
insert ignore into ref_designations values(73, 'BG02','Nacionalen Park','A');
insert ignore into ref_designations values(74, 'BG03','Prirodna Zabelezhitelnost','A');
insert ignore into ref_designations values(75, 'BG04','Poddarzhan Rezarvat','A');
insert ignore into ref_designations values(76, 'BG05','Priroden Park','A');
insert ignore into ref_designations values(77, 'BG06','Zashtitena Mestnost','A');
insert ignore into ref_designations values(78, 'BG08','Zashtiteni Zoni po Bird Directive','A');
insert ignore into ref_designations values(79, 'BG09','Zashtiteni Zoni po Habitat Directive','A');
insert ignore into ref_designations values(80, 'BG21','Darzhavni Lovni Stopanstva','B');
insert ignore into ref_designations values(81, 'BG22','Zashtitni gori','B');
insert ignore into ref_designations values(82, 'BG23','Rekreatzionni gori','B');
insert ignore into ref_designations values(83, 'BG31','Ribovadni stopanstva','C');
insert ignore into ref_designations values(84, 'BG99','Others','');
insert ignore into ref_designations values(85, 'CY00','No Protection Status','');
insert ignore into ref_designations values(86, 'CY01','State Forest Area','B');
insert ignore into ref_designations values(87, 'CY02','Permanent Forest Reserve','B');
insert ignore into ref_designations values(88, 'CY03','National Forest Park','A');
insert ignore into ref_designations values(89, 'CY04','Nature Reserve','A');
insert ignore into ref_designations values(90, 'CY05','Game Reserve ("Hunting Preserve")','A');
insert ignore into ref_designations values(91, 'CY06','Turtle Nesting Beach','A');
insert ignore into ref_designations values(92, 'CY07','Milli Park','A');
insert ignore into ref_designations values(93, 'CY08','Marine Reserve','A');
insert ignore into ref_designations values(94, 'CY41','','');
insert ignore into ref_designations values(95, 'CY99','Other','');
insert ignore into ref_designations values(96, 'CZ00','No Protection Status','');
insert ignore into ref_designations values(97, 'CZ01','Národní prírodní rezervace (NPR)','A');
insert ignore into ref_designations values(98, 'CZ02','Prírodní rezervace (PR)','A');
insert ignore into ref_designations values(99, 'CZ03','Národní prírodní památka (NPP)','A');
insert ignore into ref_designations values(100, 'CZ04','Prírodní památka (PP)','A');
insert ignore into ref_designations values(101, 'CZ05','Ochranné pásmo NPR,NPP,PR,PP','A');
insert ignore into ref_designations values(102, 'CZ06','Prechodne chránená plocha','A');
insert ignore into ref_designations values(103, 'CZ07','Národní park','A');
insert ignore into ref_designations values(104, 'CZ08','Ochranné pásmo národního parku','A');
insert ignore into ref_designations values(105, 'CZ09','Chránená krajinná oblast (CHKO)','A');
insert ignore into ref_designations values(106, 'CZ10','územní systémy ekologické stability','A');
insert ignore into ref_designations values(107, 'CZ11','Významný krajinný prvek','A');
insert ignore into ref_designations values(108, 'CZ12','prírodní park','A');
insert ignore into ref_designations values(109, 'CZ13','jeskyne','A');
insert ignore into ref_designations values(110, 'CZ21','lesy ochranné','B');
insert ignore into ref_designations values(111, 'CZ22','lesy zvláštního urcení','B');
insert ignore into ref_designations values(112, 'CZ23','chránené rybí oblasti','B');
insert ignore into ref_designations values(113, 'CZ24','chránené oblasti prirozené akumulace vod','B');
insert ignore into ref_designations values(114, 'CZ25','ochranná pásma vodních zdroju','B');
insert ignore into ref_designations values(115, 'CZ26','ochranná pásma prírodních lécivých zdroju a zdroju  prírodních minerálních vod','B');
insert ignore into ref_designations values(116, 'CZ27','kulturní památka','B');
insert ignore into ref_designations values(117, 'CZ28','památkové zóny','B');
insert ignore into ref_designations values(118, 'CZ99','Other','');
insert ignore into ref_designations values(119, 'DE00','Ohne Schutzstatus','');
insert ignore into ref_designations values(120, 'DE01','Nationalpark','A');
insert ignore into ref_designations values(121, 'DE02','Naturschutzgebiet','A');
insert ignore into ref_designations values(122, 'DE03','Flächenhaftes Naturdenkmal','A');
insert ignore into ref_designations values(123, 'DE04','Geschütztes Landschaftsbestandteil','A');
insert ignore into ref_designations values(124, 'DE05','Naturpark','A');
insert ignore into ref_designations values(125, 'DE06','Artenschon- und Artnschutzgebiete','A');
insert ignore into ref_designations values(126, 'DE07','Landschaftschutzgebiet','A');
insert ignore into ref_designations values(127, 'DE08','Naturmonumente ','A');
insert ignore into ref_designations values(128, 'DE11','Waldschutzgebiet ohne forstliche Nutzung','B');
insert ignore into ref_designations values(129, 'DE12','Waldschutzgebiet mit eingeschränkter Nutzung','B');
insert ignore into ref_designations values(130, 'DE13','Schutzwald (Boden-,Erosions-, Lawinenschutz)','B');
insert ignore into ref_designations values(131, 'DE21','im Besitz/Eigentum einer Naturschutzorganisation/ Natur(schutz) stiftung ','C');
insert ignore into ref_designations values(132, 'DE22','privatrechtliche (vertragliche) Sicherung, die einen dauerhaften Schutz für Fauna, Flora oder Lebensräume bietet','C');
insert ignore into ref_designations values(133, 'DE23','Vereinbarungen zum Naturschutz auf militärischen Liegenschaften ','C');
insert ignore into ref_designations values(134, 'DE99','Anderen','');
insert ignore into ref_designations values(135, 'DK01','Fredet ved afgørelse, exl. Kirkeomgivelser','A');
insert ignore into ref_designations values(136, 'DK02','Naturreservat','A');
insert ignore into ref_designations values(137, 'DK03','§3 beskyttet natur (alle søer, moser, vandløb, heder, enge  mv)','A');
insert ignore into ref_designations values(138, 'DK05','Natur- og vildtreservater (inkl. statsejede arealer til havs)','A');
insert ignore into ref_designations values(139, 'DK11','Statsskov udlagt  urørt / med gl.driftsform','B');
insert ignore into ref_designations values(140, 'DK22','Nationalpark','A');
insert ignore into ref_designations values(141, 'DK95','Egekrat beskyttet efter skovloven','A');
insert ignore into ref_designations values(142, 'DK98','Klitfredede arealer','A');
insert ignore into ref_designations values(143, 'EE01','Looduskaitseala loodusreservaat','A');
insert ignore into ref_designations values(144, 'EE02','Looduskaitseala looduslik sihtkaitsevöönd','A');
insert ignore into ref_designations values(145, 'EE03','Looduskaitseala hooldatav sihtkaitsevöönd','A');
insert ignore into ref_designations values(146, 'EE04','Looduskaitseala piiranguvöönd','A');
insert ignore into ref_designations values(147, 'EE05','Looduskaitseala','A');
insert ignore into ref_designations values(148, 'EE06','Rahvuspargi loodusreservaat','A');
insert ignore into ref_designations values(149, 'EE07','Rahvuspargi looduslik sihtkaitsevöönd','A');
insert ignore into ref_designations values(150, 'EE08','Rahvuspargi hooldatav sihtkaitsevöönd','A');
insert ignore into ref_designations values(151, 'EE09','Rahvuspargi piiranguvöönd','A');
insert ignore into ref_designations values(152, 'EE10','Rahvuspark','A');
insert ignore into ref_designations values(153, 'EE11','Maastikukaitseala looduslik sihtkaitsevöönd','A');
insert ignore into ref_designations values(154, 'EE12','Maastikukaitseala hooldatav sihtkaitsevöönd','A');
insert ignore into ref_designations values(155, 'EE13','Maastikukaitseala piiranguvöönd','A');
insert ignore into ref_designations values(156, 'EE14','Maastikukaitseala','A');
insert ignore into ref_designations values(157, 'EE15','Tsoneerimata kaitseala','A');
insert ignore into ref_designations values(158, 'EE16','Püsielupaik','A');
insert ignore into ref_designations values(159, 'EE17','Hoiuala','A');
insert ignore into ref_designations values(160, 'EE18','Kaitstav looduse üksikobjekt','A');
insert ignore into ref_designations values(161, 'EE19','','');
insert ignore into ref_designations values(162, 'EE20','Koelmuala','A');
insert ignore into ref_designations values(163, 'EE23','Võtmebiotoop ehk vääriselupaik','B');
insert ignore into ref_designations values(164, 'EE24','Muinsuskaitseala','B');
insert ignore into ref_designations values(165, 'EE25','Mälestis','B');
insert ignore into ref_designations values(166, 'EE27','Keskkonnaseire jaam või ala','B');
insert ignore into ref_designations values(167, 'EE28','Ranna või kalda ehituskeeluvöönd','B');
insert ignore into ref_designations values(168, 'EE29','Ranna või kalda piiranguvöönd','B');
insert ignore into ref_designations values(169, 'EE30','Ranna või kalda veekaitsevöönd','B');
insert ignore into ref_designations values(170, 'EE33','Veehaarde sanitaarkaitseala','B');
insert ignore into ref_designations values(171, 'EE34','Nitraaditundlik ala','B');
insert ignore into ref_designations values(172, 'EE41','Kohaliku omavalitsuse tasandil kaitstav loodusobjekt','A');
insert ignore into ref_designations values(173, 'EE42','Püsielupaiga sihtkaitsevöönd','A');
insert ignore into ref_designations values(174, 'EE43','Püsielupaiga piiranguvöönd','A');
insert ignore into ref_designations values(175, 'EE44','Kohaliku omavalitsuse tasandil kaitstava loodusobjekti piiranguvöönd','A');
insert ignore into ref_designations values(176, 'EE99','Muud','');
insert ignore into ref_designations values(177, 'ES00','Sin estatuto de proteción','');
insert ignore into ref_designations values(178, 'ES01','Reserva Natural Especial','A');
insert ignore into ref_designations values(179, 'ES02','Reserva Integral','A');
insert ignore into ref_designations values(180, 'ES03','Área Marina Protegida','A');
insert ignore into ref_designations values(181, 'ES04','Reserva Natural','A');
insert ignore into ref_designations values(182, 'ES05','Reserva Natural de Fauna Salvaje','A');
insert ignore into ref_designations values(183, 'ES06','Reserva Natural Parcial','A');
insert ignore into ref_designations values(184, 'ES07','Reserva Natural Integral','A');
insert ignore into ref_designations values(185, 'ES08','Parque Nacional','A');
insert ignore into ref_designations values(186, 'ES09','Parque Periurbano','A');
insert ignore into ref_designations values(187, 'ES10','Parque Natural','A');
insert ignore into ref_designations values(188, 'ES11','Parque Regional','A');
insert ignore into ref_designations values(189, 'ES12','Parque Periurbano de Conservación y Ocio','A');
insert ignore into ref_designations values(190, 'ES13','Paraje Natural','A');
insert ignore into ref_designations values(191, 'ES14','Paraje Natural de Interés Nacional','A');
insert ignore into ref_designations values(192, 'ES15','Paraje Natural Municipal','A');
insert ignore into ref_designations values(193, 'ES16','Sitio Natural de Interés Nacional','A');
insert ignore into ref_designations values(194, 'ES17','Lugar de Interés Científico','A');
insert ignore into ref_designations values(195, 'ES18','Enclave Natural','A');
insert ignore into ref_designations values(196, 'ES19','Monumento Natural','A');
insert ignore into ref_designations values(197, 'ES20','Monumento Natural de Interés Nacional','A');
insert ignore into ref_designations values(198, 'ES21','Árbol Singular','A');
insert ignore into ref_designations values(199, 'ES22','Espacio Natural Protegido','A');
insert ignore into ref_designations values(200, 'ES24','Área Natural Recreativa','A');
insert ignore into ref_designations values(201, 'ES25','Paraje Pintoresco','A');
insert ignore into ref_designations values(202, 'ES30','Reserva Natural Concertada','A');
insert ignore into ref_designations values(203, 'ES31','Reserva Natural Dirigida','A');
insert ignore into ref_designations values(204, 'ES32','Microrreserva','A');
insert ignore into ref_designations values(205, 'ES33','Reserva de la Biosfera','A');
insert ignore into ref_designations values(206, 'ES34','Humedal Protegido','A');
insert ignore into ref_designations values(207, 'ES40','Área Natural Singular','A');
insert ignore into ref_designations values(208, 'ES43','Plan Especial de Protección (PEIN)','A');
insert ignore into ref_designations values(209, 'ES44','Reserva de Fauna','A');
insert ignore into ref_designations values(210, 'ES45','Sitio de Interés','A');
insert ignore into ref_designations values(211, 'ES46','Zona de Especial Conservación de Importancia Comunitaria','A');
insert ignore into ref_designations values(212, 'ES47','Zona de Interes Regional','A');
insert ignore into ref_designations values(213, 'ES48','Zona de la Red Ecológica Europea Natura 2000','A');
insert ignore into ref_designations values(214, 'ES50','Zonas Húmedas','A');
insert ignore into ref_designations values(215, 'ES51','Cuevas','A');
insert ignore into ref_designations values(216, 'ES89','Reserva Natural Marina','A');
insert ignore into ref_designations values(217, 'ES90','Bitopo Protegido','A');
insert ignore into ref_designations values(218, 'ES91','Reserva Fluvial','A');
insert ignore into ref_designations values(219, 'ES92','Parque Rural','A');
insert ignore into ref_designations values(220, 'ES93','Sitio de Interés Científico','A');
insert ignore into ref_designations values(221, 'ES94','Paisaje Protegido','A');
insert ignore into ref_designations values(222, 'ES95','Zona Especial de Conservación','A');
insert ignore into ref_designations values(223, 'ES96','Zona de Especial Protección de los Valores Naturales','A');
insert ignore into ref_designations values(224, 'ES97','Corredor Ecológico y de Biodiversidad','A');
insert ignore into ref_designations values(225, 'ES98','Refugio de Fauna','A');
insert ignore into ref_designations values(226, 'ES99','Other','');
insert ignore into ref_designations values(227, 'FI00','Ei suojeltu','');
insert ignore into ref_designations values(228, 'FI01','Luonnonpuisto','A');
insert ignore into ref_designations values(229, 'FI02','Kansallispuisto','A');
insert ignore into ref_designations values(230, 'FI03','Valtion luonnonsuojelualue','A');
insert ignore into ref_designations values(231, 'FI04','Luonnonmuistomerkki','A');
insert ignore into ref_designations values(232, 'FI11','Erämaa-alue','B');
insert ignore into ref_designations values(233, 'FI12','Valtion retkeilyalue','B');
insert ignore into ref_designations values(234, 'FI13','Metsähallituksen päätöksella suojeltu valtion metsä','B');
insert ignore into ref_designations values(235, 'FI14','Maa-aineslain nojalla suojeltu harju-tai kallioalue','B');
insert ignore into ref_designations values(236, 'FI15','Koskiensuojelulain nojalla suojeltu vesistö','B');
insert ignore into ref_designations values(237, 'FI16','Yksityinen luonnonsuojelualue','C');
insert ignore into ref_designations values(238, 'FI17','Luonnonmuistomerkki yksityismaalla','C');
insert ignore into ref_designations values(239, 'FI92','Määräaikainen rauhoitus','C');
insert ignore into ref_designations values(240, 'FI93','Erityisesti suojeltavan lajin esiintymispaikka','A');
insert ignore into ref_designations values(241, 'FI94','Suojeltu luontotyyppi','A');
insert ignore into ref_designations values(242, 'FI95','Hylkeidensuojelualue','A');
insert ignore into ref_designations values(243, 'FI96','Vanhojen metsien suojelualue','A');
insert ignore into ref_designations values(244, 'FI97','Lehtojensuojelualue','A');
insert ignore into ref_designations values(245, 'FI98','Soidensuojelualue','A');
insert ignore into ref_designations values(246, 'FI99','Muut','');
insert ignore into ref_designations values(247, 'FR00','Aucun status de protection','');
insert ignore into ref_designations values(248, 'FR01','Parc National - Cœur','A');
insert ignore into ref_designations values(249, 'FR02','Parc National - Réserve integrale','A');
insert ignore into ref_designations values(250, 'FR03','Réserve Naturelle Nationale','A');
insert ignore into ref_designations values(251, 'FR04','Réserve Naturelle volontaire','A');
insert ignore into ref_designations values(252, 'FR05','Arrêté Préfectoral de protection de Biotope','A');
insert ignore into ref_designations values(253, 'FR06','Réserve Biologique','A');
insert ignore into ref_designations values(254, 'FR07','Réserve Biologique Domaniale dirigée','A');
insert ignore into ref_designations values(255, 'FR08','Réserve Biologique Forestière intégrale','A');
insert ignore into ref_designations values(256, 'FR11','Forêt de Protection','B');
insert ignore into ref_designations values(257, 'FR12','Site/Monument inscrit','B');
insert ignore into ref_designations values(258, 'FR13','Site/Monument classé','B');
insert ignore into ref_designations values(259, 'FR14','Site acquis par le conservatoire de l''espace littoral et des rivages lacustres','B');
insert ignore into ref_designations values(260, 'FR15','Parc Naturel Régional','B');
insert ignore into ref_designations values(261, 'FR16','Parc National - Aire d''adhésion','B');
insert ignore into ref_designations values(262, 'FR17','Réserve Nationale de Chasse et de Faune Sauvage','A');
insert ignore into ref_designations values(263, 'FR18','Réserve de chasse du domaine public maritime','B');
insert ignore into ref_designations values(264, 'FR19','Réserve de chasse du domaine public fluvial','B');
insert ignore into ref_designations values(265, 'FR20','Réserve de chasse approuvée','B');
insert ignore into ref_designations values(266, 'FR21','Réserve de pêche du domaine public fluvial','B');
insert ignore into ref_designations values(267, 'FR22','Réserve Naturelle Conventionelle','B');
insert ignore into ref_designations values(268, 'FR23','Forêt Domaniale','B');
insert ignore into ref_designations values(269, 'FR24','Forêt Communale Bénéficiant du Régime Forestier','B');
insert ignore into ref_designations values(270, 'FR31','Site acquis par un Conservatoire des Sites','C');
insert ignore into ref_designations values(271, 'FR32','Site acquis par le Département','B');
insert ignore into ref_designations values(272, 'FR33','Réserve libre (à caractère privé)','C');
insert ignore into ref_designations values(273, 'FR34','Parc Naturel Marin','B');
insert ignore into ref_designations values(274, 'FR35','Réserve Naturelle Régionale','A');
insert ignore into ref_designations values(275, 'FR36','Réserve Naturelle de la collectivité territoriale de Corse','A');
insert ignore into ref_designations values(276, 'FR37','Périmètre de protection d’une réserve naturelle nationale','B');
insert ignore into ref_designations values(277, 'FR38','Périmètre de protection d’une réserve naturelle régionale ou de Corse','B');
insert ignore into ref_designations values(278, 'FR99','Autres','');
insert ignore into ref_designations values(279, 'GR00','No Protection Status','');
insert ignore into ref_designations values(280, 'GR01','Periochi apolytis prostasias tis fysis','A');
insert ignore into ref_designations values(281, 'GR02','Periochi apolytis prostasias tis fysis se ethniko parko','A');
insert ignore into ref_designations values(282, 'GR03','Periochi apolytis prostasias tis fysis se thalassio parko','A');
insert ignore into ref_designations values(283, 'GR04','Periochi apolytis prostasias tis fysis se periochi oikoanaptyksis','A');
insert ignore into ref_designations values(284, 'GR05','Ethnikos Drymos (pirinas)','A');
insert ignore into ref_designations values(285, 'GR06','Diatiriteo mnimeio tis fysis','A');
insert ignore into ref_designations values(286, 'GR07','Periochi prostasias tis fysis','A');
insert ignore into ref_designations values(287, 'GR08','Periochi prostasias tis fysis se ethniko parko','A');
insert ignore into ref_designations values(288, 'GR09','Periochi prostasias tis fysis se thalassio parko','A');
insert ignore into ref_designations values(289, 'GR10','Periochi prostasias tis fysis se Periochi Oikoanaptyksis','A');
insert ignore into ref_designations values(290, 'GR11','Ethnikos Drymos (perifereiaki zoni)','A');
insert ignore into ref_designations values(291, 'GR12','Aisthitiko dasos','A');
insert ignore into ref_designations values(292, 'GR21','Ektrofeio thiramaton','B');
insert ignore into ref_designations values(293, 'GR23','Elenchomeni kynigetiki periochi','B');
insert ignore into ref_designations values(294, 'GR24','Prostatevomeno dasos','B');
insert ignore into ref_designations values(295, 'GR28','Prostatevomenos fysikos schimatismos, prostatevomeno topio kai stoiheia tou topiou','B');
insert ignore into ref_designations values(296, 'GR90','Periferiaki zoni periohis prostasias tis fysis','A');
insert ignore into ref_designations values(297, 'GR91','Periferiaki zoni Ethnikou Thalassiou  Parkou','A');
insert ignore into ref_designations values(298, 'GR92','Periferiaki zoni Ethnikou Parkou','A');
insert ignore into ref_designations values(299, 'GR93','Periferiaki zoni periohis oikoanaptixis','A');
insert ignore into ref_designations values(300, 'GR94','Periohi Oikoanaptyxis','A');
insert ignore into ref_designations values(301, 'GR95','Katafygio Agrias Zois','A');
insert ignore into ref_designations values(302, 'GR96','Ethniko Parko','A');
insert ignore into ref_designations values(303, 'GR97','Ethniko Thalassio Parko','A');
insert ignore into ref_designations values(304, 'GR98','Prostatevomeni periochi pou den echei haraktiristei','A');
insert ignore into ref_designations values(305, 'GR99','Alla','A');
insert ignore into ref_designations values(306, 'HR00','Bez zaštite','');
insert ignore into ref_designations values(307, 'HR01','Strogi rezervat','A');
insert ignore into ref_designations values(308, 'HR02','Posebni rezervat','A');
insert ignore into ref_designations values(309, 'HR03','Nacionalni park','A');
insert ignore into ref_designations values(310, 'HR04','Park prirode','A');
insert ignore into ref_designations values(311, 'HR05','Regionalni park','A');
insert ignore into ref_designations values(312, 'HR06','Spomenik prirode','A');
insert ignore into ref_designations values(313, 'HR07','Značajni krajobraz','A');
insert ignore into ref_designations values(314, 'HR08','Park šuma','A');
insert ignore into ref_designations values(315, 'HR09','Spomenih parkovne arhitekture','A');
insert ignore into ref_designations values(316, 'HR99','Ostalo','');
insert ignore into ref_designations values(317, 'HU00','Nem védett','');
insert ignore into ref_designations values(318, 'HU01','Nemzeti Park','A');
insert ignore into ref_designations values(319, 'HU02','Tajvédelmi Körzet','A');
insert ignore into ref_designations values(320, 'HU03','Természetvédelmi Terület','A');
insert ignore into ref_designations values(321, 'HU04','Helyi jelentõségû védett terület','A');
insert ignore into ref_designations values(322, 'HU05','Erdõrezervátum','A');
insert ignore into ref_designations values(323, 'HU06','Ex lege védett láp','A');
insert ignore into ref_designations values(324, 'HU07','Ex lege védett szikes tó','A');
insert ignore into ref_designations values(325, 'HU08','Természeti emlék','A');
insert ignore into ref_designations values(326, 'HU09','Barlang','A');
insert ignore into ref_designations values(327, 'HU10','Érzékeny Természeti Területek','B');
insert ignore into ref_designations values(328, 'HU11','Natúrpark','A');
insert ignore into ref_designations values(329, 'HU99','Egyéb','');
insert ignore into ref_designations values(330, 'IE00','No Protection Status','');
insert ignore into ref_designations values(331, 'IE01','National Nature Reserve','A');
insert ignore into ref_designations values(332, 'IE02','National Nature Reserve','A');
insert ignore into ref_designations values(333, 'IE03','National Park','A');
insert ignore into ref_designations values(334, 'IE04','Refuge for Fauna','A');
insert ignore into ref_designations values(335, 'IE05','No shooting area (Wildfowl Sanctuary)','A');
insert ignore into ref_designations values(336, 'IE11','Fresh waters designated under terms of Directive 87/659/EEC','B');
insert ignore into ref_designations values(337, 'IE13','Special amenity area order','B');
insert ignore into ref_designations values(338, 'IE21','Land owned by a non-governmental organisation for nature conservation','C');
insert ignore into ref_designations values(339, 'IE97','Refuge for Flora','A');
insert ignore into ref_designations values(340, 'IE98','Natural Heritage Area','A');
insert ignore into ref_designations values(341, 'IE99','Others','');
insert ignore into ref_designations values(342, 'IT00','Nessun tipo di protezione','');
insert ignore into ref_designations values(343, 'IT01','Parco Nazionale','A');
insert ignore into ref_designations values(344, 'IT02','Riserva Naturale Statale','A');
insert ignore into ref_designations values(345, 'IT03','Parco naturale interregionale','A');
insert ignore into ref_designations values(346, 'IT04','Parco naturale regionale/provinciale','A');
insert ignore into ref_designations values(347, 'IT05','Riserva naturale regionale/provinciale','A');
insert ignore into ref_designations values(348, 'IT06','Monumenti naturali','A');
insert ignore into ref_designations values(349, 'IT07','Oasi di protezione della fauna','B');
insert ignore into ref_designations values(350, 'IT11','Bellezze naturali','B');
insert ignore into ref_designations values(351, 'IT12','Aree di verde urbano','B');
insert ignore into ref_designations values(352, 'IT13','Vincoli idrogeologici','B');
insert ignore into ref_designations values(353, 'IT14','Aree di salvaguardia delle acque superficiali e sotterranee destinate al consumo umano','B');
insert ignore into ref_designations values(354, 'IT21','Oasi di protezione costituite da soggetti privati','C');
insert ignore into ref_designations values(355, 'IT22','Fondi Chiusi','C');
insert ignore into ref_designations values(356, 'IT30','Altre Aree Naturali Protette Regionali','A');
insert ignore into ref_designations values(357, 'IT31','Bosco da seme','A');
insert ignore into ref_designations values(358, 'IT32','Zona di protezione lungo le rotte di migrazione dell''avifauna','B');
insert ignore into ref_designations values(359, 'IT33','Zona di ripopolamento e cattura','B');
insert ignore into ref_designations values(360, 'IT34','Aree Contigue alle Aree Protette','A');
insert ignore into ref_designations values(361, 'IT35','Beni ambientali','B');
insert ignore into ref_designations values(362, 'IT36','Aree sensibili','B');
insert ignore into ref_designations values(363, 'IT37','Area Naturale Marina di interesse internazionale','A');
insert ignore into ref_designations values(364, 'IT41','Siti di Importanza Comunitaria','A');
insert ignore into ref_designations values(365, 'IT42','Zona di Protezione Speciale','A');
insert ignore into ref_designations values(366, 'IT43','Zone vulnerabili da nitrati','B');
insert ignore into ref_designations values(367, 'IT44','Acque idonee alla vita dei pesci','B');
insert ignore into ref_designations values(368, 'IT45','Acque idonee alla vita dei molluschi','B');
insert ignore into ref_designations values(369, 'IT90','Riserva Naturale Marina e Aree Naturali Marine Protette','A');
insert ignore into ref_designations values(370, 'IT94','Zona di Tutela Biologica Marina','A');
insert ignore into ref_designations values(371, 'IT95','Azienda Faunistico-Venatoria','C');
insert ignore into ref_designations values(372, 'IT99','Altri','');
insert ignore into ref_designations values(373, 'LT00','No Protection Status','');
insert ignore into ref_designations values(374, 'LT01','Valstybinis rezervatas','A');
insert ignore into ref_designations values(375, 'LT02','Gamtinis draustinis','A');
insert ignore into ref_designations values(376, 'LT03','Valstybinis parkas','A');
insert ignore into ref_designations values(377, 'LT04','Biosferos rezervatas','A');
insert ignore into ref_designations values(378, 'LT05','Atkuriamasis sklypas','A');
insert ignore into ref_designations values(379, 'LT06','Biosferos poligonas','A');
insert ignore into ref_designations values(380, 'LT99','Other','');
insert ignore into ref_designations values(381, 'LU00','Aucun statut de protection','');
insert ignore into ref_designations values(382, 'LU01','Zones RAMSAR','');
insert ignore into ref_designations values(383, 'LU02','Zones protégées d''intérêt national - Réserve naturelle','A');
insert ignore into ref_designations values(384, 'LU03','Zones protégées d''intérêt national - Réserve forestière intégrale','A');
insert ignore into ref_designations values(385, 'LU04','Zones protégées d''intérêt national - Paysage Protégé','A');
insert ignore into ref_designations values(386, 'LU05','Parc Naturel','A');
insert ignore into ref_designations values(387, 'LU06','Zones protégées d''intérêt communautaire - Zones Habitats ZSC','A');
insert ignore into ref_designations values(388, 'LU07','Zones protégées d''intérêt communautaire - Zones Oiseaux ZPS','A');
insert ignore into ref_designations values(389, 'LU08','Zones protégées d''importance communale','A');
insert ignore into ref_designations values(390, 'LU99','Autres','');
insert ignore into ref_designations values(391, 'LV00','No Protection Status','');
insert ignore into ref_designations values(392, 'LV01','Dabas rezervats','A');
insert ignore into ref_designations values(393, 'LV02','Nacionalais parks','A');
insert ignore into ref_designations values(394, 'LV03','Dabas parks','A');
insert ignore into ref_designations values(395, 'LV04','Dabas piemineklis','A');
insert ignore into ref_designations values(396, 'LV05','Dabas liegums','A');
insert ignore into ref_designations values(397, 'LV06','Aizsargajamo ainavu apvidus','A');
insert ignore into ref_designations values(398, 'LV07','Biosferas rezervats','A');
insert ignore into ref_designations values(399, 'LV08','Mikroliegums','A');
insert ignore into ref_designations values(400, 'LV09','Aizsargajama juras teritorija','A');
insert ignore into ref_designations values(401, 'LV99','Others','');
insert ignore into ref_designations values(402, 'MT00','Mhux Protett','');
insert ignore into ref_designations values(403, 'MT01','Area ta'' Importanza Ekologika','B');
insert ignore into ref_designations values(404, 'MT02','Area ta'' Importanza Ekologika/Sit ta'' Importanza Xjentifika','B');
insert ignore into ref_designations values(405, 'MT03','Santwarju ta'' l-Ghasafar','A');
insert ignore into ref_designations values(406, 'MT04','Riserva Naturali (Gzejjer)','A');
insert ignore into ref_designations values(407, 'MT05','Riserva Naturali (Filfla)','A');
insert ignore into ref_designations values(408, 'MT06','Riserva Naturali (Sigar)','A');
insert ignore into ref_designations values(409, 'MT07','Sit ta'' Importanza Xjentifika','B');
insert ignore into ref_designations values(410, 'MT08','List of Historical Trees Having an Antiquarian Importance','B');
insert ignore into ref_designations values(411, 'MT09','Zona Projbita','B');
insert ignore into ref_designations values(412, 'MT10','Zoni Specjali ta'' Konservazzjoni - Importanza Nazzjonali','A');
insert ignore into ref_designations values(413, 'MT11','Zoni Specjali ta'' Konservazzjoni - Importanza Internazzjonali','A');
insert ignore into ref_designations values(414, 'MT12','Xtajtiet Protetti','B');
insert ignore into ref_designations values(415, 'MT99','Others','');
insert ignore into ref_designations values(416, 'NL00','Geen beschermingsstatus','');
insert ignore into ref_designations values(417, 'NL01','Natuurbeschermingswet','A');
insert ignore into ref_designations values(418, 'NL21','Natuurreservaat met beheerssubsidie','C');
insert ignore into ref_designations values(419, 'NL22','Nationaal Park','C');
insert ignore into ref_designations values(420, 'NL92','Nationaal Park in Oprichting','C');
insert ignore into ref_designations values(421, 'NL99','Andere','');
insert ignore into ref_designations values(422, 'PL00','obszar nie chroniony','');
insert ignore into ref_designations values(423, 'PL01','Park Narodowy','A');
insert ignore into ref_designations values(424, 'PL02','Rezerwat Przyrody','A');
insert ignore into ref_designations values(425, 'PL03','Park Krajobrazowy','A');
insert ignore into ref_designations values(426, 'PL04','Obszar Chronionego Krajobrazu','A');
insert ignore into ref_designations values(427, 'PL05','Pomnik Przyrody','A');
insert ignore into ref_designations values(428, 'PL06','Stanowiska Dokumentacyjne','A');
insert ignore into ref_designations values(429, 'PL07','Uzytki Ekologiczne','A');
insert ignore into ref_designations values(430, 'PL09','Privat Reserve','C');
insert ignore into ref_designations values(431, 'PL10','','');
insert ignore into ref_designations values(432, 'PL11','','');
insert ignore into ref_designations values(433, 'PT00','Sem estatuto de protecção','');
insert ignore into ref_designations values(434, 'PT01','Reserva Integral','A');
insert ignore into ref_designations values(435, 'PT03','Reserva Botânica','A');
insert ignore into ref_designations values(436, 'PT06','Parque Nacional','A');
insert ignore into ref_designations values(437, 'PT07','Reserva Natural','A');
insert ignore into ref_designations values(438, 'PT08','Parque Natural','A');
insert ignore into ref_designations values(439, 'PT09','Monumento Natural','A');
insert ignore into ref_designations values(440, 'PT10','Sítio Classificado','A');
insert ignore into ref_designations values(441, 'PT11','Paisagem Protegida','A');
insert ignore into ref_designations values(442, 'PT12','Reserva de Recreio e Montanha','A');
insert ignore into ref_designations values(443, 'PT13','Reserva Geológica e de Vegetação','A');
insert ignore into ref_designations values(444, 'PT14','Zona de Repouso e Silêncio','A');
insert ignore into ref_designations values(445, 'PT15','Área Protegida para a Gestão de Habitats ou Espécies','A');
insert ignore into ref_designations values(446, 'PT16','Área Protegida de Gestão de Recursos','A');
insert ignore into ref_designations values(447, 'PT17','Microreserva','A');
insert ignore into ref_designations values(448, 'PT18','Reserva Marinha','A');
insert ignore into ref_designations values(449, 'PT19','Parque Marinho','A');
insert ignore into ref_designations values(450, 'PT21','Reserva Ecólogica Nacional','B');
insert ignore into ref_designations values(451, 'PT24','Mata Nacional','B');
insert ignore into ref_designations values(452, 'PT25','Reserva Florestal Natural Integral','B');
insert ignore into ref_designations values(453, 'PT26','Reserva Florestal Natural Parcial','B');
insert ignore into ref_designations values(454, 'PT27','Reserva Florestal de Recreio','B');
insert ignore into ref_designations values(455, 'PT29','Áreas de Refúgio de Caça','B');
insert ignore into ref_designations values(456, 'PT41','Sitio de Interesse Biológico','C');
insert ignore into ref_designations values(457, 'PT42','Área Protegida Privada','C');
insert ignore into ref_designations values(458, 'PT44','Reserva Natural Integral','A');
insert ignore into ref_designations values(459, 'PT45','Reserva Parcial','A');
insert ignore into ref_designations values(460, 'PT46','Paisagem Protegida','A');
insert ignore into ref_designations values(461, 'PT57','Paisagem Protegida Regional','A');
insert ignore into ref_designations values(462, 'PT58','Monumento Natural Regional','A');
insert ignore into ref_designations values(463, 'PT59','Parque Natural Regional','A');
insert ignore into ref_designations values(464, 'PT60','Reserva Natural Regional','A');
insert ignore into ref_designations values(465, 'PT61','Paisagem Protegida Local','A');
insert ignore into ref_designations values(466, 'PT62','Monumento Natural Local','A');
insert ignore into ref_designations values(467, 'PT63','Parque Natural Local','A');
insert ignore into ref_designations values(468, 'PT64','Reserva Natural Local','A');
insert ignore into ref_designations values(469, 'RO00','Zona fara regim de protectie','');
insert ignore into ref_designations values(470, 'RO01','Rezervatie stiintifica','A');
insert ignore into ref_designations values(471, 'RO02','Parc national','A');
insert ignore into ref_designations values(472, 'RO03','Monument al naturii','A');
insert ignore into ref_designations values(473, 'RO04','Rezervatie naturala','A');
insert ignore into ref_designations values(474, 'RO05','Parc natural','A');
insert ignore into ref_designations values(475, 'RO06','Zone de Conservare Speciala','A');
insert ignore into ref_designations values(476, 'RO07','Arie de Protectie Speciala Avifaunistica','A');
insert ignore into ref_designations values(477, 'RO08','Rezervatie a Biosferei','A');
insert ignore into ref_designations values(478, 'RO11','Padure cu functii speciale de protectie a apelor','B');
insert ignore into ref_designations values(479, 'RO12','Padure cu functii speciale de protectie a solului','B');
insert ignore into ref_designations values(480, 'RO13','Padure cu functii speciale de protectie contra factorilor climatici si industriali daunatori','B');
insert ignore into ref_designations values(481, 'RO14','Padure pentru recreere','B');
insert ignore into ref_designations values(482, 'RO15','Padure de interes stiintific si de ocrotire a genofondului si ecofondului forestier','B');
insert ignore into ref_designations values(483, 'RO21','Rezervatie de genofond','B');
insert ignore into ref_designations values(484, 'RO31','Regiune de crutare piscicola','B');
insert ignore into ref_designations values(485, 'RO32','Zona de protectie piscicola','B');
insert ignore into ref_designations values(486, 'RO41','Zona de protectie sanitara a surselor de apa potabila si minerala','B');
insert ignore into ref_designations values(487, 'RO42','Perimetru de protectie hidrogeologica','B');
insert ignore into ref_designations values(488, 'RO99','Other','');
insert ignore into ref_designations values(489, 'SE00','Inget skydd','');
insert ignore into ref_designations values(490, 'SE01','Nationalpark','A');
insert ignore into ref_designations values(491, 'SE02','Naturreservat','A');
insert ignore into ref_designations values(492, 'SE03','Naturvårdsområde','A');
insert ignore into ref_designations values(493, 'SE04','Biotopskyddsområde','A');
insert ignore into ref_designations values(494, 'SE05','Samrådsområde','A');
insert ignore into ref_designations values(495, 'SE06','Djur- och växtskyddsområde','A');
insert ignore into ref_designations values(496, 'SE98','Naturminne','A');
insert ignore into ref_designations values(497, 'SE99','Övriga','A');
insert ignore into ref_designations values(498, 'SI00','nezavarovano','');
insert ignore into ref_designations values(499, 'SI01','strogi naravni rezervat','A');
insert ignore into ref_designations values(500, 'SI02','naravni rezervat','A');
insert ignore into ref_designations values(501, 'SI03','naravni spomenik','A');
insert ignore into ref_designations values(502, 'SI04','narodni park','A');
insert ignore into ref_designations values(503, 'SI05','regijski park','A');
insert ignore into ref_designations values(504, 'SI06','krajinski park','A');
insert ignore into ref_designations values(505, 'SI07','ekološko pomembno območje','A');
insert ignore into ref_designations values(506, 'SI08','posebno varstveno območje','A');
insert ignore into ref_designations values(507, 'SI14','spomenik oblikovane narave','A');
insert ignore into ref_designations values(508, 'SK00','Bez ochrany; prvý stupen ochrany','A');
insert ignore into ref_designations values(509, 'SK01','Národná prírodná rezervácia; piaty stupen ochrany','A');
insert ignore into ref_designations values(510, 'SK02','Prírodná rezervácia / súkromná prírodná rezervácia; piaty stupen ochrany','A');
insert ignore into ref_designations values(511, 'SK03','Národná prírodná pamiatka; piaty stupen ochrany','A');
insert ignore into ref_designations values(512, 'SK04','Prírodná pamiatka / súkromná prírodná pamiatka; piaty stupen ochrany','A');
insert ignore into ref_designations values(513, 'SK05','Chránený areál / súkromný chránený areál; štvrtý stupen ochrany','A');
insert ignore into ref_designations values(514, 'SK06','Ochranné pásmo NPR, PR, NPP a PP','A');
insert ignore into ref_designations values(515, 'SK07','Ochranné pásmo chráneného areálu; tretí stupen ochrany','A');
insert ignore into ref_designations values(516, 'SK08','Národný park; tretí stupen ochrany','A');
insert ignore into ref_designations values(517, 'SK09','Ochranné pásmo národného parku; druhý stupen ochrany','A');
insert ignore into ref_designations values(518, 'SK10','Chránená krajinná oblast; druhý stupen ochrany','A');
insert ignore into ref_designations values(519, 'SK11','Biocentrum','A');
insert ignore into ref_designations values(520, 'SK12','Biokoridor','A');
insert ignore into ref_designations values(521, 'SK99','Others','A');
insert ignore into ref_designations values(522, 'UK00','No Protection Status','');
insert ignore into ref_designations values(523, 'UK01','National Nature Reserve','A');
insert ignore into ref_designations values(524, 'UK02','Marine Nature Reserve','A');
insert ignore into ref_designations values(525, 'UK04','Site of Special Scientific Interest (UK)','A');
insert ignore into ref_designations values(526, 'UK21','Land owned by a non-governmental organisation for nature conservation','C');
insert ignore into ref_designations values(527, 'UK83','Area of Outstanding Natural Beauty (NI)','A');
insert ignore into ref_designations values(528, 'UK84','Marine Consultation Area','A');
insert ignore into ref_designations values(529, 'UK85','Area of Outstanding Natural Beauty','A');
insert ignore into ref_designations values(530, 'UK86','Special Area (Channel Islands)','A');
insert ignore into ref_designations values(531, 'UK87','Voluntary Reserve','C');
insert ignore into ref_designations values(532, 'UK88','Regional Park','A');
insert ignore into ref_designations values(533, 'UK91','National Scenic Area','A');
insert ignore into ref_designations values(534, 'UK92','Heritage Coast','A');
insert ignore into ref_designations values(535, 'UK93','Forest Park','A');
insert ignore into ref_designations values(536, 'UK96','Local Nature Reserve','A');
insert ignore into ref_designations values(537, 'UK97','National Park','A');
insert ignore into ref_designations values(538, 'UK98','Area of Special Scientific Interest (NI)','A');
insert ignore into ref_designations values(539, 'IN00','Ramsar Convention Site','');
insert ignore into ref_designations values(540, 'IN01','Biogenetic Reserve (Council of Europe)','');
insert ignore into ref_designations values(541, 'IN02','European Diploma Site (Since 2000)','');
insert ignore into ref_designations values(542, 'IN03','Biosphere Reserve (UNESCO)','');
insert ignore into ref_designations values(543, 'IN04','Meditarranean Specially Protected Area (Barcelona Convention)','');
insert ignore into ref_designations values(544, 'IN05','World Heritage Site (UNESCO)','');
insert ignore into ref_designations values(545, 'IN06','Other International Designation','');
insert ignore into ref_designations values(546, 'IN07','Baltic Sea Protected Area (BSPA)','');
insert ignore into ref_designations values(547, 'IN08','Special Protected Area (SPA, EC Birds Directive)','');
insert ignore into ref_designations values(548, 'IN09','Special Area of Conservation (SAC, EC Habitats Directive)','');
insert ignore into ref_designations values(549, 'IN10','Area of Special Conservation Interest (ASCI, Bern Convention, Emerald)','');
insert ignore into ref_designations values(550, 'IN11','Specially Protected Area of Mediterranean Importance (SPAMI, Barcelona Convention)','');
insert ignore into ref_designations values(551, 'IN12','Special Area of Conservation and Special Protected Area (EC Birds and Habitats Directives)','');
insert ignore into ref_designations values(552, 'INE0','Declassified European Diploma Site','');
insert ignore into ref_designations values(553, 'INEA','European Diploma Site (Category A)','');
insert ignore into ref_designations values(554, 'INEB','European Diploma Site (Category B)','');
insert ignore into ref_designations values(555, 'INEC','European Diploma Site (Category C)','');
insert ignore into ref_designations values(556, 'INF0','Declassified Biosphere Reserve','');
insert ignore into ref_designations values(557, 'INR0','Declassified Ramsar Convention Site','');
insert ignore into ref_designations values(558, 'INS0','Proposed Baltic Sea Protected Area (BSPA)','');
commit;
