insert ignore into natura2000.ref_habitats values(1,'1110',0,'Sandbanks which are slightly covered by sea water all the time','','','','','','','');
insert ignore into natura2000.ref_habitats values(2,'1120',1,'Posidonia beds (Posidonion oceanicae)','','','','','','','');
insert ignore into natura2000.ref_habitats values(3,'1130',0,'Estuaries','','','','','','','');
insert ignore into natura2000.ref_habitats values(4,'1140',0,'Mudflats and sandflats not covered by seawater at low tide','','','','','','','');
insert ignore into natura2000.ref_habitats values(5,'1150',1,'Coastal lagoons','','','','','','','');
insert ignore into natura2000.ref_habitats values(6,'1160',0,'Large shallow inlets and bays','','','','','','','');
insert ignore into natura2000.ref_habitats values(7,'1170',0,'Reefs','','','','','','','');
insert ignore into natura2000.ref_habitats values(8,'1180',0,'Submarine structures made by leaking gases','','','','','','','');
insert ignore into natura2000.ref_habitats values(9,'1210',0,'Annual vegetation of drift lines','','','','','','','');
insert ignore into natura2000.ref_habitats values(10,'1220',0,'Perennial vegetation of stony banks','','','','','','','');
insert ignore into natura2000.ref_habitats values(11,'1230',0,'Vegetated sea cliffs of the Atlantic and Baltic Coasts','','','','','','','');
insert ignore into natura2000.ref_habitats values(12,'1240',0,'Vegetated sea cliffs of the Mediterranean coasts with endemic Limonium spp.','','','','','','','');
insert ignore into natura2000.ref_habitats values(13,'1250',0,'Vegetated sea cliffs with endemic flora of the Macaronesian coasts','','','','','','','');
insert ignore into natura2000.ref_habitats values(14,'1310',0,'Salicornia and other annuals colonizing mud and sand','','','','','','','');
insert ignore into natura2000.ref_habitats values(15,'1320',0,'Spartina swards (Spartinion maritimae)','','','','','','','');
insert ignore into natura2000.ref_habitats values(16,'1330',0,'Atlantic salt meadows (Glauco-Puccinellietalia maritimae)','','','','','','','');
insert ignore into natura2000.ref_habitats values(17,'1340',1,'Inland salt meadows','','','','','','','');
insert ignore into natura2000.ref_habitats values(18,'1410',0,'Mediterranean salt meadows (Juncetalia maritimi)','','','','','','','');
insert ignore into natura2000.ref_habitats values(19,'1420',0,'Mediterranean and thermo-Atlantic halophilous scrubs (Sarcocornetea fruticosi)','','','','','','','');
insert ignore into natura2000.ref_habitats values(20,'1430',0,'Halo-nitrophilous scrubs (Pegano-Salsoletea)','','','','','','','');
insert ignore into natura2000.ref_habitats values(21,'1510',1,'Mediterranean salt steppes (Limonietalia)','','','','','','','');
insert ignore into natura2000.ref_habitats values(22,'1520',1,'Iberian gypsum vegetation (Gypsophiletalia)','','','','','','','');
insert ignore into natura2000.ref_habitats values(23,'1530',1,'Pannonic salt steppes and salt marshes','','','','','','','');
insert ignore into natura2000.ref_habitats values(24,'1610',0,'Baltic esker islands with sandy, rocky and shingle beach vegetation and sublittoral vegetation','','','','','','','');
insert ignore into natura2000.ref_habitats values(25,'1620',0,'Boreal Baltic islets and small islands','','','','','','','');
insert ignore into natura2000.ref_habitats values(26,'1630',1,'Boreal Baltic coastal meadows','','','','','','','');
insert ignore into natura2000.ref_habitats values(27,'1640',0,'Boreal Baltic sandy beaches with perennial vegetation','','','','','','','');
insert ignore into natura2000.ref_habitats values(28,'1650',0,'Boreal Baltic narrow inlets','','','','','','','');
insert ignore into natura2000.ref_habitats values(29,'2110',0,'Embryonic shifting dunes','','','','','','','');
insert ignore into natura2000.ref_habitats values(30,'2120',0,'"Shifting dunes along the shoreline with Ammophila arenaria (""white dunes"")"','','','','','','','');
insert ignore into natura2000.ref_habitats values(31,'2130',1,'"Fixed coastal dunes with herbaceous vegetation (""grey dunes"")"','','','','','','','');
insert ignore into natura2000.ref_habitats values(32,'2140',1,'Decalcified fixed dunes with Empetrum nigrum','','','','','','','');
insert ignore into natura2000.ref_habitats values(33,'2150',1,'Atlantic decalcified fixed dunes (Calluno-Ulicetea)','','','','','','','');
insert ignore into natura2000.ref_habitats values(34,'2160',0,'Dunes with Hippopha� rhamnoides','','','','','','','');
insert ignore into natura2000.ref_habitats values(35,'2170',0,'Dunes with Salix repens ssp. argentea (Salicion arenariae)','','','','','','','');
insert ignore into natura2000.ref_habitats values(36,'2180',0,'Wooded dunes of the Atlantic, Continental and Boreal region','','','','','','','');
insert ignore into natura2000.ref_habitats values(37,'2190',0,'Humid dune slacks','','','','','','','');
insert ignore into natura2000.ref_habitats values(38,'21A0',0,'Machairs (* in Ireland)','','','','','','','');
insert ignore into natura2000.ref_habitats values(39,'2210',0,'Crucianellion maritimae fixed beach dunes','','','','','','','');
insert ignore into natura2000.ref_habitats values(40,'2220',0,'Dunes with Euphorbia terracina','','','','','','','');
insert ignore into natura2000.ref_habitats values(41,'2230',0,'Malcolmietalia dune grasslands','','','','','','','');
insert ignore into natura2000.ref_habitats values(42,'2240',0,'Brachypodietalia dune grasslands with annuals','','','','','','','');
insert ignore into natura2000.ref_habitats values(43,'2250',1,'Coastal dunes with Juniperus spp.','','','','','','','');
insert ignore into natura2000.ref_habitats values(44,'2260',0,'Cisto-Lavenduletalia dune sclerophyllous scrubs','','','','','','','');
insert ignore into natura2000.ref_habitats values(45,'2270',1,'Wooded dunes with Pinus pinea and/or Pinus pinaster','','','','','','','');
insert ignore into natura2000.ref_habitats values(46,'2310',0,'Dry sand heaths with Calluna and Genista','','','','','','','');
insert ignore into natura2000.ref_habitats values(47,'2320',0,'Dry sand heaths with Calluna and Empetrum nigrum','','','','','','','');
insert ignore into natura2000.ref_habitats values(48,'2330',0,'Inland dunes with open Corynephorus and Agrostis grasslands','','','','','','','');
insert ignore into natura2000.ref_habitats values(49,'2340',1,'Pannonic inland dunes','','','','','','','');
insert ignore into natura2000.ref_habitats values(50,'3110',0,'Oligotrophic waters containing very few minerals of sandy plains (Littorelletalia uniflorae)','','','','','','','');
insert ignore into natura2000.ref_habitats values(51,'3120',0,'Oligotrophic waters containing very few minerals generally on sandy soils of the West Mediterranean, with Isoetes spp.','','','','','','','');
insert ignore into natura2000.ref_habitats values(52,'3130',0,'Oligotrophic to mesotrophic standing waters with vegetation of the Littorelletea uniflorae and/or of the Isoëto-Nanojuncetea','','','','','','','');
insert ignore into natura2000.ref_habitats values(53,'3140',0,'Hard oligo-mesotrophic waters with benthic vegetation of Chara spp.','','','','','','','');
insert ignore into natura2000.ref_habitats values(54,'3150',0,'Natural eutrophic lakes with Magnopotamion or Hydrocharition - type vegetation','','','','','','','');
insert ignore into natura2000.ref_habitats values(55,'3160',0,'Natural dystrophic lakes and ponds','','','','','','','');
insert ignore into natura2000.ref_habitats values(56,'3170',1,'Mediterranean temporary ponds','','','','','','','');
insert ignore into natura2000.ref_habitats values(57,'3180',1,'Turloughs','','','','','','','');
insert ignore into natura2000.ref_habitats values(58,'3190',0,'Lakes of gypsum karst','','','','','','','');
insert ignore into natura2000.ref_habitats values(59,'31A0',1,'Transylvanian hot-spring lotus beds','','','','','','','');
insert ignore into natura2000.ref_habitats values(60,'3210',0,'Fennoscandian natural rivers','','','','','','','');
insert ignore into natura2000.ref_habitats values(61,'3220',0,'Alpine rivers and the herbaceous vegetation along their banks','','','','','','','');
insert ignore into natura2000.ref_habitats values(62,'3230',0,'Alpine rivers and their ligneous vegetation with Myricaria germanica','','','','','','','');
insert ignore into natura2000.ref_habitats values(63,'3240',0,'Alpine rivers and their ligneous vegetation with Salix elaeagnos','','','','','','','');
insert ignore into natura2000.ref_habitats values(64,'3250',0,'Constantly flowing Mediterranean rivers with Glaucium flavum','','','','','','','');
insert ignore into natura2000.ref_habitats values(65,'3260',0,'Water courses of plain to montane levels with the Ranunculion fluitantis and Callitricho-Batrachion vegetation','','','','','','','');
insert ignore into natura2000.ref_habitats values(66,'3270',0,'Rivers with muddy banks with Chenopodion rubri p.p. and Bidention p.p. vegetation','','','','','','','');
insert ignore into natura2000.ref_habitats values(67,'3280',0,'Constantly flowing Mediterranean rivers with Paspalo-Agrostidion species and hanging curtains of Salix and Populus alba','','','','','','','');
insert ignore into natura2000.ref_habitats values(68,'3290',0,'Intermittently flowing Mediterranean rivers of the Paspalo-Agrostidion','','','','','','','');
insert ignore into natura2000.ref_habitats values(69,'4010',0,'Northern Atlantic wet heaths with Erica tetralix','','','','','','','');
insert ignore into natura2000.ref_habitats values(70,'4020',1,'Temperate Atlantic wet heaths with Erica ciliaris and Erica tetralix','','','','','','','');
insert ignore into natura2000.ref_habitats values(71,'4030',0,'European dry heaths','','','','','','','');
insert ignore into natura2000.ref_habitats values(72,'4040',1,'Dry Atlantic coastal heaths with Erica vagans','','','','','','','');
insert ignore into natura2000.ref_habitats values(73,'4050',1,'Endemic macaronesian heaths','','','','','','','');
insert ignore into natura2000.ref_habitats values(74,'4060',0,'Alpine and Boreal heaths','','','','','','','');
insert ignore into natura2000.ref_habitats values(75,'4070',1,'Bushes with Pinus mugo and Rhododendron hirsutum (Mugo-Rhododendretum hirsuti)','','','','','','','');
insert ignore into natura2000.ref_habitats values(76,'4080',0,'Sub-Arctic Salix spp. scrub','','','','','','','');
insert ignore into natura2000.ref_habitats values(77,'4090',0,'Endemic oro-Mediterranean heaths with gorse','','','','','','','');
insert ignore into natura2000.ref_habitats values(78,'40A0',1,'Subcontinental peri-Pannonic scrub','','','','','','','');
insert ignore into natura2000.ref_habitats values(79,'40B0',0,'Rhodope Potentilla fruticosa thickets','','','','','','','');
insert ignore into natura2000.ref_habitats values(80,'40C0',1,'Ponto-Sarmatic deciduous thickets','','','','','','','');
insert ignore into natura2000.ref_habitats values(81,'5110',0,'Stable xerothermophilous formations with Buxus sempervirens on rock slopes (Berberidion p.p.)','','','','','','','');
insert ignore into natura2000.ref_habitats values(82,'5120',0,'Mountain Cytisus purgans formations','','','','','','','');
insert ignore into natura2000.ref_habitats values(83,'5130',0,'Juniperus communis formations on heaths or calcareous grasslands','','','','','','','');
insert ignore into natura2000.ref_habitats values(84,'5140',1,'Cistus palhinhae formations on maritime wet heaths','','','','','','','');
insert ignore into natura2000.ref_habitats values(85,'5210',0,'Arborescent matorral with Juniperus spp.','','','','','','','');
insert ignore into natura2000.ref_habitats values(86,'5220',1,'Arborescent matorral with Zyziphus','','','','','','','');
insert ignore into natura2000.ref_habitats values(87,'5230',1,'Arborescent matorral with Laurus nobilis','','','','','','','');
insert ignore into natura2000.ref_habitats values(88,'5310',0,'Laurus nobilis thickets','','','','','','','');
insert ignore into natura2000.ref_habitats values(89,'5320',0,'Low formations of Euphorbia close to cliffs','','','','','','','');
insert ignore into natura2000.ref_habitats values(90,'5330',0,'Thermo-Mediterranean and pre-desert scrub','','','','','','','');
insert ignore into natura2000.ref_habitats values(91,'5410',0,'West Mediterranean clifftop phryganas (Astragalo-Plantaginetum subulatae)','','','','','','','');
insert ignore into natura2000.ref_habitats values(92,'5420',0,'Sarcopoterium spinosum phryganas','','','','','','','');
insert ignore into natura2000.ref_habitats values(93,'5430',0,'Endemic phryganas of the Euphorbio-Verbascion','','','','','','','');
insert ignore into natura2000.ref_habitats values(94,'6110',1,'Rupicolous calcareous or basophilic grasslands of the Alysso-Sedion albi','','','','','','','');
insert ignore into natura2000.ref_habitats values(95,'6120',1,'Xeric sand calcareous grasslands','','','','','','','');
insert ignore into natura2000.ref_habitats values(96,'6130',0,'Calaminarian grasslands of the Violetalia calaminariae','','','','','','','');
insert ignore into natura2000.ref_habitats values(97,'6140',0,'Siliceous Pyrenean Festuca eskia grasslands','','','','','','','');
insert ignore into natura2000.ref_habitats values(98,'6150',0,'Siliceous alpine and boreal grasslands','','','','','','','');
insert ignore into natura2000.ref_habitats values(99,'6160',0,'Oro-Iberian Festuca indigesta grasslands','','','','','','','');
insert ignore into natura2000.ref_habitats values(100,'6170',0,'Alpine and subalpine calcareous grasslands','','','','','','','');
insert ignore into natura2000.ref_habitats values(101,'6180',0,'Macaronesian mesophile grasslands','','','','','','','');
insert ignore into natura2000.ref_habitats values(102,'6190',0,'Rupicolous pannonic grasslands (Stipo-Festucetalia pallentis)','','','','','','','');
insert ignore into natura2000.ref_habitats values(103,'6210',0,'Semi-natural dry grasslands and scrubland facies on calcareous substrates (Festuco-Brometalia) (* important orchid sites)','','','','','','','');
insert ignore into natura2000.ref_habitats values(104,'6220',1,'Pseudo-steppe with grasses and annuals of the Thero-Brachypodietea','','','','','','','');
insert ignore into natura2000.ref_habitats values(105,'6230',1,'Species-rich Nardus grasslands, on silicious substrates in mountain areas (and submountain areas in Continental Europe)','','','','','','','');
insert ignore into natura2000.ref_habitats values(106,'6240',1,'Sub-Pannonic steppic grasslands','','','','','','','');
insert ignore into natura2000.ref_habitats values(107,'6250',1,'Pannonic loess steppic grasslands','','','','','','','');
insert ignore into natura2000.ref_habitats values(108,'6260',1,'Pannonic sand steppes','','','','','','','');
insert ignore into natura2000.ref_habitats values(109,'6270',1,'Fennoscandian lowland species-rich dry to mesic grasslands','','','','','','','');
insert ignore into natura2000.ref_habitats values(110,'6280',1,'Nordic alvar and precambrian calcareous flatrocks','','','','','','','');
insert ignore into natura2000.ref_habitats values(111,'62A0',0,'Eastern sub-Mediterranean dry grasslands (Scorzoneratalia villosae)','','','','','','','');
insert ignore into natura2000.ref_habitats values(112,'62B0',1,'Serpentinophilous grassland of Cyprus','','','','','','','');
insert ignore into natura2000.ref_habitats values(113,'62C0',1,'Ponto-Sarmatic steppes','','','','','','','');
insert ignore into natura2000.ref_habitats values(114,'62D0',0,'Oro-Moesian acidophilous grasslands','','','','','','','');
insert ignore into natura2000.ref_habitats values(115,'6310',0,'Dehesas with evergreen Quercus spp.','','','','','','','');
insert ignore into natura2000.ref_habitats values(116,'6410',0,'Molinia meadows on calcareous, peaty or clayey-silt-laden soils (Molinion caeruleae)','','','','','','','');
insert ignore into natura2000.ref_habitats values(117,'6420',0,'Mediterranean tall humid grasslands of the Molinio-Holoschoenion','','','','','','','');
insert ignore into natura2000.ref_habitats values(118,'6430',0,'Hydrophilous tall herb fringe communities of plains and of the montane to alpine levels','','','','','','','');
insert ignore into natura2000.ref_habitats values(119,'6440',0,'Alluvial meadows of river valleys of the Cnidion dubii','','','','','','','');
insert ignore into natura2000.ref_habitats values(120,'6450',0,'Northern boreal alluvial meadows','','','','','','','');
insert ignore into natura2000.ref_habitats values(121,'6460',0,'Peat grasslands of Troodos','','','','','','','');
insert ignore into natura2000.ref_habitats values(122,'6510',0,'Lowland hay meadows (Alopecurus pratensis, Sanguisorba officinalis)','','','','','','','');
insert ignore into natura2000.ref_habitats values(123,'6520',0,'Mountain hay meadows','','','','','','','');
insert ignore into natura2000.ref_habitats values(124,'6530',1,'Fennoscandian wooded meadows','','','','','','','');
insert ignore into natura2000.ref_habitats values(125,'7110',1,'Active raised bogs','','','','','','','');
insert ignore into natura2000.ref_habitats values(126,'7120',0,'Degraded raised bogs still capable of natural regeneration','','','','','','','');
insert ignore into natura2000.ref_habitats values(127,'7130',0,'Blanket bogs (* if active bog)','','','','','','','');
insert ignore into natura2000.ref_habitats values(128,'7140',0,'Transition mires and quaking bogs','','','','','','','');
insert ignore into natura2000.ref_habitats values(129,'7150',0,'Depressions on peat substrates of the Rhynchosporion','','','','','','','');
insert ignore into natura2000.ref_habitats values(130,'7160',0,'Fennoscandian mineral-rich springs and springfens','','','','','','','');
insert ignore into natura2000.ref_habitats values(131,'7210',1,'Calcareous fens with Cladium mariscus and species of the Caricion davallianae','','','','','','','');
insert ignore into natura2000.ref_habitats values(132,'7220',1,'Petrifying springs with tufa formation (Cratoneurion)','','','','','','','');
insert ignore into natura2000.ref_habitats values(133,'7230',0,'Alkaline fens','','','','','','','');
insert ignore into natura2000.ref_habitats values(134,'7240',1,'Alpine pioneer formations of the Caricion bicoloris-atrofuscae','','','','','','','');
insert ignore into natura2000.ref_habitats values(135,'7310',1,'Aapa mires','','','','','','','');
insert ignore into natura2000.ref_habitats values(136,'7320',1,'Palsa mires','','','','','','','');
insert ignore into natura2000.ref_habitats values(137,'8110',0,'Siliceous scree of the montane to snow levels (Androsacetalia alpinae and Galeopsietalia ladani)','','','','','','','');
insert ignore into natura2000.ref_habitats values(138,'8120',0,'Calcareous and calcshist screes of the montane to alpine levels (Thlaspietea rotundifolii)','','','','','','','');
insert ignore into natura2000.ref_habitats values(139,'8130',0,'Western Mediterranean and thermophilous scree','','','','','','','');
insert ignore into natura2000.ref_habitats values(140,'8140',0,'Eastern Mediterranean screes','','','','','','','');
insert ignore into natura2000.ref_habitats values(141,'8150',0,'Medio-European upland siliceous screes','','','','','','','');
insert ignore into natura2000.ref_habitats values(142,'8160',1,'Medio-European calcareous scree of hill and montane levels','','','','','','','');
insert ignore into natura2000.ref_habitats values(143,'8210',0,'Calcareous rocky slopes with chasmophytic vegetation','','','','','','','');
insert ignore into natura2000.ref_habitats values(144,'8220',0,'Siliceous rocky slopes with chasmophytic vegetation','','','','','','','');
insert ignore into natura2000.ref_habitats values(145,'8230',0,'Siliceous rock with pioneer vegetation of the Sedo-Scleranthion or of the Sedo albi-Veronicion dillenii','','','','','','','');
insert ignore into natura2000.ref_habitats values(146,'8240',1,'Limestone pavements','','','','','','','');
insert ignore into natura2000.ref_habitats values(147,'8310',0,'Caves not open to the public','','','','','','','');
insert ignore into natura2000.ref_habitats values(148,'8320',0,'Fields of lava and natural excavations','','','','','','','');
insert ignore into natura2000.ref_habitats values(149,'8330',0,'Submerged or partially submerged sea caves','','','','','','','');
insert ignore into natura2000.ref_habitats values(150,'8340',0,'Permanent glaciers','','','','','','','');
insert ignore into natura2000.ref_habitats values(151,'9010',1,'Western Taïga','','','','','','','');
insert ignore into natura2000.ref_habitats values(152,'9020',1,'Fennoscandian hemiboreal natural old broad-leaved deciduous forests (Quercus, Tilia, Acer, Fraxinus or Ulmus) rich in epiphytes','','','','','','','');
insert ignore into natura2000.ref_habitats values(153,'9030',1,'Natural forests of primary succession stages of landupheaval coast','','','','','','','');
insert ignore into natura2000.ref_habitats values(154,'9040',0,'Nordic subalpine/subarctic forests with Betula pubescens ssp. czerepanovii','','','','','','','');
insert ignore into natura2000.ref_habitats values(155,'9050',0,'Fennoscandian herb-rich forests with Picea abies','','','','','','','');
insert ignore into natura2000.ref_habitats values(156,'9060',0,'Coniferous forests on, or connected to, glaciofluvial eskers','','','','','','','');
insert ignore into natura2000.ref_habitats values(157,'9070',0,'Fennoscandian wooded pastures','','','','','','','');
insert ignore into natura2000.ref_habitats values(158,'9080',1,'Fennoscandian deciduous swamp woods','','','','','','','');
insert ignore into natura2000.ref_habitats values(159,'9110',0,'Luzulo-Fagetum beech forests','','','','','','','');
insert ignore into natura2000.ref_habitats values(160,'9120',0,'Atlantic acidophilous beech forests with Ilex and sometimes also Taxus in the shrublayer (Quercion robori-petraeae or Ilici-Fagenion)','','','','','','','');
insert ignore into natura2000.ref_habitats values(161,'9130',0,'Asperulo-Fagetum beech forests','','','','','','','');
insert ignore into natura2000.ref_habitats values(162,'9140',0,'Medio-European subalpine beech woods with Acer and Rumex arifolius','','','','','','','');
insert ignore into natura2000.ref_habitats values(163,'9150',0,'Medio-European limestone beech forests of the Cephalanthero-Fagion','','','','','','','');
insert ignore into natura2000.ref_habitats values(164,'9160',0,'Sub-Atlantic and medio-European oak or oak-hornbeam forests of the Carpinion betuli','','','','','','','');
insert ignore into natura2000.ref_habitats values(165,'9170',0,'Galio-Carpinetum oak-hornbeam forests','','','','','','','');
insert ignore into natura2000.ref_habitats values(166,'9180',1,'Tilio-Acerion forests of slopes, screes and ravines','','','','','','','');
insert ignore into natura2000.ref_habitats values(167,'9190',0,'Old acidophilous oak woods with Quercus robur on sandy plains','','','','','','','');
insert ignore into natura2000.ref_habitats values(168,'91A0',0,'Old sessile oak woods with Ilex and Blechnum in the British Isles','','','','','','','');
insert ignore into natura2000.ref_habitats values(169,'91AA',1,'Eastern white oak woods','','','','','','','');
insert ignore into natura2000.ref_habitats values(170,'91B0',0,'Thermophilous Fraxinus angustifolia woods','','','','','','','');
insert ignore into natura2000.ref_habitats values(171,'91BA',0,'Moesian silver fir forests','','','','','','','');
insert ignore into natura2000.ref_habitats values(172,'91C0',1,'Caledonian forest','','','','','','','');
insert ignore into natura2000.ref_habitats values(173,'91CA',0,'Rhodopide and Balkan Range Scots pine forests','','','','','','','');
insert ignore into natura2000.ref_habitats values(174,'91D0',1,'Bog woodland','','','','','','','');
insert ignore into natura2000.ref_habitats values(175,'91E0',1,'Alluvial forests with Alnus glutinosa and Fraxinus excelsior (Alno-Padion, Alnion incanae, Salicion albae)','','','','','','','');
insert ignore into natura2000.ref_habitats values(176,'91F0',0,'Riparian mixed forests of Quercus robur, Ulmus laevis and Ulmus minor, Fraxinus excelsior or Fraxinus angustifolia, along the great rivers (Ulmenion minoris)','','','','','','','');
insert ignore into natura2000.ref_habitats values(177,'91G0',1,'Pannonic woods with Quercus petraea and Carpinus betulus','','','','','','','');
insert ignore into natura2000.ref_habitats values(178,'91H0',1,'Pannonian woods with Quercus pubescens','','','','','','','');
insert ignore into natura2000.ref_habitats values(179,'91I0',1,'Euro-Siberian steppic woods with Quercus spp.','','','','','','','');
insert ignore into natura2000.ref_habitats values(180,'91J0',1,'Taxus baccata woods of the British Isles','','','','','','','');
insert ignore into natura2000.ref_habitats values(181,'91K0',0,'Illyrian Fagus sylvatica forests (Aremonio-Fagion)','','','','','','','');
insert ignore into natura2000.ref_habitats values(182,'91L0',0,'Illyrian oak-hornbeam forests (Erythronio-Carpinion)','','','','','','','');
insert ignore into natura2000.ref_habitats values(183,'91M0',0,'Pannonian-Balkanic turkey oak �sessile oak forests','','','','','','','');
insert ignore into natura2000.ref_habitats values(184,'91N0',1,'Pannonic inland sand dune thicket (Junipero-Populetum albae)','','','','','','','');
insert ignore into natura2000.ref_habitats values(185,'91P0',0,'Holy Cross fir forest (Abietetum polonicum)','','','','','','','');
insert ignore into natura2000.ref_habitats values(186,'91Q0',0,'Western Carpathian calcicolous Pinus sylvestris forests','','','','','','','');
insert ignore into natura2000.ref_habitats values(187,'91R0',0,'Dinaric dolomite Scots pine forests (Genisto januensis-Pinetum)','','','','','','','');
insert ignore into natura2000.ref_habitats values(188,'91S0',1,'Western Pontic beech forests','','','','','','','');
insert ignore into natura2000.ref_habitats values(189,'91T0',0,'Central European lichen Scots pine forests','','','','','','','');
insert ignore into natura2000.ref_habitats values(190,'91U0',0,'Sarmatic steppe pine forest','','','','','','','');
insert ignore into natura2000.ref_habitats values(191,'91V0',0,'Dacian Beech forests (Symphyto-Fagion)','','','','','','','');
insert ignore into natura2000.ref_habitats values(192,'91W0',0,'Moesian beech forests','','','','','','','');
insert ignore into natura2000.ref_habitats values(193,'91X0',1,'Dobrogean beech forests','','','','','','','');
insert ignore into natura2000.ref_habitats values(194,'91Y0',0,'Dacian oak & hornbeam forests','','','','','','','');
insert ignore into natura2000.ref_habitats values(195,'91Z0',0,'Moesian silver lime woods','','','','','','','');
insert ignore into natura2000.ref_habitats values(196,'9210',1,'Apeninne beech forests with Taxus and Ilex','','','','','','','');
insert ignore into natura2000.ref_habitats values(197,'9220',1,'Apennine beech forests with Abies alba and beech forests with Abies nebrodensis','','','','','','','');
insert ignore into natura2000.ref_habitats values(198,'9230',0,'Galicio-Portuguese oak woods with Quercus robur and Quercus pyrenaica','','','','','','','');
insert ignore into natura2000.ref_habitats values(199,'9240',0,'Quercus faginea and Quercus canariensis Iberian woods','','','','','','','');
insert ignore into natura2000.ref_habitats values(200,'9250',0,'Quercus trojana woods','','','','','','','');
insert ignore into natura2000.ref_habitats values(201,'9260',0,'Castanea sativa woods','','','','','','','');
insert ignore into natura2000.ref_habitats values(202,'9270',0,'Hellenic beech forests with Abies borisii-regis','','','','','','','');
insert ignore into natura2000.ref_habitats values(203,'9280',0,'Quercus frainetto woods','','','','','','','');
insert ignore into natura2000.ref_habitats values(204,'9290',0,'Cupressus forests (Acero-Cupression)','','','','','','','');
insert ignore into natura2000.ref_habitats values(205,'92A0',0,'Salix alba and Populus alba galleries','','','','','','','');
insert ignore into natura2000.ref_habitats values(206,'92B0',0,'Riparian formations on intermittent Mediterranean water courses with Rhododendron ponticum, Salix and others','','','','','','','');
insert ignore into natura2000.ref_habitats values(207,'92C0',0,'Platanus orientalis and Liquidambar orientalis woods (Platanion orientalis)','','','','','','','');
insert ignore into natura2000.ref_habitats values(208,'92D0',0,'Southern riparian galleries and thickets (Nerio-Tamaricetea and Securinegion tinctoriae)','','','','','','','');
insert ignore into natura2000.ref_habitats values(209,'9310',0,'Aegean Quercus brachyphylla woods','','','','','','','');
insert ignore into natura2000.ref_habitats values(210,'9320',0,'Olea and Ceratonia forests','','','','','','','');
insert ignore into natura2000.ref_habitats values(211,'9330',0,'Quercus suber forests','','','','','','','');
insert ignore into natura2000.ref_habitats values(212,'9340',0,'Quercus ilex and Quercus rotundifolia forests','','','','','','','');
insert ignore into natura2000.ref_habitats values(213,'9350',0,'Quercus macrolepis forests','','','','','','','');
insert ignore into natura2000.ref_habitats values(214,'9360',1,'Macaronesian laurel forests (Laurus, Ocotea)','','','','','','','');
insert ignore into natura2000.ref_habitats values(215,'9370',1,'Palm groves of Phoenix','','','','','','','');
insert ignore into natura2000.ref_habitats values(216,'9380',0,'Forests of Ilex aquifolium','','','','','','','');
insert ignore into natura2000.ref_habitats values(217,'9390',1,'Scrub and low forest vegetation with Quercus alnifolia','','','','','','','');
insert ignore into natura2000.ref_habitats values(218,'93A0',0,'Woodlands with Quercus infectoria (Anagyro foetidae-Quercetum infectoriae)','','','','','','','');
insert ignore into natura2000.ref_habitats values(219,'9410',0,'Acidophilous Picea forests of the montane to alpine levels (Vaccinio-Piceetea)','','','','','','','');
insert ignore into natura2000.ref_habitats values(220,'9420',0,'Alpine Larix decidua and/or Pinus cembra forests','','','','','','','');
insert ignore into natura2000.ref_habitats values(221,'9430',0,'Subalpine and montane Pinus uncinata forests (* if on gypsum or limestone)','','','','','','','');
insert ignore into natura2000.ref_habitats values(222,'9510',1,'Southern Apennine Abies alba forests','','','','','','','');
insert ignore into natura2000.ref_habitats values(223,'9520',0,'Abies pinsapo forests','','','','','','','');
insert ignore into natura2000.ref_habitats values(224,'9530',1,'(Sub-) Mediterranean pine forests with endemic black pines','','','','','','','');
insert ignore into natura2000.ref_habitats values(225,'9540',0,'Mediterranean pine forests with endemic Mesogean pines','','','','','','','');
insert ignore into natura2000.ref_habitats values(226,'9550',0,'Canarian endemic pine forests','','','','','','','');
insert ignore into natura2000.ref_habitats values(227,'9560',1,'Endemic forests with Juniperus spp.','','','','','','','');
insert ignore into natura2000.ref_habitats values(228,'9570',1,'Tetraclinis articulata forests','','','','','','','');
insert ignore into natura2000.ref_habitats values(229,'9580',1,'Mediterranean Taxus baccata woods','','','','','','','');
insert ignore into natura2000.ref_habitats values(230,'9590',1,'Cedrus brevifolia forests (Cedrosetum brevifoliae)','','','','','','','');
insert ignore into natura2000.ref_habitats values(231,'95A0',0,'High oro-Mediterranean pine forests','','','','','','','');
commit;