insert ignore into ref_nuts values (1,'BE10','Région de Bruxelles-Capitale / Brussels Hoofdstedelijk Gewest');
insert ignore into ref_nuts values (2,'BE21','Prov. Antwerpen');
insert ignore into ref_nuts values (3,'BE22','Prov. Limburg (B)');
insert ignore into ref_nuts values (4,'BE23','Prov. Oost-Vlaanderen');
insert ignore into ref_nuts values (5,'BE24','Prov. Vlaams-Brabant');
insert ignore into ref_nuts values (6,'BE25','Prov. West-Vlaanderen');
insert ignore into ref_nuts values (7,'BE31','Prov. Brabant Wallon');
insert ignore into ref_nuts values (8,'BE32','Prov. Hainaut');
insert ignore into ref_nuts values (9,'BE33','Prov. Liège');
insert ignore into ref_nuts values (10,'BE34','Prov. Luxembourg (B)');
insert ignore into ref_nuts values (11,'BE35','Prov. Namur');
insert ignore into ref_nuts values (12,'BEZZ','Extra-Regio');
insert ignore into ref_nuts values (13,'BG31','Северозападен / Severozapaden');
insert ignore into ref_nuts values (14,'BG32','Северен централен / Severen tsentralen');
insert ignore into ref_nuts values (15,'BG33','Североизточен / Severoiztochen');
insert ignore into ref_nuts values (16,'BG34','Югоизточен / Yugoiztochen');
insert ignore into ref_nuts values (17,'BG41','Югозападен / Yugozapaden');
insert ignore into ref_nuts values (18,'BG42','Южен централен / Yuzhen tsentralen');
insert ignore into ref_nuts values (19,'BGZZ','Extra-Regio');
insert ignore into ref_nuts values (20,'CZ01','Praha');
insert ignore into ref_nuts values (21,'CZ02','Střední Čechy');
insert ignore into ref_nuts values (22,'CZ03','Jihozápad');
insert ignore into ref_nuts values (23,'CZ04','Severozápad');
insert ignore into ref_nuts values (24,'CZ05','Severovýchod');
insert ignore into ref_nuts values (25,'CZ06','Jihovýchod');
insert ignore into ref_nuts values (26,'CZ07','Střední Morava');
insert ignore into ref_nuts values (27,'CZ08','Moravskoslezsko');
insert ignore into ref_nuts values (28,'CZZZ','Extra-Regio');
insert ignore into ref_nuts values (29,'DK01','Hovedstaden');
insert ignore into ref_nuts values (30,'DK02','Sjælland');
insert ignore into ref_nuts values (31,'DK03','Syddanmark');
insert ignore into ref_nuts values (32,'DK04','Midtjylland');
insert ignore into ref_nuts values (33,'DK05','Nordjylland');
insert ignore into ref_nuts values (34,'DKZZ','Extra-Regio');
insert ignore into ref_nuts values (35,'DE11','Stuttgart');
insert ignore into ref_nuts values (36,'DE12','Karlsruhe');
insert ignore into ref_nuts values (37,'DE13','Freiburg');
insert ignore into ref_nuts values (38,'DE14','Tübingen');
insert ignore into ref_nuts values (39,'DE21','Oberbayern');
insert ignore into ref_nuts values (40,'DE22','Niederbayern');
insert ignore into ref_nuts values (41,'DE23','Oberpfalz');
insert ignore into ref_nuts values (42,'DE24','Oberfranken');
insert ignore into ref_nuts values (43,'DE25','Mittelfranken');
insert ignore into ref_nuts values (44,'DE26','Unterfranken');
insert ignore into ref_nuts values (45,'DE27','Schwaben');
insert ignore into ref_nuts values (46,'DE30','Berlin');
insert ignore into ref_nuts values (47,'DE41','Brandenburg - Nordost');
insert ignore into ref_nuts values (48,'DE42','Brandenburg - Südwest');
insert ignore into ref_nuts values (49,'DE50','Bremen');
insert ignore into ref_nuts values (50,'DE60','Hamburg');
insert ignore into ref_nuts values (51,'DE71','Darmstadt');
insert ignore into ref_nuts values (52,'DE72','Gießen');
insert ignore into ref_nuts values (53,'DE73','Kassel');
insert ignore into ref_nuts values (54,'DE80','Mecklenburg-Vorpommern');
insert ignore into ref_nuts values (55,'DE91','Braunschweig');
insert ignore into ref_nuts values (56,'DE92','Hannover');
insert ignore into ref_nuts values (57,'DE93','Lüneburg');
insert ignore into ref_nuts values (58,'DE94','Weser-Ems');
insert ignore into ref_nuts values (59,'DEA1','Düsseldorf');
insert ignore into ref_nuts values (60,'DEA2','Köln');
insert ignore into ref_nuts values (61,'DEA3','Münster');
insert ignore into ref_nuts values (62,'DEA4','Detmold');
insert ignore into ref_nuts values (63,'DEA5','Arnsberg');
insert ignore into ref_nuts values (64,'DEB1','Koblenz');
insert ignore into ref_nuts values (65,'DEB2','Trier');
insert ignore into ref_nuts values (66,'DEB3','Rheinhessen-Pfalz');
insert ignore into ref_nuts values (67,'DEC0','Saarland');
insert ignore into ref_nuts values (68,'DED1','Chemnitz');
insert ignore into ref_nuts values (69,'DED2','Dresden');
insert ignore into ref_nuts values (70,'DED3','Leipzig');
insert ignore into ref_nuts values (71,'DEE0','Sachsen-Anhalt');
insert ignore into ref_nuts values (72,'DEF0','Schleswig-Holstein');
insert ignore into ref_nuts values (73,'DEG0','Thüringen');
insert ignore into ref_nuts values (74,'DEZZ','Extra-Regio');
insert ignore into ref_nuts values (75,'EE00','Eesti');
insert ignore into ref_nuts values (76,'EEZZ','Extra-Regio');
insert ignore into ref_nuts values (77,'IE01','Border, Midland and Western');
insert ignore into ref_nuts values (78,'IE02','Southern and Eastern');
insert ignore into ref_nuts values (79,'IEZZ','Extra-Regio');
insert ignore into ref_nuts values (80,'GR11','Aνατολική Μακεδονία, Θράκη / Anatoliki Makedonia, Thraki');
insert ignore into ref_nuts values (81,'GR12','Κεντρική Μακεδονία / Kentriki Makedonia');
insert ignore into ref_nuts values (82,'GR13','Δυτική Μακεδονία / Dytiki Makedonia');
insert ignore into ref_nuts values (83,'GR14','Θεσσαλία / Thessalia');
insert ignore into ref_nuts values (84,'GR21','Ήπειρος / Ipeiros');
insert ignore into ref_nuts values (85,'GR22','Ιόνια Νησιά / Ionia Nisia');
insert ignore into ref_nuts values (86,'GR23','Δυτική Ελλάδα / Dytiki Ellada');
insert ignore into ref_nuts values (87,'GR24','Στερεά Ελλάδα / Sterea Ellada');
insert ignore into ref_nuts values (88,'GR25','Πελοπόννησος / Peloponnisos');
insert ignore into ref_nuts values (89,'GR30','Aττική / Attiki');
insert ignore into ref_nuts values (90,'GR41','Βόρειο Αιγαίο / Voreio Aigaio');
insert ignore into ref_nuts values (91,'GR42','Νότιο Αιγαίο / Notio Aigaio');
insert ignore into ref_nuts values (92,'GR43','Κρήτη / Kriti');
insert ignore into ref_nuts values (93,'GRZZ','Extra-Regio');
insert ignore into ref_nuts values (94,'ES11','Galicia');
insert ignore into ref_nuts values (95,'ES12','Principado de Asturias');
insert ignore into ref_nuts values (96,'ES13','Cantabria');
insert ignore into ref_nuts values (97,'ES21','País Vasco');
insert ignore into ref_nuts values (98,'ES22','Comunidad Foral de Navarra');
insert ignore into ref_nuts values (99,'ES23','La Rioja');
insert ignore into ref_nuts values (100,'ES24','Aragón');
insert ignore into ref_nuts values (101,'ES30','Comunidad de Madrid');
insert ignore into ref_nuts values (102,'ES41','Castilla y León');
insert ignore into ref_nuts values (103,'ES42','Castilla-La Mancha');
insert ignore into ref_nuts values (104,'ES43','Extremadura');
insert ignore into ref_nuts values (105,'ES51','Cataluña');
insert ignore into ref_nuts values (106,'ES52','Comunidad Valenciana');
insert ignore into ref_nuts values (107,'ES53','Illes Balears');
insert ignore into ref_nuts values (108,'ES61','Andalucía');
insert ignore into ref_nuts values (109,'ES62','Región de Murcia');
insert ignore into ref_nuts values (110,'ES63','Ciudad Autónoma de Ceuta');
insert ignore into ref_nuts values (111,'ES64','Ciudad Autónoma de Melilla');
insert ignore into ref_nuts values (112,'ES70','Canarias');
insert ignore into ref_nuts values (113,'ESZZ','Extra-Regio');
insert ignore into ref_nuts values (114,'FR10','Île de France');
insert ignore into ref_nuts values (115,'FR21','Champagne-Ardenne');
insert ignore into ref_nuts values (116,'FR22','Picardie');
insert ignore into ref_nuts values (117,'FR23','Haute-Normandie');
insert ignore into ref_nuts values (118,'FR24','Centre');
insert ignore into ref_nuts values (119,'FR25','Basse-Normandie');
insert ignore into ref_nuts values (120,'FR26','Bourgogne');
insert ignore into ref_nuts values (121,'FR30','Nord - Pas-de-Calais');
insert ignore into ref_nuts values (122,'FR41','Lorraine');
insert ignore into ref_nuts values (123,'FR42','Alsace');
insert ignore into ref_nuts values (124,'FR43','Franche-Comté');
insert ignore into ref_nuts values (125,'FR51','Pays de la Loire');
insert ignore into ref_nuts values (126,'FR52','Bretagne');
insert ignore into ref_nuts values (127,'FR53','Poitou-Charentes');
insert ignore into ref_nuts values (128,'FR61','Aquitaine');
insert ignore into ref_nuts values (129,'FR62','Midi-Pyrénées');
insert ignore into ref_nuts values (130,'FR63','Limousin');
insert ignore into ref_nuts values (131,'FR71','Rhône-Alpes');
insert ignore into ref_nuts values (132,'FR72','Auvergne');
insert ignore into ref_nuts values (133,'FR81','Languedoc-Roussillon');
insert ignore into ref_nuts values (134,'FR82','Provence-Alpes-Côte d´Azur');
insert ignore into ref_nuts values (135,'FR83','Corse');
insert ignore into ref_nuts values (136,'FR91','Guadeloupe');
insert ignore into ref_nuts values (137,'FR92','Martinique');
insert ignore into ref_nuts values (138,'FR93','Guyane');
insert ignore into ref_nuts values (139,'FR94','Réunion');
insert ignore into ref_nuts values (140,'FRZZ','Extra-Regio');
insert ignore into ref_nuts values (141,'ITC1','Piemonte');
insert ignore into ref_nuts values (142,'ITC2','Valle d´Aosta/Vallée d´Aoste');
insert ignore into ref_nuts values (143,'ITC3','Liguria');
insert ignore into ref_nuts values (144,'ITC4','Lombardia');
insert ignore into ref_nuts values (145,'ITD1','Provincia Autonoma Bolzano/Bozen');
insert ignore into ref_nuts values (146,'ITD2','Provincia Autonoma Trento');
insert ignore into ref_nuts values (147,'ITD3','Veneto');
insert ignore into ref_nuts values (148,'ITD4','Friuli-Venezia Giulia');
insert ignore into ref_nuts values (149,'ITD5','Emilia-Romagna');
insert ignore into ref_nuts values (150,'ITE1','Toscana');
insert ignore into ref_nuts values (151,'ITE2','Umbria');
insert ignore into ref_nuts values (152,'ITE3','Marche');
insert ignore into ref_nuts values (153,'ITE4','Lazio');
insert ignore into ref_nuts values (154,'ITF1','Abruzzo');
insert ignore into ref_nuts values (155,'ITF2','Molise');
insert ignore into ref_nuts values (156,'ITF3','Campania');
insert ignore into ref_nuts values (157,'ITF4','Puglia');
insert ignore into ref_nuts values (158,'ITF5','Basilicata');
insert ignore into ref_nuts values (159,'ITF6','Calabria');
insert ignore into ref_nuts values (160,'ITG1','Sicilia');
insert ignore into ref_nuts values (161,'ITG2','Sardegna');
insert ignore into ref_nuts values (162,'ITZZ','Extra-Regio');
insert ignore into ref_nuts values (163,'CY00','Κύπρος / Kıbrıs');
insert ignore into ref_nuts values (164,'CYZZ','Extra-Regio');
insert ignore into ref_nuts values (165,'LV00','Latvija');
insert ignore into ref_nuts values (166,'LVZZ','Extra-Regio');
insert ignore into ref_nuts values (167,'LT00','Lietuva');
insert ignore into ref_nuts values (168,'LTZZ','Extra-Regio');
insert ignore into ref_nuts values (169,'LU00','Luxembourg (Grand-Duché)');
insert ignore into ref_nuts values (170,'LUZZ','Extra-Regio');
insert ignore into ref_nuts values (171,'HU10','Közép-Magyarország');
insert ignore into ref_nuts values (172,'HU21','Közép-Dunántúl');
insert ignore into ref_nuts values (173,'HU22','Nyugat-Dunántúl');
insert ignore into ref_nuts values (174,'HU23','Dél-Dunántúl');
insert ignore into ref_nuts values (175,'HU31','Észak-Magyarország');
insert ignore into ref_nuts values (176,'HU32','Észak-Alföld');
insert ignore into ref_nuts values (177,'HU33','Dél-Alföld');
insert ignore into ref_nuts values (178,'HUZZ','Extra-Regio');
insert ignore into ref_nuts values (179,'HR0','HRVATSKA');
insert ignore into ref_nuts values (180,'MT00','Malta');
insert ignore into ref_nuts values (181,'MTZZ','Extra-Regio');
insert ignore into ref_nuts values (182,'NL11','Groningen');
insert ignore into ref_nuts values (183,'NL12','Friesland (NL)');
insert ignore into ref_nuts values (184,'NL13','Drenthe');
insert ignore into ref_nuts values (185,'NL21','Overijssel');
insert ignore into ref_nuts values (186,'NL22','Gelderland');
insert ignore into ref_nuts values (187,'NL23','Flevoland');
insert ignore into ref_nuts values (188,'NL31','Utrecht');
insert ignore into ref_nuts values (189,'NL32','Noord-Holland');
insert ignore into ref_nuts values (190,'NL33','Zuid-Holland');
insert ignore into ref_nuts values (191,'NL34','Zeeland');
insert ignore into ref_nuts values (192,'NL41','Noord-Brabant');
insert ignore into ref_nuts values (193,'NL42','Limburg (NL)');
insert ignore into ref_nuts values (194,'NLZZ','Extra-Regio');
insert ignore into ref_nuts values (195,'AT11','Burgenland (A)');
insert ignore into ref_nuts values (196,'AT12','Niederösterreich');
insert ignore into ref_nuts values (197,'AT13','Wien');
insert ignore into ref_nuts values (198,'AT21','Kärnten');
insert ignore into ref_nuts values (199,'AT22','Steiermark');
insert ignore into ref_nuts values (200,'AT31','Oberösterreich');
insert ignore into ref_nuts values (201,'AT32','Salzburg');
insert ignore into ref_nuts values (202,'AT33','Tirol');
insert ignore into ref_nuts values (203,'AT34','Vorarlberg');
insert ignore into ref_nuts values (204,'ATZZ','Extra-Regio');
insert ignore into ref_nuts values (205,'PL11','Łódzkie');
insert ignore into ref_nuts values (206,'PL12','Mazowieckie');
insert ignore into ref_nuts values (207,'PL21','Małopolskie');
insert ignore into ref_nuts values (208,'PL22','Śląskie');
insert ignore into ref_nuts values (209,'PL31','Lubelskie');
insert ignore into ref_nuts values (210,'PL32','Podkarpackie');
insert ignore into ref_nuts values (211,'PL33','Świętokrzyskie');
insert ignore into ref_nuts values (212,'PL34','Podlaskie');
insert ignore into ref_nuts values (213,'PL41','Wielkopolskie');
insert ignore into ref_nuts values (214,'PL42','Zachodniopomorskie');
insert ignore into ref_nuts values (215,'PL43','Lubuskie');
insert ignore into ref_nuts values (216,'PL51','Dolnośląskie');
insert ignore into ref_nuts values (217,'PL52','Opolskie');
insert ignore into ref_nuts values (218,'PL61','Kujawsko-Pomorskie');
insert ignore into ref_nuts values (219,'PL62','Warmińsko-Mazurskie');
insert ignore into ref_nuts values (220,'PL63','Pomorskie');
insert ignore into ref_nuts values (221,'PLZZ','Extra-Regio');
insert ignore into ref_nuts values (222,'PT11','Norte');
insert ignore into ref_nuts values (223,'PT15','Algarve');
insert ignore into ref_nuts values (224,'PT16','Centro (P)');
insert ignore into ref_nuts values (225,'PT17','Lisboa');
insert ignore into ref_nuts values (226,'PT18','Alentejo');
insert ignore into ref_nuts values (227,'PT20','Região Autónoma dos Açores');
insert ignore into ref_nuts values (228,'PT30','Região Autónoma da Madeira');
insert ignore into ref_nuts values (229,'PTZZ','Extra-Regio');
insert ignore into ref_nuts values (230,'RO11','Nord-Vest');
insert ignore into ref_nuts values (231,'RO12','Centru');
insert ignore into ref_nuts values (232,'RO21','Nord-Est');
insert ignore into ref_nuts values (233,'RO22','Sud-Est');
insert ignore into ref_nuts values (234,'RO31','Sud - Muntenia');
insert ignore into ref_nuts values (235,'RO32','Bucureşti - Ilfov');
insert ignore into ref_nuts values (236,'RO41','Sud-Vest Oltenia');
insert ignore into ref_nuts values (237,'RO42','Vest');
insert ignore into ref_nuts values (238,'ROZZ','Extra-Regio');
insert ignore into ref_nuts values (239,'SI01','Vzhodna Slovenija');
insert ignore into ref_nuts values (240,'SI02','Zahodna Slovenija');
insert ignore into ref_nuts values (241,'SIZZ','Extra-Regio');
insert ignore into ref_nuts values (242,'SK01','Bratislavský kraj');
insert ignore into ref_nuts values (243,'SK02','Západné Slovensko');
insert ignore into ref_nuts values (244,'SK03','Stredné Slovensko');
insert ignore into ref_nuts values (245,'SK04','Východné Slovensko');
insert ignore into ref_nuts values (246,'SKZZ','Extra-Regio');
insert ignore into ref_nuts values (247,'FI13','Itä-Suomi');
insert ignore into ref_nuts values (248,'FI18','Etelä-Suomi');
insert ignore into ref_nuts values (249,'FI19','Länsi-Suomi');
insert ignore into ref_nuts values (250,'FI1A','Pohjois-Suomi');
insert ignore into ref_nuts values (251,'FI20','Åland');
insert ignore into ref_nuts values (252,'FIZZ','Extra-Regio');
insert ignore into ref_nuts values (253,'SE11','Stockholm');
insert ignore into ref_nuts values (254,'SE12','Östra Mellansverige');
insert ignore into ref_nuts values (255,'SE21','Småland med öarna');
insert ignore into ref_nuts values (256,'SE22','Sydsverige');
insert ignore into ref_nuts values (257,'SE23','Västsverige');
insert ignore into ref_nuts values (258,'SE31','Norra Mellansverige');
insert ignore into ref_nuts values (259,'SE32','Mellersta Norrland');
insert ignore into ref_nuts values (260,'SE33','Övre Norrland');
insert ignore into ref_nuts values (261,'SEZZ','Extra-Regio');
insert ignore into ref_nuts values (262,'UKC1','Tees Valley and Durham');
insert ignore into ref_nuts values (263,'UKC2','Northumberland and Tyne and Wear');
insert ignore into ref_nuts values (264,'UKD1','Cumbria');
insert ignore into ref_nuts values (265,'UKD2','Cheshire');
insert ignore into ref_nuts values (266,'UKD3','Greater Manchester');
insert ignore into ref_nuts values (267,'UKD4','Lancashire');
insert ignore into ref_nuts values (268,'UKD5','Merseyside');
insert ignore into ref_nuts values (269,'UKE1','East Yorkshire and Northern Lincolnshire');
insert ignore into ref_nuts values (270,'UKE2','North Yorkshire');
insert ignore into ref_nuts values (271,'UKE3','South Yorkshire');
insert ignore into ref_nuts values (272,'UKE4','West Yorkshire');
insert ignore into ref_nuts values (273,'UKF1','Derbyshire and Nottinghamshire');
insert ignore into ref_nuts values (274,'UKF2','Leicestershire, Rutland and Northamptonshire');
insert ignore into ref_nuts values (275,'UKF3','Lincolnshire');
insert ignore into ref_nuts values (276,'UKG1','Herefordshire, Worcestershire and Warwickshire');
insert ignore into ref_nuts values (277,'UKG2','Shropshire and Staffordshire');
insert ignore into ref_nuts values (278,'UKG3','West Midlands');
insert ignore into ref_nuts values (279,'UKH1','East Anglia');
insert ignore into ref_nuts values (280,'UKH2','Bedfordshire and Hertfordshire');
insert ignore into ref_nuts values (281,'UKH3','Essex');
insert ignore into ref_nuts values (282,'UKI1','Inner London');
insert ignore into ref_nuts values (283,'UKI2','Outer London');
insert ignore into ref_nuts values (284,'UKJ1','Berkshire, Buckinghamshire and Oxfordshire');
insert ignore into ref_nuts values (285,'UKJ2','Surrey, East and West Sussex');
insert ignore into ref_nuts values (286,'UKJ3','Hampshire and Isle of Wight');
insert ignore into ref_nuts values (287,'UKJ4','Kent');
insert ignore into ref_nuts values (288,'UKK1','Gloucestershire, Wiltshire and Bristol/Bath area');
insert ignore into ref_nuts values (289,'UKK2','Dorset and Somerset');
insert ignore into ref_nuts values (290,'UKK3','Cornwall and Isles of Scilly');
insert ignore into ref_nuts values (291,'UKK4','Devon');
insert ignore into ref_nuts values (292,'UKL1','West Wales and The Valleys');
insert ignore into ref_nuts values (293,'UKL2','East Wales');
insert ignore into ref_nuts values (294,'UKM2','Eastern Scotland');
insert ignore into ref_nuts values (295,'UKM3','South Western Scotland');
insert ignore into ref_nuts values (296,'UKM5','North Eastern Scotland');
insert ignore into ref_nuts values (297,'UKM6','Highlands and Islands');
insert ignore into ref_nuts values (298,'UKN0','Northern Ireland');
insert ignore into ref_nuts values (299,'UKZZ','Extra-Regio');
commit;