insert ignore into ref_conventions VALUES(1,'Ramsar site','ramsar');
insert ignore into ref_conventions VALUES(2,'Biogenetic reserve','biogenetic');
insert ignore into ref_conventions VALUES(3,'Eurodiploma site','eurodiploma');
insert ignore into ref_conventions VALUES(4,'Biosphere reserve','biosphere');
insert ignore into ref_conventions VALUES(5,'Barcelona Conven. site','barcelona');
insert ignore into ref_conventions VALUES(6,'Bucharest Conven. site','bucharest');
insert ignore into ref_conventions VALUES(7,'World heritage site','worldHeritage');
insert ignore into ref_conventions VALUES(8,'HELCOM site','helcom');
insert ignore into ref_conventions VALUES(9,'OSPAR site','ospar');
insert ignore into ref_conventions VALUES(10,'Protected marine area','protectedMarine');
insert ignore into ref_conventions VALUES(11,'Other','other');
commit;