insert ignore into ref_biogeo VALUES(1,'Alpine','alpine');
insert ignore into ref_biogeo VALUES(2,'Anatolian','anatolian');
insert ignore into ref_biogeo VALUES(3,'Arctic','arctic');
insert ignore into ref_biogeo VALUES(4,'Atlantic','atlantic');
insert ignore into ref_biogeo VALUES(5,'Mediterranean','mediterranean');
insert ignore into ref_biogeo VALUES(6,'Black Sea','blackSea');
insert ignore into ref_biogeo VALUES(7,'Boreal','boreal');
insert ignore into ref_biogeo VALUES(8,'Continental','continental');
insert ignore into ref_biogeo VALUES(9,'Macaronesian','macaronesian');
insert ignore into ref_biogeo VALUES(10,'Pannonian','pannonian');
insert ignore into ref_biogeo VALUES(11,'Steppic','steppic');
insert ignore into ref_biogeo VALUES(12,'Marine Atlantic','marineAtlantic');
insert ignore into ref_biogeo VALUES(13,'Marine Baltic','marineBaltic');
insert ignore into ref_biogeo VALUES(14,'Marine Black Sea','marineBlackSea');
insert ignore into ref_biogeo VALUES(15,'Marine Macaronesian','marineMacaronesian');
insert ignore into ref_biogeo VALUES(16,'Marine Mediterranean','marineMediterranean');
commit;