update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A001';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A002';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A003';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A004';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A005';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A006';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A007';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Podiceps caspicus (A549)' where REF_BIRDS_CODE='A008';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A009';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Procellaria diomedea (A503)' where REF_BIRDS_CODE='A010';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A011';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A012';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A013';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A014';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A015';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Sula bassana' where REF_BIRDS_CODE='A016';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A017';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A018';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A019';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A020';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A021';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A022';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A023';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A024';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A025';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A026';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Casmerodius albus,  Ardea alba' where REF_BIRDS_CODE='A027';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A028';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A029';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A030';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A031';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A032';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A033';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A034';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A035';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A036';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Cygnus bewickii' where REF_BIRDS_CODE='A037';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A038';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A039';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A040';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A041';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A042';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A043';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A044';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A045';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A046';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A048';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A050';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A051';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A052';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A053';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A054';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A055';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A056';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A057';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A058';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A059';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A060';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A061';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A062';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A063';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A064';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A065';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A066';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A067';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Mergellus albellus' where REF_BIRDS_CODE='A068';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A069';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A070';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A071';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A072';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A073';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A074';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A075';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A076';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A077';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A078';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A079';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A080';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A081';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A082';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A083';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A084';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A085';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A086';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A087';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A088';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A089';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A090';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A091';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A092';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Aquila fasciatus' where REF_BIRDS_CODE='A093';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A094';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A095';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A096';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A097';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A098';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A099';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A100';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A101';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A102';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A103';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A104';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A105';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Lagopus muta' where REF_BIRDS_CODE='A106';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A107';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A108';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A109';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A110';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A111';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A112';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A113';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A115';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Turnix sylvaticus' where REF_BIRDS_CODE='A117';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A118';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A119';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A120';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A121';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A122';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A123';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A124';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A125';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A126';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A127';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A128';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A129';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A130';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A131';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A132';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A133';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A134';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A135';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A136';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A137';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A138';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Eudromias morinellus' where REF_BIRDS_CODE='A139';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A140';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A141';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A142';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A143';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A144';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A145';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A146';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A147';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A148';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A149';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A150';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A151';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A152';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A153';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A154';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A155';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A156';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A157';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A158';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A159';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A160';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A161';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A162';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A163';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A164';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A165';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A166';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Tringa cinerea (A518)' where REF_BIRDS_CODE='A167';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A168';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A169';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A170';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Phalaropus fulicaria' where REF_BIRDS_CODE='A171';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A172';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A173';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A174';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Stercorarius skua' where REF_BIRDS_CODE='A175';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A176';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A177';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Xema sabini' where REF_BIRDS_CODE='A178';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A179';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A180';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A181';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A182';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A183';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A184';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A185';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A186';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A187';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A188';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Sterna nilotica' where REF_BIRDS_CODE='A189';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A190';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A191';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A192';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A193';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A194';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A195';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Chlidonias hybrida' where REF_BIRDS_CODE='A196';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A197';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A198';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A199';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A200';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A202';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A203';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A204';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A205';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='livia and domestica' where REF_BIRDS_CODE='A206';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A207';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A208';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A209';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A210';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A211';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A212';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A213';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A214';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A215';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Bubo scandiaca' where REF_BIRDS_CODE='A216';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A217';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A218';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A219';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A220';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A221';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A222';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A223';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A224';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A225';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A226';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A227';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Apus melba' where REF_BIRDS_CODE='A228';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A229';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A230';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A231';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A232';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A233';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A234';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A235';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A236';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A237';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A238';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A239';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A240';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Dendrocopos tridactylus' where REF_BIRDS_CODE='A241';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A242';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A243';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A244';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A245';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A246';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A247';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A248';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A249';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Hirundo rupestris' where REF_BIRDS_CODE='A250';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A251';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A252';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Delichon urbicum' where REF_BIRDS_CODE='A253';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Anthus novaeseelandiae (A526)' where REF_BIRDS_CODE='A254';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A255';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A256';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A257';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A258';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A259';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A260';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Motacilla finere (A527)' where REF_BIRDS_CODE='A261';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A262';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A263';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A264';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A265';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A266';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A267';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Erythropygia galactotes' where REF_BIRDS_CODE='A268';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A269';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A270';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A271';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A272';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A273';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A274';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A275';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Saxicola torquata, Phoenicurus torquata (A567)' where REF_BIRDS_CODE='A276';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A277';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A278';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A279';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A280';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A281';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A282';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A283';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A284';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A285';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A286';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A287';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A288';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A289';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A290';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A291';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A292';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A293';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A294';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A295';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A296';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A297';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A298';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A299';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A300';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A301';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A302';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A303';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A304';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A305';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A306';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A307';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A308';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A309';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A310';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A311';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A312';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A313';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A314';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A315';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A316';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A317';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A318';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A319';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A320';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A321';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A322';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A323';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A324';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A325';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A326';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A327';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A328';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A329';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A330';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A331';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A332';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A333';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A334';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A335';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A336';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A337';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A338';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A339';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A340';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A341';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A342';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A343';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A344';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A345';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A346';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A347';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A348';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A349';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A350';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A351';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A352';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A353';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A354';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A355';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A356';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A357';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A358';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A359';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A360';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A361';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Serinus citrinella'  where REF_BIRDS_CODE='A362';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Carduelis chloris' where REF_BIRDS_CODE='A363';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A364';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A365';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A366';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A367';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A368';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A369';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A370';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A371';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A372';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A373';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A374';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A375';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A376';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A377';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A378';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A379';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A380';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A381';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A382';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Miliaria calandra' where REF_BIRDS_CODE='A383';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Puffinus mauretanicus' where REF_BIRDS_CODE='A384';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Pterodroma mollis madeira' where REF_BIRDS_CODE='A385';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Pterodroma mollis feae' where REF_BIRDS_CODE='A386';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A387';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A388';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A389';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A390';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A391';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A392';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A393';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A394';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A395';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A396';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A397';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A398';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A399';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A400';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A401';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A402';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A403';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A404';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Aquila heliaca adalberti' where REF_BIRDS_CODE='A405';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0'and  REF_BIRDS_ALT_SCIENTIFIC_NAME ='Lagopus muta pyrenaica' where REF_BIRDS_CODE='A407';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Lagopus muta helvetica' where REF_BIRDS_CODE='A408';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A409';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A410';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A411';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A412';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A413';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A414';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A415';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A416';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A417';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Vanellus spinosus' where REF_BIRDS_CODE='A418';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A419';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A420';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A421';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A422';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A423';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A424';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A425';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A426';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A427';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A428';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A429';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A430';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A431';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Anthus berthelotti' where REF_BIRDS_CODE='A432';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A433';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A434';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A435';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A436';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A437';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Hippolais pallida' where REF_BIRDS_CODE='A438';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A439';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A440';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Muscicapa latirostris' where REF_BIRDS_CODE='A441';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A442';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A443';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A444';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A445';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A446';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A447';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A448';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A449';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A450';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A451';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Rhodopechys githaginea (A546)' where REF_BIRDS_CODE='A452';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Pyrrhula pyrrhula murina' where REF_BIRDS_CODE='A453';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Cyanopica cyana' where REF_BIRDS_CODE='A454';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A455';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A456';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A457';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Larus argentatus cachinnans' where REF_BIRDS_CODE='A459';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A460';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A461';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Lagopus lagopus scotica' where REF_BIRDS_CODE='A462';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A463';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Puffinus puffinus yelkouan' where REF_BIRDS_CODE='A464';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A465';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A466';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Saxicola cypriaca, Oenanthe pleschanka cypriaca' where REF_BIRDS_CODE='A467';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A468';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A469';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A470';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A501';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A502';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='1', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Calonectris diomedea' where REF_BIRDS_CODE='A503';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A504';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A505';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A506';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A507';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A508';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Aquila rapax nipalensis' where REF_BIRDS_CODE='A509';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Aquila rapax rapax' where REF_BIRDS_CODE='A510';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A511';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A512';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A513';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Grus virgo' where REF_BIRDS_CODE='A514';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A515';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A516';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A517';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='1', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Xenus cinereus' where REF_BIRDS_CODE='A518';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A519';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A520';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A521';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A522';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A523';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A524';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A525';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='1', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Anthus richardi' where REF_BIRDS_CODE='A526';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='1', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Motacilla cinerea' where REF_BIRDS_CODE='A527';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A528';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A529';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A530';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A531';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Oenanthe finischii' where REF_BIRDS_CODE='A532';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A533';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A534';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Regulus regulus teneriffae' where REF_BIRDS_CODE='A535';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A536';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A537';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A538';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A539';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A540';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Emberiza leucocephala' where REF_BIRDS_CODE='A541';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A542';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A543';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A544';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A545';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='1', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Bucanetes githagineus' where REF_BIRDS_CODE='A546';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A547';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A548';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='1', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Podiceps nigricollis' where REF_BIRDS_CODE='A549';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A550';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A551';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Ardea virescens, Butorides striatus' where REF_BIRDS_CODE='A552';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A553';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A554';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A555';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A556';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A557';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A558';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A559';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A560';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A561';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A562';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A563';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A564';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A565';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A566';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='1', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Saxicola torquata, Saxicola torquatus' where REF_BIRDS_CODE='A567';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A568';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A602';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A603';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Larus argentatus michahellis' where REF_BIRDS_CODE='A604';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0' where REF_BIRDS_CODE='A605';
update natura2000.ref_birds set REF_BIRDS_CODE_NEW='0', REF_BIRDS_ALT_SCIENTIFIC_NAME ='Vanellus gregarius' where REF_BIRDS_CODE='A606';
insert ignore into natura2000.ref_birds VALUES (537,'A607','Platalea leucorodia leucorodia','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (538,'A608','Motacilla citreola','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (539,'A609','Luscinia svecica svecica','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (540,'A610','Nycticorax nycticorax nycticorax','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (541,'A611','Luscinia svecica namnetum','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (542,'A612','Luscinia svecica cyanecula','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (543,'A613','Phylloscopus canariensis','0','0','0','0','0','0','Ph1lloscopus coll1bita canariensis');
insert ignore into natura2000.ref_birds VALUES (544,'A614','Limosa limosa limosa','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (545,'A615','Corvus cornix','0','0','0','0','0','0','Corvus corone cornix');
insert ignore into natura2000.ref_birds VALUES (546,'A616','Limosa limosa islandica','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (547,'A617','Ixobrychus minutus minutus','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (548,'A618','Phylloscopus ibericus','0','0','0','0','0','0','Ph1lloscopus coll1bita ibericus');
insert ignore into natura2000.ref_birds VALUES (549,'A619','Accipiter gentilis gentilis','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (550,'A620','Passer domesticus','0','0','0','0','0','0','Passer domesticus domesticus');
insert ignore into natura2000.ref_birds VALUES (551,'A621','Passer italiae','0','0','0','0','0','0','Passer domesticus italiae');
insert ignore into natura2000.ref_birds VALUES (552,'A623','Carduelis citrinella','0','0','0','0','0','0','Serinus citrinella citrinella');
insert ignore into natura2000.ref_birds VALUES (553,'A624','Chettusia leucura','0','0','0','0','0','0','Va0ellus leucurus');
insert ignore into natura2000.ref_birds VALUES (554,'A625','Glareola pratincola pratincola','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (555,'A626','Lagopus mutus mutus','0','0','0','0','0','0','Lagopus muta muta');
insert ignore into natura2000.ref_birds VALUES (556,'A627','Corvus corone','0','0','0','0','0','0','Corvus corone corone');
insert ignore into natura2000.ref_birds VALUES (557,'A628','Lagopus mutus millaisi','0','0','0','0','0','0','Lagopus muta millaisi');
insert ignore into natura2000.ref_birds VALUES (558,'A629','Lagopus lagopus rossica','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (559,'A630','Oceanodroma monteiroi','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (560,'A631','Sterna albifrons albifrons','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (561,'A632','Pluvialis apricaria apricaria','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (562,'A633','Accipiter nisus nisus','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (563,'A634','Ardea purpurea purpurea','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (564,'A635','Ardeola ralloides ralloides','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (565,'A636','Fringilla teydea teydea','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (566,'A637','Certhia brachydactyla all others','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (567,'A638','Grus grus all others','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (568,'A639','Grus grus grus','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (569,'A640','Larus fuscus fuscus','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (570,'A641','Larus fuscus intermedius','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (571,'A642','Podiceps auritus auritus','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (572,'A643','Fringilla teydea polatzeki','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (573,'A644','Perdix perdix all others','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (574,'A645','Sylvia undata undata','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (575,'A646','Sylvia undata dartfordiensis','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (576,'A647','Sylvia cantillans moltonii','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (577,'A648','Sylvia cantillans cantillans','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (578,'A649','Regulus regulus sanctaemariae','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (579,'A650','Regulus regulus inermis','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (580,'A651','Regulus regulus azoricus','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (581,'A652','Regulus madeirensis','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (582,'A653','Lanius excubitor excubitor','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (583,'A654','Mergus merganser merganser','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (584,'A655','Lanius excubitor meridionalis','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (585,'A656','Parus ater all others','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (586,'A657','Fringilla coelebs all others','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (587,'A658','Dendrocopos major all others','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (588,'A659','Tetrao urogallus all others','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (589,'A660','Gelochelidon nilotica nilotica','0','0','0','0','0','0','Sterna Nilotica');
insert ignore into natura2000.ref_birds VALUES (590,'A661','Tetrao urogallus aquitanicus','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (591,'A662','Uria aalge albionis','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (592,'A663','Phoenicopterus roseus','0','0','0','0','0','0','Phoenicopterus ruber roseus');
insert ignore into natura2000.ref_birds VALUES (593,'A664','Larus fuscus graellsii','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (594,'A665','Podiceps grisegena grisegena','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (595,'A666','Anthus petrosus','0','0','0','0','0','0','Anthus spinoletta petrosus');
insert ignore into natura2000.ref_birds VALUES (596,'A667','Ciconia ciconia ciconia','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (597,'A668','Charadrius leschenaultii columbinus','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (598,'A669','Carduelis corsicana','0','0','0','0','0','0','Serinus citrinella corsicana');
insert ignore into natura2000.ref_birds VALUES (599,'A670','Calidris maritima maritima','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (600,'A671','Calidris canutus islandica','0','0','0','0','0','0','Calidris canutus islandicus');
insert ignore into natura2000.ref_birds VALUES (601,'A672','Calidris alpina alpina','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (602,'A673','Burhinus oedicnemus oedicnemus','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (603,'A674','Branta bernicla hrota','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (604,'A675','Branta bernicla bernicla','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (605,'A676','Troglodytes troglodytes all others','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (606,'A677','Apus affinis','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (607,'A678','Uria aalge aalge','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (608,'A679','Acrocephalus dumetorum','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (609,'A680','Acrocephalus agricola','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (610,'A681','Carduelis cabaret','0','0','0','0','0','0','Carduelis flammea cabaret');
insert ignore into natura2000.ref_birds VALUES (611,'A682','Charadrius alexandrinus alexandrinus','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (612,'A683','Phalacrocorax carbo carbo','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (613,'A684','Phalacrocorax aristotelis aristotelis','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (614,'A685','Melanitta fusca fusca','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (615,'A686','Iduna caligata','0','0','0','0','0','0','Hippolais caligata');
insert ignore into natura2000.ref_birds VALUES (616,'A687','Columba palumbus palumbus','0','0','0','0','0','0','');
insert ignore into natura2000.ref_birds VALUES (617,'A688','Botaurus stellaris stellaris','0','0','0','0','0','0','');
commit;
