insert ignore into ref_impacts values(1,'A','Agriculture','','1pp','');
insert ignore into ref_impacts values(2,'A01','Cultivation','includes increase of agricultural area','100','100');
insert ignore into ref_impacts values(3,'A02','modification of cultivation practices','includes also intallation of perennial non-timber crops','101','101');
insert ignore into ref_impacts values(4,'A02.01','agricultural intensification','','','');
insert ignore into ref_impacts values(5,'A02.02','crop change','','','');
insert ignore into ref_impacts values(6,'A02.03','grassland removal for arable land','','','');
insert ignore into ref_impacts values(7,'A03','mowing / cutting of grassland','','102','102');
insert ignore into ref_impacts values(8,'A03.01','intensive mowing or intensification','','','');
insert ignore into ref_impacts values(9,'A03.02','non intensive mowing','','','');
insert ignore into ref_impacts values(10,'A03.03','abandonment / lack of  mowing','','','');
insert ignore into ref_impacts values(11,'A04','grazing','','140','140');
insert ignore into ref_impacts values(12,'A04.01','intensive grazing','','','');
insert ignore into ref_impacts values(13,'A04.01.01','intensive cattle grazing','','','');
insert ignore into ref_impacts values(14,'A04.01.02','intensive sheep grazing','','','');
insert ignore into ref_impacts values(15,'A04.01.03','intensive horse grazing','','','');
insert ignore into ref_impacts values(16,'A04.01.04','intensive goat grazing','','','');
insert ignore into ref_impacts values(17,'A04.01.05','intensive mixed animal grazing','','','');
insert ignore into ref_impacts values(18,'A04.02','non intensive grazing','','','');
insert ignore into ref_impacts values(19,'A04.02.01','non intensive cattle grazing','','','');
insert ignore into ref_impacts values(20,'A04.02.02','non intensive sheep grazing','','','');
insert ignore into ref_impacts values(21,'A04.02.03','non intensive horse grazing','','','');
insert ignore into ref_impacts values(22,'A04.02.04','non intensive goat grazing','','','');
insert ignore into ref_impacts values(23,'A04.02.05','non intensive mixed animal grazing','','','');
insert ignore into ref_impacts values(24,'A04.03','abandonment of pastoral systems, lack of grazing','','141','141');
insert ignore into ref_impacts values(25,'A05','livestock farming and animal breeding (without grazing)','','170 (+171)','');
insert ignore into ref_impacts values(26,'A05.01','Animal breeding,','','170','170');
insert ignore into ref_impacts values(27,'A05.02','stock feeding','','171','171');
insert ignore into ref_impacts values(28,'A05.03','Lack of animal breeding','','','');
insert ignore into ref_impacts values(29,'A06','annual and perennial non-timber crops','','','');
insert ignore into ref_impacts values(30,'A06.01','annual crops for food production','','','');
insert ignore into ref_impacts values(31,'A06.01.01','intensive annual crops for food production/ intensification','','','');
insert ignore into ref_impacts values(32,'A06.01.02','non- intensive annual crops for food production','','','');
insert ignore into ref_impacts values(33,'A06.02','perennial non-timber crops','includes olive grooves, orchards and vineyards','','');
insert ignore into ref_impacts values(34,'A06.02.01','intensive perennial non-timber crops/intensification','','','');
insert ignore into ref_impacts values(35,'A06.02.02','non-intensive perennial non-timber crops','','','');
insert ignore into ref_impacts values(36,'A06.03','biofuel-production','','','');
insert ignore into ref_impacts values(37,'A06.04','abandonment of crop production','','','');
insert ignore into ref_impacts values(38,'A07','use of biocides, hormones and chemicals','','110','110');
insert ignore into ref_impacts values(39,'A08','Fertilisation','','120','120');
insert ignore into ref_impacts values(40,'A09','Irrigation','including (temporary) transition from dry to mesic or wet contitions due to irrigation','130','130');
insert ignore into ref_impacts values(41,'A10','Restructuring agricultural land holding','','150','150');
insert ignore into ref_impacts values(42,'A10.01','removal of hedges and copses or scrub','','151','151');
insert ignore into ref_impacts values(43,'A10.02','removal of stone walls and embankments','','','');
insert ignore into ref_impacts values(44,'A11','Agriculture activities not referred to above','','190pp','');
insert ignore into ref_impacts values(45,'B','Sylviculture, forestry','','160','160');
insert ignore into ref_impacts values(46,'B01','forest planting on open ground','increase in forest area, planting e.g. on grasland , heathland','161','161');
insert ignore into ref_impacts values(47,'B01.01','forest planting on open ground (native trees)','','','');
insert ignore into ref_impacts values(48,'B01.02','artificial planting on open ground (non-native trees)','increase in forest area','162','162');
insert ignore into ref_impacts values(49,'B02','Forest and Plantation management  & use','','','');
insert ignore into ref_impacts values(50,'B02.01','forest replanting','replanting on forest ground after clear-cutting','163','163');
insert ignore into ref_impacts values(51,'B02.01.01','forest replanting (native trees)','','','');
insert ignore into ref_impacts values(52,'B02.01.02','forest replanting (non native trees)','','','');
insert ignore into ref_impacts values(53,'B02.02','forestry clearance','clear-cutting, removal of all trees','164','164');
insert ignore into ref_impacts values(54,'B02.03','removal of forest undergrowth','','165','165');
insert ignore into ref_impacts values(55,'B02.04','removal of dead and dying trees','','166','166');
insert ignore into ref_impacts values(56,'B02.05','non- intensive timber production (leaving dead wood/ old trees untouched)','','','');
insert ignore into ref_impacts values(57,'B02.06','thinning of tree layer','','','');
insert ignore into ref_impacts values(58,'B03','forest exploitation without replanting or natural regrowth','decline of forest area','167','167');
insert ignore into ref_impacts values(59,'B04','use of biocides, hormones and chemicals (forestry)','','','');
insert ignore into ref_impacts values(60,'B05','use of fertilizers (forestry)','','','');
insert ignore into ref_impacts values(61,'B06','grazing in forests/ woodland','','','');
insert ignore into ref_impacts values(62,'B07','Forestry activities not referred to above','e.g. erosion due to forest clearing, fragmentation','190pp','');
insert ignore into ref_impacts values(63,'C','Mining, extraction of materials and energy production','','3 pp.','');
insert ignore into ref_impacts values(64,'C01','Mining and quarrying','','','');
insert ignore into ref_impacts values(65,'C01.01','Sand and gravel extraction','','300','300');
insert ignore into ref_impacts values(66,'C01.01.01','sand and gravel quarries','','301','301');
insert ignore into ref_impacts values(67,'C01.01.02','removal of beach materials','','302','302');
insert ignore into ref_impacts values(68,'C01.02','Loam and clay pits','','','');
insert ignore into ref_impacts values(69,'C01.03','Peat extraction','','310','310');
insert ignore into ref_impacts values(70,'C01.03.01','hand cutting of peat','','311','311');
insert ignore into ref_impacts values(71,'C01.03.02','mechanical removal of peat','','312','312');
insert ignore into ref_impacts values(72,'C01.04','Mines','','330','330');
insert ignore into ref_impacts values(73,'C01.04.01','open cast mining','','331','331');
insert ignore into ref_impacts values(74,'C01.04.02','underground mining','','','');
insert ignore into ref_impacts values(75,'C01.05','Salt works','','340','340');
insert ignore into ref_impacts values(76,'C01.05.01','abandonment of saltpans (salinas)','','','');
insert ignore into ref_impacts values(77,'C01.05.02','conversion of saltpans','e.g. for aquaculture or rice fields','','');
insert ignore into ref_impacts values(78,'C01.06','Geotechnical survey','','','');
insert ignore into ref_impacts values(79,'C01.07','Mining and extraction activities not referred to above','','390','390');
insert ignore into ref_impacts values(80,'C02','Exploration and extraction of oil or gas','','320','320');
insert ignore into ref_impacts values(81,'C02.01','exploration drilling','','','');
insert ignore into ref_impacts values(82,'C02.02','production drilling','','','');
insert ignore into ref_impacts values(83,'C02.03','jack-up drilling rig','','','');
insert ignore into ref_impacts values(84,'C02.04','semi-submersible rig','','','');
insert ignore into ref_impacts values(85,'C02.05','drill ship','','','');
insert ignore into ref_impacts values(86,'C03','Renewable abiotic energy use','','','');
insert ignore into ref_impacts values(87,'C03.01','geothermal power production','','','');
insert ignore into ref_impacts values(88,'C03.02','solar energy production','','','');
insert ignore into ref_impacts values(89,'C03.03','wind energy production','','','');
insert ignore into ref_impacts values(90,'C03.04','tidal energy production','','','');
insert ignore into ref_impacts values(91,'D','Transportation and service corridors','','5','5');
insert ignore into ref_impacts values(92,'D01','Roads, paths and railroads','','','');
insert ignore into ref_impacts values(93,'D01.01','paths, tracks, cycling tracks','includes non-paved forest roads','501','501');
insert ignore into ref_impacts values(94,'D01.02','roads, motorways','all paved/ tarred roads','502','502');
insert ignore into ref_impacts values(95,'D01.03','car parcs and parking areas','','','');
insert ignore into ref_impacts values(96,'D01.04','railway lines, TGV','','503','503');
insert ignore into ref_impacts values(97,'D01.05','bridge, viaduct','','507','507');
insert ignore into ref_impacts values(98,'D01.06','tunnel','','508','508');
insert ignore into ref_impacts values(99,'D02','Utility and service lines','','510','510');
insert ignore into ref_impacts values(100,'D02.01','electricity and phone lines','','511','511');
insert ignore into ref_impacts values(101,'D02.01.01','suspended electricity and phone lines','','','');
insert ignore into ref_impacts values(102,'D02.01.02','underground/submerged electricity and phone lines','','','');
insert ignore into ref_impacts values(103,'D02.02','pipe lines','','512','512');
insert ignore into ref_impacts values(104,'D02.03','communication masts and antennas','','','');
insert ignore into ref_impacts values(105,'D02.09','other forms of energy transport','','513','513');
insert ignore into ref_impacts values(106,'D03','shipping lanes, ports, marine constructions','WFD','','');
insert ignore into ref_impacts values(107,'D03.01','port areas','WFD','504','504');
insert ignore into ref_impacts values(108,'D03.01.01','slipways','','','');
insert ignore into ref_impacts values(109,'D03.01.02','piers / tourist harbours or recreational piers','','','');
insert ignore into ref_impacts values(110,'D03.01.03','fishing harbours','','','');
insert ignore into ref_impacts values(111,'D03.01.04','industrial ports','','','');
insert ignore into ref_impacts values(112,'D03.02','Shipping lanes','includes canals, WFD','520','520');
insert ignore into ref_impacts values(113,'D03.02.01','cargo lanes','creates acoustic disturbance to some cetaceans','','');
insert ignore into ref_impacts values(114,'D03.02.02','passenger ferry lanes (high speed)',' vessel collision with some cetaceans','','');
insert ignore into ref_impacts values(115,'D03.03','marine constructions','WFD','','');
insert ignore into ref_impacts values(116,'D04','airports, flightpaths','','','');
insert ignore into ref_impacts values(117,'D04.01','airport','','505','505');
insert ignore into ref_impacts values(118,'D04.02','aerodrome, heliport','','506','506');
insert ignore into ref_impacts values(119,'D04.03','flight paths','','','');
insert ignore into ref_impacts values(120,'D05','Improved access to site','','530','530');
insert ignore into ref_impacts values(121,'D06','Other forms of transportation and communication','','590','590');
insert ignore into ref_impacts values(122,'E','Urbanisation, residential and commercial development','','4','4');
insert ignore into ref_impacts values(123,'E01','Urbanised areas, human habitation','','400','400');
insert ignore into ref_impacts values(124,'E01.01','continuous urbanisation','','401','401');
insert ignore into ref_impacts values(125,'E01.02','discontinuous urbanisation','','402','402');
insert ignore into ref_impacts values(126,'E01.03','dispersed habitation','','403','403');
insert ignore into ref_impacts values(127,'E01.04','other patterns of habitation','','409','409');
insert ignore into ref_impacts values(128,'E02','Industrial or commercial areas','','410','410');
insert ignore into ref_impacts values(129,'E02.01','factory','','411','411');
insert ignore into ref_impacts values(130,'E02.02','industrial stockage','','412','412');
insert ignore into ref_impacts values(131,'E02.03','other industrial / commercial area','inlcuding shopping centres','419','419');
insert ignore into ref_impacts values(132,'E03','Discharges','','420','420');
insert ignore into ref_impacts values(133,'E03.01','disposal of household / recreational facility waste','','421','421');
insert ignore into ref_impacts values(134,'E03.02','disposal of industrial waste','','422','422');
insert ignore into ref_impacts values(135,'E03.03','disposal of inert materials','','423','423');
insert ignore into ref_impacts values(136,'E03.04','Other discharges','','424','424');
insert ignore into ref_impacts values(137,'E03.04.01','costal sand suppletion/ beach nourishment','WFD','','');
insert ignore into ref_impacts values(138,'E04','Structures, buildings in the landscape','','','');
insert ignore into ref_impacts values(139,'E04.01','Agricultural structures, buildings in the landscape','','430','430');
insert ignore into ref_impacts values(140,'E04.02','Military constructions and buildings in the landscape','without transportation e.g. airports see section D','','');
insert ignore into ref_impacts values(141,'E05','Storage of materials','','440','440');
insert ignore into ref_impacts values(142,'E06','Other urbanisation, industrial and similar activities','','490','490');
insert ignore into ref_impacts values(143,'E06.01','demolishment of buildings & human structures','includes bridges, walls..','','');
insert ignore into ref_impacts values(144,'E06.02','reconstruction, renovation of buildings','','','');
insert ignore into ref_impacts values(145,'F','Biological resource use other than agriculture & forestry','','2','2');
insert ignore into ref_impacts values(146,'F01','Marine and Freshwater Aquaculture','','200','200');
insert ignore into ref_impacts values(147,'F01.01','intensive fish farming, intensification','','','');
insert ignore into ref_impacts values(148,'F01.02','suspension culture','e.g. mussels, seaweed, fish','','');
insert ignore into ref_impacts values(149,'F01.03','bottom culture','e.g. shellfish','','');
insert ignore into ref_impacts values(150,'F02','Fishing and harvesting aquatic ressources','includes effects of bycatch/accidential catch in all subcategories','','');
insert ignore into ref_impacts values(151,'F02.01','Professional passive fishing','includes other fishing methods not listed in subcategories','210pp','');
insert ignore into ref_impacts values(152,'F02.01.01','potting','','211pp','');
insert ignore into ref_impacts values(153,'F02.01.02','netting','','213','213');
insert ignore into ref_impacts values(154,'F02.01.03','demersal longlining','','','');
insert ignore into ref_impacts values(155,'F02.01.04','pelagic longlining','','','');
insert ignore into ref_impacts values(156,'F02.02','Professional active fishing','','210pp','');
insert ignore into ref_impacts values(157,'F02.02.01','benthic or demersal trawling','','','');
insert ignore into ref_impacts values(158,'F02.02.02','pelagic trawling','drift-net fishing','212','212');
insert ignore into ref_impacts values(159,'F02.02.03','demersal seining','','','');
insert ignore into ref_impacts values(160,'F02.02.04','purse seining','','','');
insert ignore into ref_impacts values(161,'F02.02.05','benthic dredging','','','');
insert ignore into ref_impacts values(162,'F02.03','Leisure fishing','other than bait-fishing','220','220');
insert ignore into ref_impacts values(163,'F02.03.01','bait digging / collection','','221','221');
insert ignore into ref_impacts values(164,'F02.03.02','pole fishing','e.g. sturgeons','','');
insert ignore into ref_impacts values(165,'F02.03.03','spear-fishing','e.g. overfishing of Scyllarides','','');
insert ignore into ref_impacts values(166,'F03','Hunting and collection of wild animals (terrestrial)','','','');
insert ignore into ref_impacts values(167,'F03.01','Hunting','','230','230');
insert ignore into ref_impacts values(168,'F03.01.01','damage caused by game (excess population density)','','','');
insert ignore into ref_impacts values(169,'F03.02','Taking and removal of animals (terrestrial)','','240','240');
insert ignore into ref_impacts values(170,'F03.02.01','collection of animals (insects, reptiles, amphibians.....)','','241','241');
insert ignore into ref_impacts values(171,'F03.02.02','taking from nest (e.g. falcons)','','242','242');
insert ignore into ref_impacts values(172,'F03.02.03','trapping, poisoning, poaching','','243','243');
insert ignore into ref_impacts values(173,'F03.02.04','predator control','','','');
insert ignore into ref_impacts values(174,'F03.02.05','accidential capture','e.g. accidental death in fishing gear','','');
insert ignore into ref_impacts values(175,'F03.02.09','other forms of taking animals','','244','244');
insert ignore into ref_impacts values(176,'F04','Taking / Removal of terrestrial plants, general','','250','250');
insert ignore into ref_impacts values(177,'F04.01','pillaging of floristic stations','','251','251');
insert ignore into ref_impacts values(178,'F04.02','collection (fungi, lichen, berries etc.)','','','');
insert ignore into ref_impacts values(179,'F04.02.01','hand raking','','','');
insert ignore into ref_impacts values(180,'F04.02.02','hand collection','','','');
insert ignore into ref_impacts values(181,'F05','Illegal taking/ removal of marine fauna','','','');
insert ignore into ref_impacts values(182,'F05.01','dynamite','damages rocky substrates like reefs, disturbs marine mammals','','');
insert ignore into ref_impacts values(183,'F05.02','date mussel-fishing','damages rocky substrates and benthic communities','','');
insert ignore into ref_impacts values(184,'F05.03','poisons','damages coastal fish-fauna','','');
insert ignore into ref_impacts values(185,'F05.04','poaching','e.g. marine turtles','','');
insert ignore into ref_impacts values(186,'F05.05','shooting','e.g. marine mammals','','');
insert ignore into ref_impacts values(187,'F05.06','removal for collection purposes','e.g. marine invertebrates','','');
insert ignore into ref_impacts values(188,'F05.07','other (i.e. drift nets)','','','');
insert ignore into ref_impacts values(189,'F06','Hunting, fishing or collecting activities not referred to above','e.g. harvesting of shellfish','290','290');
insert ignore into ref_impacts values(190,'F06.01','game/ bird breeding station','','','');
insert ignore into ref_impacts values(191,'G','Human intrusions and disturbances','','6pp','');
insert ignore into ref_impacts values(192,'G01','Outdoor sports and leisure activities, recreational activities','','620','620');
insert ignore into ref_impacts values(193,'G01.01','nautical sports','','621','621');
insert ignore into ref_impacts values(194,'G01.01.01','motorized nautical sports','e.g. jet-skiing','','');
insert ignore into ref_impacts values(195,'G01.01.02','non-motorized nautical sports','e.g. wind-surfing','','');
insert ignore into ref_impacts values(196,'G01.02','walking, horseriding and non-motorised vehicles','','622','622');
insert ignore into ref_impacts values(197,'G01.03','motorised vehicles','','623','623');
insert ignore into ref_impacts values(198,'G01.03.01','regular motorized driving','standard vehicles & 4x4 on roads','','');
insert ignore into ref_impacts values(199,'G01.03.02','off-road motorized driving','','','');
insert ignore into ref_impacts values(200,'G01.04','mountaineering, rock climbing, speleology','','624','624');
insert ignore into ref_impacts values(201,'G01.04.01','mountaineering & rock climbing','','','');
insert ignore into ref_impacts values(202,'G01.04.02','speleology','','','');
insert ignore into ref_impacts values(203,'G01.04.03','recreational cave visits','terrestrial & marine','','');
insert ignore into ref_impacts values(204,'G01.05','gliding, delta plane, paragliding, ballooning','','625','625');
insert ignore into ref_impacts values(205,'G01.06','skiing, off-piste','','626','626');
insert ignore into ref_impacts values(206,'G01.07','scubadiving, snorkelling','e.g. disturbing monk seals and coastal nesting birds','','');
insert ignore into ref_impacts values(207,'G01.08','other outdoor sports and leisure activities','','629','629');
insert ignore into ref_impacts values(208,'G02','Sport and leisure structures','','600','600');
insert ignore into ref_impacts values(209,'G02.01','golf course','','601','601');
insert ignore into ref_impacts values(210,'G02.02','skiing complex','','602','602');
insert ignore into ref_impacts values(211,'G02.03','stadium','','603','603');
insert ignore into ref_impacts values(212,'G02.04','circuit, track','','604','604');
insert ignore into ref_impacts values(213,'G02.05','hippodrome','','605','605');
insert ignore into ref_impacts values(214,'G02.06','attraction park','','606','606');
insert ignore into ref_impacts values(215,'G02.07','sports pitch','','607','607');
insert ignore into ref_impacts values(216,'G02.08','camping and caravans','','608','608');
insert ignore into ref_impacts values(217,'G02.09','wildlife watching','e.g. bird watching, whale watching','','');
insert ignore into ref_impacts values(218,'G02.10','other sport / leisure complexes','','609','609');
insert ignore into ref_impacts values(219,'G03','Interpretative centres','','610','610');
insert ignore into ref_impacts values(220,'G04','Military use and civil unrest','','','');
insert ignore into ref_impacts values(221,'G04.01','Military manouvres','','730','730');
insert ignore into ref_impacts values(222,'G04.02','abandonment of military use','','','');
insert ignore into ref_impacts values(223,'G05','Other human intrusions and disturbances','','690 & 790','690');
insert ignore into ref_impacts values(224,'G05','Other human intrusions and disturbances','','','790');
insert ignore into ref_impacts values(225,'G05.01','Trampling, overuse','','720','720');
insert ignore into ref_impacts values(226,'G05.02','shallow surface abrasion/ mechanical damage to seabed surface','e.g. by contact with scubadivers/ snorkellers, incurred by three-dimensional organisms present on reefs','','');
insert ignore into ref_impacts values(227,'G05.03','penetration/ disturbance below surface of the seabed','e.g. by anchoring/ mooring on reefs,  in Posidonia meadows','','');
insert ignore into ref_impacts values(228,'G05.04','Vandalism','','740','740');
insert ignore into ref_impacts values(229,'G05.05','intensive maintenance of public parcs /cleaning of beaches','','','');
insert ignore into ref_impacts values(230,'G05.06','tree surgery, felling for public safety, removal of roadside trees','','','');
insert ignore into ref_impacts values(231,'G05.07','missing or wrongly directed conservation measures','','','');
insert ignore into ref_impacts values(232,'G05.08','closures of caves or galleries','','','');
insert ignore into ref_impacts values(233,'G05.09','fences, fencing','','','');
insert ignore into ref_impacts values(234,'G05.10','overflying with aircrafts (agricultural)','','','');
insert ignore into ref_impacts values(235,'G05.11','death or injury by collision','e.g. marine mammals','','');
insert ignore into ref_impacts values(236,'H','Pollution','','700','700');
insert ignore into ref_impacts values(237,'H01','Pollution to surface waters (limnic & terrestrial, marine & brackish)','WFD','701pp','');
insert ignore into ref_impacts values(238,'H01.01','pollution to surface waters by industrial plants','WFD- differs further into UWWT, IPPC and other plants','','');
insert ignore into ref_impacts values(239,'H01.02','pollution to surface waters by storm overflows','WFD - WFD lists storm overflows as point and diffuse source','','');
insert ignore into ref_impacts values(240,'H01.03','other point source pollution to surface water','WFD','','');
insert ignore into ref_impacts values(241,'H01.04','diffuse pollution to surface waters via strom overlows or urban run-off','WFD','','');
insert ignore into ref_impacts values(242,'H01.05','diffuse pollution to surface waters due to agricultural and forestry activities','WFD (WFD does not include forestry effluents)','','');
insert ignore into ref_impacts values(243,'H01.06','diffuse pollution to surface waters due to transport and infrastructure without connection to canalization/sweepers','WFD','','');
insert ignore into ref_impacts values(244,'H01.07','diffuse pollution to surface waters due to abandoned industrial sites','WFD','','');
insert ignore into ref_impacts values(245,'H01.08','diffuse pollution to surface waters due to household sewage and waste waters','WFD: "releases from facilities for the storage and/or treatment of domestic effluent in areas without sewerage networks"','','');
insert ignore into ref_impacts values(246,'H01.09','diffuse pollution to surface waters due to other sources not listed','WFD','','');
insert ignore into ref_impacts values(247,'H02','Pollution to groundwater (point sources and diffuse sources)','WFD','701pp','');
insert ignore into ref_impacts values(248,'H02.01','groundwater pollution by leakages from contaminated sites','WFD','','');
insert ignore into ref_impacts values(249,'H02.02','groundwater pollution by leakages from waste disposal sites','WFD','','');
insert ignore into ref_impacts values(250,'H02.03','groundwater pollution associated with oil industry infrastructure','WFD','','');
insert ignore into ref_impacts values(251,'H02.04','groundwater pollution by mine water discharges','WFD','','');
insert ignore into ref_impacts values(252,'H02.05','groundwater pollution by discharge to ground such as disposal of contaminated water to soakaways','WFD','','');
insert ignore into ref_impacts values(253,'H02.06','diffuse groundwater pollution due to agricultural and forestry activities','WFD (WFD does not include forestry effluents)','','');
insert ignore into ref_impacts values(254,'H02.07','diffuse groundwater pollution due to non-sewered population','WFD','','');
insert ignore into ref_impacts values(255,'H02.08','diffuse groundwater pollution due to urban land use','WFD','','');
insert ignore into ref_impacts values(256,'H03','Marine water pollution','specific to marine and brackish waters','','');
insert ignore into ref_impacts values(257,'H03.01','oil spills in the sea','','','');
insert ignore into ref_impacts values(258,'H03.02','toxic chemical discharge from material dumped at sea','harming e.g. marine mammals, birds, reptiles','','');
insert ignore into ref_impacts values(259,'H03.02.01','non-synthetic compound contamination','incl. heavy metals, hydrocarbons, produced water','','');
insert ignore into ref_impacts values(260,'H03.02.02','synthetic compound contamination','incl. pesticides, antifoulants, pharmaceuticals','','');
insert ignore into ref_impacts values(261,'H03.02.03','radionucleide contamination','','','');
insert ignore into ref_impacts values(262,'H03.02.04','introduction of other substances (e.g. liquid, gas)','','','');
insert ignore into ref_impacts values(263,'H03.03','marine macro-pollution (i.e. plastic bags, styrofoam)','e.g. accidental ingestion by marine turtles, mammals, marine birds','','');
insert ignore into ref_impacts values(264,'H04','Air pollution, air-borne pollutants','','702','702');
insert ignore into ref_impacts values(265,'H04.01','Acid rain','','','');
insert ignore into ref_impacts values(266,'H04.02','Nitrogen-input','','','');
insert ignore into ref_impacts values(267,'H04.03','other air pollution','','','');
insert ignore into ref_impacts values(268,'H05','Soil pollution and solid waste (excluding discharges)','','703','703');
insert ignore into ref_impacts values(269,'H05.01','garbage and solid waste','','','');
insert ignore into ref_impacts values(270,'H06','excess energy','incl.  geophysical surveys, if not under H06.05','','');
insert ignore into ref_impacts values(271,'H06.01','Noise nuisance, noise pollution','','710','710');
insert ignore into ref_impacts values(272,'H06.01.01','point source or irregular noise pollution','','','');
insert ignore into ref_impacts values(273,'H06.01.02','diffuse or permanent noise pollution','','','');
insert ignore into ref_impacts values(274,'H06.02','Light pollution','','','');
insert ignore into ref_impacts values(275,'H06.03','Thermal heating of water bodies','limnic,, brackish or marine water bodies','','');
insert ignore into ref_impacts values(276,'H06.04','Electromagnetic changes','e.g. in marine environment','','');
insert ignore into ref_impacts values(277,'H06.05','Seismic exploration, explosions','','','');
insert ignore into ref_impacts values(278,'H07','Other forms of pollution','','709','709');
insert ignore into ref_impacts values(279,'I','Invasive, other problematic species and genes','','','');
insert ignore into ref_impacts values(280,'I01','invasive non-native species','plant & animal species','954,966','954');
insert ignore into ref_impacts values(281,'I01','invasive non-native species','plant & animal species','','966');
insert ignore into ref_impacts values(282,'I02','problematic native species','','','');
insert ignore into ref_impacts values(283,'I03','introduced genetic material, GMO','','','');
insert ignore into ref_impacts values(284,'I03.01','genetic pollution (animals)','','964','964');
insert ignore into ref_impacts values(285,'I03.02','genetic pollution (plants)','','974','974');
insert ignore into ref_impacts values(286,'J','Natural System modifications','','','');
insert ignore into ref_impacts values(287,'J01','fire and fire suppression','','180','180');
insert ignore into ref_impacts values(288,'J01.01','burning down','activily burning down existing vegetation','','');
insert ignore into ref_impacts values(289,'J01.02','supression of natural fires','','','');
insert ignore into ref_impacts values(290,'J01.03','lack of fires','','','');
insert ignore into ref_impacts values(291,'J02','human induced changes in hydraulic conditions','','8, 890','8');
insert ignore into ref_impacts values(292,'J02','human induced changes in hydraulic conditions','','','890');
insert ignore into ref_impacts values(293,'J02.01','Landfill, land reclamation and drying out, general','','800','800');
insert ignore into ref_impacts values(294,'J02.01.01','polderisation','WFD','801','801');
insert ignore into ref_impacts values(295,'J02.01.02','reclamation of land from sea, estuary or marsh','WFD','802','802');
insert ignore into ref_impacts values(296,'J02.01.03','infilling of ditches, dykes, ponds, pools, marshes or pits','WFD','803','803');
insert ignore into ref_impacts values(297,'J02.01.04','recultivation of mining areas','','','');
insert ignore into ref_impacts values(298,'J02.02','Removal of sediments (mud...)','','820','820');
insert ignore into ref_impacts values(299,'J02.02.01','dredging/ removal of limnic sediments','WFD "river management: dredging"','','');
insert ignore into ref_impacts values(300,'J02.02.02','estuarine and coastal dredging','WFD','','');
insert ignore into ref_impacts values(301,'J02.03','Canalisation & water deviation','','830','830');
insert ignore into ref_impacts values(302,'J02.03.01','large scale water deviation','','','');
insert ignore into ref_impacts values(303,'J02.03.02','canalisation','','','');
insert ignore into ref_impacts values(304,'J02.04','Flooding modifications','','840','840');
insert ignore into ref_impacts values(305,'J02.04.01','flooding','','','');
insert ignore into ref_impacts values(306,'J02.04.02','lack of  flooding','','','');
insert ignore into ref_impacts values(307,'J02.05','Modification of hydrographic functioning, general','','850','850');
insert ignore into ref_impacts values(308,'J02.05.01','modification of water flow (tidal & marine currents)','','851','851');
insert ignore into ref_impacts values(309,'J02.05.02','modifying structures of inland water courses','WFD: land sealing in riparian zones and floodplains','852','852');
insert ignore into ref_impacts values(310,'J02.05.03','mofification of standing water bodies','e.g. creation of fish ponds','','');
insert ignore into ref_impacts values(311,'J02.05.04','reservoirs','','','');
insert ignore into ref_impacts values(312,'J02.05.05','small hydropower projects, weirs','supply for single buildings, mills','','');
insert ignore into ref_impacts values(313,'J02.05.06','wave exposure changes','','','');
insert ignore into ref_impacts values(314,'J02.06','Water abstractions from surface waters','WFD; exploitation of water ressources','853pp,810pp','');
insert ignore into ref_impacts values(315,'J02.06.01','surface water abstractions for agriculture','WFD, e.g. irrigation','','');
insert ignore into ref_impacts values(316,'J02.06.02','surface water abstractions for public water supply','WFD','','');
insert ignore into ref_impacts values(317,'J02.06.03','surface water abstractions by manufacturing industry','WFD','','');
insert ignore into ref_impacts values(318,'J02.06.04','surface water abstractions for the production of electricity (cooling)','WFD','','');
insert ignore into ref_impacts values(319,'J02.06.05','surface water abstractions by fish farms','WFD','','');
insert ignore into ref_impacts values(320,'J02.06.06','surface water abstractions by hydro-energy','WFD, not for cooling','','');
insert ignore into ref_impacts values(321,'J02.06.07','surface water abstractions by quarries/ open cast (coal) sites','WFD','','');
insert ignore into ref_impacts values(322,'J02.06.08','surface water abstractions for navigation','WFD, e.g. for suppying canals','','');
insert ignore into ref_impacts values(323,'J02.06.09','surface water abstractions for water transfer','WFD','','');
insert ignore into ref_impacts values(324,'J02.06.10','other major surface water abstractions','WFD','','');
insert ignore into ref_impacts values(325,'J02.07','Water abstractions from groundwater','WFD, drainage, lowering of groundwater table','853pp,810pp','');
insert ignore into ref_impacts values(326,'J02.07.01','groundwater abstractions for agriculture','WFD','','');
insert ignore into ref_impacts values(327,'J02.07.02','groundwater abstractions for  public water supply','WFD','','');
insert ignore into ref_impacts values(328,'J02.07.03','groundwater abstractions by industry','WFD; WFD differetiates as subcategories IPPC, non IPPC industries','','');
insert ignore into ref_impacts values(329,'J02.07.04','groundwater abstractions by quarries/open cast (coal)sites','WFD','','');
insert ignore into ref_impacts values(330,'J02.07.05','other major groundwater abstractions from groundwater for agriculture','WFD','','');
insert ignore into ref_impacts values(331,'J02.08','Raising the groundwater table /artificial recharge of goundwater','WFD: artificial recharge of groundwater','','');
insert ignore into ref_impacts values(332,'J02.08.01','discharges to groundwater for artificial recharge purposes','WFD','','');
insert ignore into ref_impacts values(333,'J02.08.02','returns of groundwater to GWB from which it was abstracted','WFD: e.g. fro sand & gravel washing','','');
insert ignore into ref_impacts values(334,'J02.08.03','mine water rebound','WFD','','');
insert ignore into ref_impacts values(335,'J02.08.04','other major groundwater recharge','WFD','','');
insert ignore into ref_impacts values(336,'J02.09.','Saltwater intrusion of groundwater','WFD','','');
insert ignore into ref_impacts values(337,'J02.09.01','saltwater intrusion','WFD','','');
insert ignore into ref_impacts values(338,'J02.09.02','other intrusion','WFD','','');
insert ignore into ref_impacts values(339,'J02.10','management of aquatic and bank vegetation for drainage purposes','','811','811');
insert ignore into ref_impacts values(340,'J02.11','Siltation rate changes, dumping, depositing of dredged deposits','','860','860');
insert ignore into ref_impacts values(341,'J02.11.01','Dumping, depositing of dredged deposits','','','');
insert ignore into ref_impacts values(342,'J02.11.02','Other siltation rate changes','','','');
insert ignore into ref_impacts values(343,'J02.12','Dykes, embankments, artificial beaches, general','WFD','870','870');
insert ignore into ref_impacts values(344,'J02.12.01','sea defense or coast protection works, tidal barrages','WFD: including tidal barrages for flood defense and power generation','871','871');
insert ignore into ref_impacts values(345,'J02.12.02','dykes and flooding defense in inland water systems','WFD','','');
insert ignore into ref_impacts values(346,'J02.13','Abandonment of management of water bodies','','','');
insert ignore into ref_impacts values(347,'J02.14','Altered water quality due anthropogenic changes in salinity','marine and coastal waters, e.g. algal growth on reefs','','');
insert ignore into ref_impacts values(348,'J02.15','Other human induced changes in hydraulic conditions','','','');
insert ignore into ref_impacts values(349,'J03','Other ecosystem modifications','','','');
insert ignore into ref_impacts values(350,'J03.01','reduction or loss of specific habitat features','','','');
insert ignore into ref_impacts values(351,'J03.01.01','reduction of prey availability (inluding carcasses)','e.g. for birds of prey','','');
insert ignore into ref_impacts values(352,'J03.02','anthropogenic reduction of habitat connectivity','fragmentation','','');
insert ignore into ref_impacts values(353,'J03.02.01','reduction in migration/ migration barriers','','','');
insert ignore into ref_impacts values(354,'J03.02.02','reduction in dispersal','','','');
insert ignore into ref_impacts values(355,'J03.02.03','reduction in genetic exchange','','','');
insert ignore into ref_impacts values(356,'J03.03','reduction, lack or prevention of erosion','','','');
insert ignore into ref_impacts values(357,'J03.04','applied (industrial) destructive research','e.g. "marine scientific research" in a broad sense','','');
insert ignore into ref_impacts values(358,'K','Natural biotic and abiotic processes (without catastrophes)','','9 pp','');
insert ignore into ref_impacts values(359,'K01','abiotic (slow) natural processes','','','');
insert ignore into ref_impacts values(360,'K01.01','Erosion','','900','900');
insert ignore into ref_impacts values(361,'K01.02','Silting up','','910','910');
insert ignore into ref_impacts values(362,'K01.03','Drying out','','920','920');
insert ignore into ref_impacts values(363,'K01.04','Submersion','','930','930');
insert ignore into ref_impacts values(364,'K01.05','Soil salinization','','','');
insert ignore into ref_impacts values(365,'K02','Biocenotic evolution, succession','includes enlargement of scrub vegetation area','950','950');
insert ignore into ref_impacts values(366,'K02.01','species composition change (succession)','','','');
insert ignore into ref_impacts values(367,'K02.02','accumulation of organic material','','951','951');
insert ignore into ref_impacts values(368,'K02.03','eutrophication (natural)','','952','952');
insert ignore into ref_impacts values(369,'K02.04','acidification (natural)','','953','953');
insert ignore into ref_impacts values(370,'K03','Interspecific faunal relations','','960','960');
insert ignore into ref_impacts values(371,'K03.01','competition (fauna)','example: gull/tern','961','961');
insert ignore into ref_impacts values(372,'K03.02','parasitism (fauna)','','962','962');
insert ignore into ref_impacts values(373,'K03.03','introduction of disease (microbial pathogens)','','963','963');
insert ignore into ref_impacts values(374,'K03.04','predation','','965','965');
insert ignore into ref_impacts values(375,'K03.05','antagonism arising from introduction of species','','966','966');
insert ignore into ref_impacts values(376,'K03.06','antagonism with domestic animals','','967','967');
insert ignore into ref_impacts values(377,'K03.07','other forms of interspecific faunal competition','','969','969');
insert ignore into ref_impacts values(378,'K04','Interspecific floral relations','','970','970');
insert ignore into ref_impacts values(379,'K04.01','competition (flora)','','971','971');
insert ignore into ref_impacts values(380,'K04.02','parasitism (flora)','','972','972');
insert ignore into ref_impacts values(381,'K04.03','introduction of disease (microbial pathogens)','','973','973');
insert ignore into ref_impacts values(382,'K04.04','lack of pollinating agents','','975','975');
insert ignore into ref_impacts values(383,'K04.05','damage by herbivores (including game species)','','976','976');
insert ignore into ref_impacts values(384,'K05','reduced fecundity/ genetic depression','e.g. beause of too low population numbers','979','979');
insert ignore into ref_impacts values(385,'K05.01','reduced fecundity/ genetic depression in animals (inbreeding)','','990','990');
insert ignore into ref_impacts values(386,'K05.02','reduced fecundity/ genetic depression in plants (incl. endogamy)','','','');
insert ignore into ref_impacts values(387,'K06','other forms or mixed forms of interspecific floral competition','','','');
insert ignore into ref_impacts values(388,'L','Geological events, natural catastrophes','','940','940');
insert ignore into ref_impacts values(389,'L01','volcanic activity','','945','945');
insert ignore into ref_impacts values(390,'L02','tidal wave, tsunamis','','947','947');
insert ignore into ref_impacts values(391,'L03','earthquake','','946','946');
insert ignore into ref_impacts values(392,'L04','avalanche','','942','942');
insert ignore into ref_impacts values(393,'L05','collapse of terrain, landslide','','943pp','');
insert ignore into ref_impacts values(394,'L06','undergound collapses','','943pp','');
insert ignore into ref_impacts values(395,'L07','storm, cyclone','','944','944');
insert ignore into ref_impacts values(396,'L08','inundation (natural processes)','','941','941');
insert ignore into ref_impacts values(397,'L09','fire (natural)','','948','948');
insert ignore into ref_impacts values(398,'L10','other natural catastrophes','','949','949');
insert ignore into ref_impacts values(399,'M','Climate change','','','');
insert ignore into ref_impacts values(400,'M01','Changes in abiotic conditions','','','');
insert ignore into ref_impacts values(401,'M01.01','temperature changes (e.g. rise of temperature & extremes)','','','');
insert ignore into ref_impacts values(402,'M01.02','droughts and less precipitations','','','');
insert ignore into ref_impacts values(403,'M01.03','flooding and rising precipitations','','','');
insert ignore into ref_impacts values(404,'M01.04','pH-changes','','','');
insert ignore into ref_impacts values(405,'M01.05','water flow changes (limnic, tidal and oceanic)','','','');
insert ignore into ref_impacts values(406,'M01.06','wave exposure changes','','','');
insert ignore into ref_impacts values(407,'M01.07','sea-level changes','','','');
insert ignore into ref_impacts values(408,'M02','Changes in biotic conditions','','','');
insert ignore into ref_impacts values(409,'M02.01','habitat shifting and alteration','','','');
insert ignore into ref_impacts values(410,'M02.02','desynchronisation of processes','','','');
insert ignore into ref_impacts values(411,'M02.03','decline or extinction of species','','','');
insert ignore into ref_impacts values(412,'M02.04','migration of species (natural newcomers)','','','');
insert ignore into ref_impacts values(413,'X','No threats or pressures','','','');
insert ignore into ref_impacts values(414,'XO','Threats and pressures from outside the Member State','','','');
insert ignore into ref_impacts values(415,'XE','Threats and pressures from outside the EU territory','','','');
insert ignore into ref_impacts values(416,'U','Unknown threat or pressure','','','');
commit;