INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6500,'A471', 'Periparus ater cypriotes', 'Parus ater cypriotes');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6510,'A473', 'Periparus ater', 'Parus ater');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6520,'A474', 'Acanthis flammea', 'Carduelis flammea flammea, Carduelis flammea');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6530,'A475', 'Alaudala rufescens', 'Calandrella rufescens');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6540,'A476', 'Linaria cannabina', 'Carduelis cannabina');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6550,'A477', 'Linaria flavirostris', 'Carduelis flavirostris');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6560,'A478', 'Spinus spinus', 'Carduelis spinus');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6570,'A479', 'Cecropis daurica', 'Hirundo daurica');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6580,'A480', 'Cyanecula svecica', 'Luscinia svecica');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6590,'A481', 'Cyanopica cooki', 'Cyanopica cyana, Cyanopica cyanus');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6600,'A483', 'Cyanistes caeruleus', 'Parus caeruleus');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6610,'A484', 'Cyanistes teneriffae', 'Parus caeruleus');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6620,'A485', 'Fringilla polatzeki', 'Fringilla teydea polatzeki');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6630,'A486', 'Fringilla teydea', 'Fringilla teydea teydea');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6640,'A487', 'Iduna pallida', 'Hippolais pallida s. str.');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6650,'A488', 'Iduna opaca', 'Hippolais opaca');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6660,'A490', 'Poecile cinctus', 'Parus cinctus');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6670,'A491', 'Poecile lugubris', 'Parus lugubris');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6680,'A492', 'Poecile montanus', 'Parus montanus');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6690,'A493', 'Poecile palustris', 'Parus palustris');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6700,'A494', 'Pastor roseus', 'Sturnus roseus');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6710,'A496', 'Lanius meridionalis', 'Lanius excubitor meridionalis');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6720,'A497', 'Lophophanes cristatus', 'Parus cristatus');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6730,'A498', 'Phylloscopus orientalis', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6740,'A499', 'Phylloscopus bonelli', 'Phylloscopus bonelli');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6750,'A500', 'Sylvia sarda', 'Sylvia sarda');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6760,'A569', 'Sylvia balearica', 'Sylvia sarda balearica');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6770,'A570', 'Sylvia hortensis', 'Sylvia hortensis');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6780,'A571', 'Sylvia crassirostris', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6790,'A572', 'Phylloscopus collybita', 'Phylloscopus collybita');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6800,'A573', 'Phylloscopus trochiloides', 'Phylloscopus trochiloides');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6810,'A574', 'Sylvia curruca', 'Sylvia curruca s. str.');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6820,'A693', 'Puffinus mauretanicus', 'Puffinus puffinus mauretanicus');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6830,'A701', 'Anser fabalis fabalis', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6840,'A702', 'Anser fabalis rossicus', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6850,'A707', 'Aquila fasciata', 'Aquila fasciatus, Hieraaetus fasciatus');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6860,'A711', 'Lagopus lagopus scotica', 'Lagopus lagopus scoticus');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6870,'A712', 'Lagopus muta pyrenaica', 'Lagopus mutus pyrenaicus');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6880,'A713', 'Lagopus muta helvetica', 'Lagopus mutus helveticus');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6890,'A716', 'Francolinus francolinus francolinus', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6900,'A717', 'Turnix sylvaticus', 'Turnix sylvatica');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6910,'A722', 'Porphyrio porphyrio porphyrio', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6920,'A727', 'Eudromias morinellus', 'Charadrius morinellus');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6930,'A728', 'Vanellus spinosus', 'Hoplopterus spinosus');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6940,'A730', 'Numenius arquata orientalis', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6950,'A734', 'Chlidonias hybrida', 'Chlidonias hybridus');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6960,'A736', 'Bubo scandiacus', 'Nyctea scandiaca, Bubo scandiaca');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6970,'A738', 'Delichon urbicum', 'Delichon urbica');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6980,'A747', 'Cygnus atratus', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (6990,'A749', 'Aix sponsa', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7000,'A751', 'Cairina moschata', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7010,'A752', 'Colinus virginianus', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7020,'A753', 'Francolinus francolinus asiae', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7030,'A755', 'Chrysolophus amherstiae', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7040,'A756', 'Pavo cristatus', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7050,'A757', 'Numida meleagris', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7060,'A759', 'Porphyrio porphyrio poliocephalus', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7070,'A760', 'Psittacula krameri', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7080,'A762', 'Leiothrix lutea', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7090,'A763', 'Paradoxornis webbianus', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7100,'A764', 'Amandava amandava', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7110,'A767', 'Mergellus albellus', 'Mergus albellus');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7120,'A768', 'Numenius arquata arquata', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7130,'A773', 'Ardea alba', 'Casmerodius albus,  Egretta alba');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7140,'A798', 'Larus armenicus', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7150,'A800', 'Larus ichthyaetus', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7160,'A839', 'Lagopus muta', 'Lagopus mutus');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7170,'A844', 'Anser canagicus', 'Chen canagica');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7180,'A845', 'Anser indicus', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7190,'A846', 'Buteo jamaicensis', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7200,'A847', 'Parabuteo unicinctus', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7210,'A848', 'Agapornis roseicollis', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7220,'A850', 'Calonectris diomedea', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7230,'A851', 'Calonectris borealis', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7240,'A852', 'Ardenna gravis', 'Puffinus gravis');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7250,'A853', 'Ardenna grisea', 'Puffinus griseus');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7260,'A854', 'Hydrobates leucorhous', 'Oceanodroma leucorhoa');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7270,'A855', 'Mareca penelope', 'Anas penelope');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7280,'A856', 'Spatula querquedula', 'Anas querquedula');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7290,'A857', 'Spatula clypeata', 'Anas clypeata');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7300,'A858', 'Clanga pomarina', 'Aquila pomarina');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7310,'A859', 'Clanga clanga', 'Aquila clanga');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7320,'A860', 'Calidris falcinellus', 'Limicola falcinellus');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7330,'A861', 'Calidris pugnax', 'Philomachus pugnax');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7340,'A862', 'Hydrocoloeus minutus', 'Larus minutus');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7350,'A863', 'Thalasseus sandvicensis', 'Sterna sandvicensis');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7360,'A866', 'Picus viridis', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7370,'A867', 'Picus sharpei', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7380,'A868', 'Leiopicus medius', 'Dendrocopos medius');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7390,'A869', 'Dryobates minor', 'Dendrocopos minor');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7400,'A872', 'Pterodroma deserta', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7410,'A874', 'Hydrobates castro', 'Oceanodroma castro');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7420,'A875', 'Microcarbo pygmaeus', 'Phalacrocorax pygmeus');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7430,'A876', 'Lyrurus tetrix tetrix', 'Tetrao tetrix tetrix');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7440,'A877', 'Lyrurus tetrix britannicus', 'Tetrao tetrix britannicus');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7450,'A880', 'Puffinus lherminieri', 'Puffinus assimilis baroli');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7460,'A882', 'Onychoprion fuscatus', 'Sterna fuscata');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7470,'A883', 'Thalasseus bengalensis', 'Sterna bengalensis');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7480,'A884', 'Hydrobates monteiroi', 'Oceanodroma monteiroi');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7490,'A885', 'Sternula albifrons', 'Sterna albifrons');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7500,'A889', 'Mareca strepera', 'Anas strepera');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7510,'A890', 'Larus argentatus argentatus', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7520,'A892', 'Zapornia parva', 'Porzana parva');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7530,'A893', 'Zapornia pusilla', 'Porzana pusilla');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7540,'A894', 'Hydroprogne caspia', 'Sterna caspia');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7550,'A895', 'Larus argentatus argenteus', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7560,'A896', 'Pternistis erckelii', 'Francolinus erckelii');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7570,'A897', 'Spilopelia senegalensis', 'Streptopelia senegalensis');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7580,'A900', 'Melanitta nigra', 'Melanitta nigra nigra');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7590,'A907', 'Sylvia subalpina', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7600,'A909', 'Lyrurus tetrix', 'Tetrao tetrix');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7610,'A743', 'Corvus corone corone', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7620,'A689', 'Gavia arctica arctica', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7630,'A691', 'Podiceps cristatus cristatus', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7640,'A690', 'Tachybaptus ruficollis ruficollis', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7650,'A692', 'Podiceps nigricollis nigricollis', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7660,'A698', 'Casmerodius albus albus', 'Casmerodius albus,  Egretta alba');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7670,'A699', 'Ardea cinerea cinerea', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7680,'A703', 'Anas strepera strepera', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7690,'A704', 'Anas crecca crecca', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7700,'A705', 'Anas platyrhynchos platyrhynchos', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7710,'A708', 'Falco peregrinus peregrinus', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7720,'A718', 'Rallus aquaticus aquaticus', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7730,'A719', 'Porzana parva parva', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7740,'A720', 'Porzana pusilla intermedia', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7750,'A721', 'Gallinula chloropus chloropus', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7760,'A723', 'Fulica atra atra', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7770,'A726', 'Charadrius dubius curonicus', '');
INSERT IGNORE INTO ref_birds(ref_birds_id, ref_birds_code, ref_birds_name, ref_birds_alt_scientific_name) VALUES (7780,'A732', 'Sterna caspia caspia', '');

DELETE FROM ref_birds WHERE ref_birds_code = 'A748';
DELETE FROM ref_birds WHERE ref_birds_code = 'A750';
DELETE FROM ref_birds WHERE ref_birds_code = 'A758';
DELETE FROM ref_birds WHERE ref_birds_code = 'A761';
DELETE FROM ref_birds WHERE ref_birds_code = 'A765';
DELETE FROM ref_birds WHERE ref_birds_code = 'A011';
DELETE FROM ref_birds WHERE ref_birds_code = 'A012';
DELETE FROM ref_birds WHERE ref_birds_code = 'A015';
DELETE FROM ref_birds WHERE ref_birds_code = 'A027';
DELETE FROM ref_birds WHERE ref_birds_code = 'A033';
DELETE FROM ref_birds WHERE ref_birds_code = 'A050';
DELETE FROM ref_birds WHERE ref_birds_code = 'A051';
DELETE FROM ref_birds WHERE ref_birds_code = 'A055';
DELETE FROM ref_birds WHERE ref_birds_code = 'A056';
DELETE FROM ref_birds WHERE ref_birds_code = 'A068';
DELETE FROM ref_birds WHERE ref_birds_code = 'A089';
DELETE FROM ref_birds WHERE ref_birds_code = 'A090';
DELETE FROM ref_birds WHERE ref_birds_code = 'A093';
DELETE FROM ref_birds WHERE ref_birds_code = 'A106';
DELETE FROM ref_birds WHERE ref_birds_code = 'A107';
DELETE FROM ref_birds WHERE ref_birds_code = 'A117';
DELETE FROM ref_birds WHERE ref_birds_code = 'A120';
DELETE FROM ref_birds WHERE ref_birds_code = 'A121';
DELETE FROM ref_birds WHERE ref_birds_code = 'A139';
DELETE FROM ref_birds WHERE ref_birds_code = 'A150';
DELETE FROM ref_birds WHERE ref_birds_code = 'A151';
DELETE FROM ref_birds WHERE ref_birds_code = 'A177';
DELETE FROM ref_birds WHERE ref_birds_code = 'A190';
DELETE FROM ref_birds WHERE ref_birds_code = 'A191';
DELETE FROM ref_birds WHERE ref_birds_code = 'A195';
DELETE FROM ref_birds WHERE ref_birds_code = 'A196';
DELETE FROM ref_birds WHERE ref_birds_code = 'A216';
DELETE FROM ref_birds WHERE ref_birds_code = 'A238';
DELETE FROM ref_birds WHERE ref_birds_code = 'A240';
DELETE FROM ref_birds WHERE ref_birds_code = 'A252';
DELETE FROM ref_birds WHERE ref_birds_code = 'A253';
DELETE FROM ref_birds WHERE ref_birds_code = 'A254';
DELETE FROM ref_birds WHERE ref_birds_code = 'A272';
DELETE FROM ref_birds WHERE ref_birds_code = 'A325';
DELETE FROM ref_birds WHERE ref_birds_code = 'A326';
DELETE FROM ref_birds WHERE ref_birds_code = 'A327';
DELETE FROM ref_birds WHERE ref_birds_code = 'A328';
DELETE FROM ref_birds WHERE ref_birds_code = 'A329';
DELETE FROM ref_birds WHERE ref_birds_code = 'A353';
DELETE FROM ref_birds WHERE ref_birds_code = 'A365';
DELETE FROM ref_birds WHERE ref_birds_code = 'A366';
DELETE FROM ref_birds WHERE ref_birds_code = 'A367';
DELETE FROM ref_birds WHERE ref_birds_code = 'A368';
DELETE FROM ref_birds WHERE ref_birds_code = 'A384';
DELETE FROM ref_birds WHERE ref_birds_code = 'A390';
DELETE FROM ref_birds WHERE ref_birds_code = 'A393';
DELETE FROM ref_birds WHERE ref_birds_code = 'A407';
DELETE FROM ref_birds WHERE ref_birds_code = 'A408';
DELETE FROM ref_birds WHERE ref_birds_code = 'A409';
DELETE FROM ref_birds WHERE ref_birds_code = 'A410';
DELETE FROM ref_birds WHERE ref_birds_code = 'A418';
DELETE FROM ref_birds WHERE ref_birds_code = 'A431';
DELETE FROM ref_birds WHERE ref_birds_code = 'A436';
DELETE FROM ref_birds WHERE ref_birds_code = 'A443';
DELETE FROM ref_birds WHERE ref_birds_code = 'A454';
DELETE FROM ref_birds WHERE ref_birds_code = 'A462';
DELETE FROM ref_birds WHERE ref_birds_code = 'A470';
DELETE FROM ref_birds WHERE ref_birds_code = 'A501';
DELETE FROM ref_birds WHERE ref_birds_code = 'A503';
DELETE FROM ref_birds WHERE ref_birds_code = 'A507';
DELETE FROM ref_birds WHERE ref_birds_code = 'A508';
DELETE FROM ref_birds WHERE ref_birds_code = 'A510';
DELETE FROM ref_birds WHERE ref_birds_code = 'A517';
DELETE FROM ref_birds WHERE ref_birds_code = 'A518';
DELETE FROM ref_birds WHERE ref_birds_code = 'A520';
DELETE FROM ref_birds WHERE ref_birds_code = 'A521';
DELETE FROM ref_birds WHERE ref_birds_code = 'A524';
DELETE FROM ref_birds WHERE ref_birds_code = 'A526';
DELETE FROM ref_birds WHERE ref_birds_code = 'A527';
DELETE FROM ref_birds WHERE ref_birds_code = 'A528';
DELETE FROM ref_birds WHERE ref_birds_code = 'A529';
DELETE FROM ref_birds WHERE ref_birds_code = 'A531';
DELETE FROM ref_birds WHERE ref_birds_code = 'A535';
DELETE FROM ref_birds WHERE ref_birds_code = 'A537';
DELETE FROM ref_birds WHERE ref_birds_code = 'A538';
DELETE FROM ref_birds WHERE ref_birds_code = 'A539';
DELETE FROM ref_birds WHERE ref_birds_code = 'A543';
DELETE FROM ref_birds WHERE ref_birds_code = 'A546';
DELETE FROM ref_birds WHERE ref_birds_code = 'A547';
DELETE FROM ref_birds WHERE ref_birds_code = 'A549';
DELETE FROM ref_birds WHERE ref_birds_code = 'A550';
DELETE FROM ref_birds WHERE ref_birds_code = 'A551';
DELETE FROM ref_birds WHERE ref_birds_code = 'A552';
DELETE FROM ref_birds WHERE ref_birds_code = 'A554';
DELETE FROM ref_birds WHERE ref_birds_code = 'A559';
DELETE FROM ref_birds WHERE ref_birds_code = 'A561';
DELETE FROM ref_birds WHERE ref_birds_code = 'A563';
DELETE FROM ref_birds WHERE ref_birds_code = 'A564';
DELETE FROM ref_birds WHERE ref_birds_code = 'A565';
DELETE FROM ref_birds WHERE ref_birds_code = 'A566';
DELETE FROM ref_birds WHERE ref_birds_code = 'A567';
DELETE FROM ref_birds WHERE ref_birds_code = 'A568';
DELETE FROM ref_birds WHERE ref_birds_code = 'A602';
DELETE FROM ref_birds WHERE ref_birds_code = 'A606';
DELETE FROM ref_birds WHERE ref_birds_code = 'A611';
DELETE FROM ref_birds WHERE ref_birds_code = 'A624';
DELETE FROM ref_birds WHERE ref_birds_code = 'A625';
DELETE FROM ref_birds WHERE ref_birds_code = 'A626';
DELETE FROM ref_birds WHERE ref_birds_code = 'A628';
DELETE FROM ref_birds WHERE ref_birds_code = 'A630';
DELETE FROM ref_birds WHERE ref_birds_code = 'A632';
DELETE FROM ref_birds WHERE ref_birds_code = 'A636';
DELETE FROM ref_birds WHERE ref_birds_code = 'A637';
DELETE FROM ref_birds WHERE ref_birds_code = 'A638';
DELETE FROM ref_birds WHERE ref_birds_code = 'A643';
DELETE FROM ref_birds WHERE ref_birds_code = 'A644';
DELETE FROM ref_birds WHERE ref_birds_code = 'A645';
DELETE FROM ref_birds WHERE ref_birds_code = 'A646';
DELETE FROM ref_birds WHERE ref_birds_code = 'A649';
DELETE FROM ref_birds WHERE ref_birds_code = 'A650';
DELETE FROM ref_birds WHERE ref_birds_code = 'A651';
DELETE FROM ref_birds WHERE ref_birds_code = 'A655';
DELETE FROM ref_birds WHERE ref_birds_code = 'A656';
DELETE FROM ref_birds WHERE ref_birds_code = 'A657';
DELETE FROM ref_birds WHERE ref_birds_code = 'A658';
DELETE FROM ref_birds WHERE ref_birds_code = 'A659';
DELETE FROM ref_birds WHERE ref_birds_code = 'A664';
DELETE FROM ref_birds WHERE ref_birds_code = 'A668';
DELETE FROM ref_birds WHERE ref_birds_code = 'A676';
DELETE FROM ref_birds WHERE ref_birds_code = 'A681';
DELETE FROM ref_birds WHERE ref_birds_code = 'A745';
DELETE FROM ref_birds WHERE ref_birds_code = 'A746';
DELETE FROM ref_birds WHERE ref_birds_code = 'A426';
DELETE FROM ref_birds WHERE ref_birds_code = 'A505';
DELETE FROM ref_birds WHERE ref_birds_code = 'A519';
DELETE FROM ref_birds WHERE ref_birds_code = 'A525';
DELETE FROM ref_birds WHERE ref_birds_code = 'A530';