-- temporarily turn on auto increment to insert new rows
ALTER TABLE `ref_habitats_emerald` CHANGE `REF_HABITATS_ID` `REF_HABITATS_ID` int(11) AUTO_INCREMENT NOT NULL;
-- new values
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('B1.1', 'Sand beach driftlines');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('B2.1', 'Shingle beach driftlines');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('B3.24', 'Unvegetated Baltic rocky shores and cliffs');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('B3.3', 'Rock cliffs, ledges and shores, with angiosperms');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('C1.32', 'Free-floating vegetation of eutrophic waterbodies');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('C1.33', 'Rooted submerged vegetation of eutrophic waterbodies');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('C1.4', 'Permanent dystrophic lakes, ponds and pools');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('C2.111', 'Fennoscandian mineral-rich springs and springfens');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('C2.18', 'Acid oligotrophic vegetation of spring brooks');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('C2.19', 'Lime-rich oligotrophic vegetation of spring brooks');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('C2.1A', 'Mesotrophic vegetation of spring brooks');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('C2.1B', 'Eutrophic vegetation of spring brooks');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('C2.25', 'Acid oligotrophic vegetation of fast-flowing streams');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('C2.26', 'Lime-rich oligotrophic vegetation of fast-flowing streams');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('C2.27', 'Mesotrophic vegetation of fast-flowing streams');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('C2.28', 'Eutrophic vegetation of fast-flowing streams');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('C2.33', 'Mesotrophic vegetation of slow-flowing rivers');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('C2.34', 'Eutrophic vegetation of slow-flowing rivers');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('C3.4', 'Species-poor beds of low-growing water-fringing or amphibious vegetation');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('C3.51', 'Euro-Siberian dwarf annual amphibious swards (but excluding C3.5131 Toad-rush swards)');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('D6.23', 'Interior Iberian salt pan meadows');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('E1.11', 'Euro-Siberian rock debris swards');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('E1.12', 'Euro-Siberian pioneer calcareous sand swards');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('E1.13', 'Continental dry rocky steppic grasslands and dwarf scrub on chalk outcrops');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('E1.55', 'Eastern sub-Mediterranean dry grassland');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('E1.722', 'Boreo-arctic Agrostis-Festuca grasslands');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('E1.9', 'Open non-Mediterranean dry acid and neutral grassland, including inland dune grassland');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('E2.15', 'Macaronesian mesic grassland');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('E2.2', 'Low and medium altitude hay meadows');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('E2.3', 'Mountain hay meadows');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('E3.3', 'Sub-mediterranean humid meadows');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('E4.11', 'Boreo-alpine acidocline snow-patch grassland and herb habitats');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('E4.12', 'Boreo-alpine calcicline snow-patch grassland and herb habitats');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('E4.3', 'Acid alpine and subalpine grassland');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('E4.4', 'Calcareous alpine and subalpine grassland');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('E5.4', 'Moist or wet tall-herb and fern fringes and meadows');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('E5.5', 'Subalpine moist or wet tall-herb and fern stands');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('F2.22', 'Alpide acidocline Rhododendron heaths');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('F2.32', 'Subalpine and oroboreal Salix brush');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('F2.336', 'Rhodope Potentilla fruticosa thickets');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('F2.41', 'Inner Alpine Pinus mugo  scrub');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('F2.42', 'Outer Alpine Pinus mugo scrub');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('F2.43', 'Southwestern Pinus mugo scrub');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('F2.44', 'Apennine Pinus mugo scrub');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('F2.45', 'Hercynian Pinus mugo scrub');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('F3.12', 'Buxus sempervirens thickets');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('F3.16', 'Juniperus communis scrub');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('F3.21', 'Montane Cytisus purgans fields');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('F3.245', 'Eastern Mediterranean deciduous thickets');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('F3.247', 'Ponto-Sarmatic deciduous thickets');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('F5.13', 'Juniper matorral');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('F5.171', 'Iberian arid zone Ziziphus matorral');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('F5.18', 'Laurus nobilis matorral');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('F5.516', 'Laurus thickets');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('F5.517', 'Coastal Helichrysum garrigues');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('F5.51G', 'Tall spiny broom brush');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('F5.53', 'Ampelodesmos mauritanica -dominated garrigues');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('G1.22', 'Mixed Quercus - Ulmus - Fraxinus woodland of great rivers');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('G1.3', 'Mediterranean riparian woodland');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('G1.917', 'Oroboreal Betula woods and thickets');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('G1.918', 'Eurasian boreal Betula  woods');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('G1.925', 'Boreal Populus tremula woods');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('G1.B3', 'Boreal and boreonemoral Alnus woods');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('G3.134', 'Holy Cross fir forests');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('G3.1E', 'Southern European Picea abies forests');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('G3.1F', 'Enclave Picea abies forests');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('G3.43', 'Inner-Alpine Ononis steppe forests');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('G3.44', 'Spring heath Pinus sylvestris forests');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('G3.5', 'Pinus nigra woodland (but excluding G3.57 : Pinus nigra reforestation)');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('G3.7', 'Lowland to montane mediterranean Pinus woodland (excluding Pinus nigra )');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('G3.A', 'Picea taiga woodland');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('G3.B', 'Pinus taiga woodland');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('H2.1', 'Cold siliceous screes');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('H2.2', 'Cold limestone screes');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('H2.3', 'Temperate-montane acid siliceous screes');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('H2.4', 'Temperate-montane calcareous and ultra-basic screes');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('H2.5', 'Acid siliceous screes of warm exposures');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('H2.6', 'Calcareous and ultra-basic screes of warm exposures');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('H3.1', 'Acid siliceous inland cliffs');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('H3.2', 'Basic and ultra-basic inland cliffs');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('H3.511', 'Limestone pavements');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('H4.2', 'Ice caps and true glaciers');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('H4.3', 'Rock glaciers and unvegetated ice-dominated moraines');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('H6', 'Recent volcanic features');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('X09', 'Pasture woods (with a tree layer overlying pasture)');
INSERT INTO ref_habitats_emerald (`REF_HABITATS_CODE`, `REF_HABITATS_DESC_EN`) VALUES ('C1.24113', 'Transylvanian hot-spring lotus beds');
-- disable auto increment again
ALTER TABLE `ref_habitats_emerald` CHANGE `REF_HABITATS_ID` `REF_HABITATS_ID` int(11) NOT NULL;