UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Mussel and/or barnacle communities' WHERE REF_HABITATS_CODE = 'A1.11';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Association with Lithophyllum byssoides' WHERE REF_HABITATS_CODE = 'A1.141';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Mussels and fucoids on moderately exposed shores' WHERE REF_HABITATS_CODE = 'A1.22';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Communities of littoral caves and overhangs' WHERE REF_HABITATS_CODE = 'A1.44';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Littoral sand and muddy sand' WHERE REF_HABITATS_CODE = 'A2.2';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Littoral mud' WHERE REF_HABITATS_CODE = 'A2.3';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Littoral mixed sediments' WHERE REF_HABITATS_CODE = 'A2.4';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Coastal saltmarshes and saline reedbeds' WHERE REF_HABITATS_CODE = 'A2.5';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Seagrass beds on littoral sediments' WHERE REF_HABITATS_CODE = 'A2.61';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Eleocharis beds' WHERE REF_HABITATS_CODE = 'A2.621';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Littoral mussel beds on sediment' WHERE REF_HABITATS_CODE = 'A2.72';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Infralittoral rock and other hard substrata' WHERE REF_HABITATS_CODE = 'A3';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Circalittoral rock and other hard substrata' WHERE REF_HABITATS_CODE = 'A4';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Sublittoral sediment' WHERE REF_HABITATS_CODE = 'A5';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Seeps in the deep-sea bed' WHERE REF_HABITATS_CODE = 'A6.911';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Shifting coastal dunes' WHERE REF_HABITATS_CODE = 'B1.3';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Coastal stable dune grassland (grey dunes)' WHERE REF_HABITATS_CODE = 'B1.4';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Coastal dune heaths' WHERE REF_HABITATS_CODE = 'B1.5';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Coastal dune scrub' WHERE REF_HABITATS_CODE = 'B1.6';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Coastal dune woods' WHERE REF_HABITATS_CODE = 'B1.7';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Moist and wet dune slacks' WHERE REF_HABITATS_CODE = 'B1.8';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Machair' WHERE REF_HABITATS_CODE = 'B1.9';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Upper shingle beaches with open vegetation' WHERE REF_HABITATS_CODE = 'B2.3';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Permanent oligotrophic lakes, ponds and pools' WHERE REF_HABITATS_CODE = 'C1.1';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Floating Hydrocharis morsus-ranae rafts' WHERE REF_HABITATS_CODE = 'C1.222';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Floating Stratiotes aloides rafts' WHERE REF_HABITATS_CODE = 'C1.223';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Floating Utricularia australis and Utricularia vulgaris colonies' WHERE REF_HABITATS_CODE = 'C1.224';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Floating Salvinia natans mats' WHERE REF_HABITATS_CODE = 'C1.225';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Floating Aldrovanda vesiculosa communities' WHERE REF_HABITATS_CODE = 'C1.226';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Nelumbo nucifera beds' WHERE REF_HABITATS_CODE = 'C1.2416';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Charophyte submerged carpets in mesotrophic waterbodies' WHERE REF_HABITATS_CODE = 'C1.25';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Ranunculus communities in shallow water' WHERE REF_HABITATS_CODE = 'C1.3411';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Hottonia palustris beds in shallow water' WHERE REF_HABITATS_CODE = 'C1.3413';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Permanent inland saline and brackish lakes, ponds and pools' WHERE REF_HABITATS_CODE = 'C1.5';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Temporary inland saline and brackish waters' WHERE REF_HABITATS_CODE = 'C1.66';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Turlough and lake-bottom meadows' WHERE REF_HABITATS_CODE = 'C1.67';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Hard water springs' WHERE REF_HABITATS_CODE = 'C2.12';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Sparsely vegetated river gravel banks' WHERE REF_HABITATS_CODE = 'C3.55';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Unvegetated river gravel banks' WHERE REF_HABITATS_CODE = 'C3.62';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Blanket bogs' WHERE REF_HABITATS_CODE = 'D1.2';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Peri-Danubian black-white-star sedge fens' WHERE REF_HABITATS_CODE = 'D2.226';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Transition mires and quaking bogs' WHERE REF_HABITATS_CODE = 'D2.3';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Palsa mires' WHERE REF_HABITATS_CODE = 'D3.1';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Aapa mires' WHERE REF_HABITATS_CODE = 'D3.2';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Polygon mires' WHERE REF_HABITATS_CODE = 'D3.3';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Rich fens, including eutrophic tall-herb fens and calcareous flushes and soaks' WHERE REF_HABITATS_CODE = 'D4.1';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Basic mountain flushes and streamsides, with a rich arctic-montane flora' WHERE REF_HABITATS_CODE = 'D4.2';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Beds of large sedges normally without free-standing water' WHERE REF_HABITATS_CODE = 'D5.2';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Inland saltmarshes' WHERE REF_HABITATS_CODE = 'D6.1';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Perennial calcareous grassland and basic steppes' WHERE REF_HABITATS_CODE = 'E1.2';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Mediterranean xeric grassland' WHERE REF_HABITATS_CODE = 'E1.3';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Nardus stricta swards' WHERE REF_HABITATS_CODE = 'E1.71';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Mediterraneo-montane Nardus stricta swards' WHERE REF_HABITATS_CODE = 'E1.83';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Heavy-metal grassland' WHERE REF_HABITATS_CODE = 'E1.B';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Mediterranean tall humid grassland' WHERE REF_HABITATS_CODE = 'E3.1';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Moist or wet eutropic and mesotrophic grassland' WHERE REF_HABITATS_CODE = 'E3.4';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Moist or wet oligotrophic grassland' WHERE REF_HABITATS_CODE = 'E3.5';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Mediterranean inland salt steppes' WHERE REF_HABITATS_CODE = 'E6.1';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Continental inland salt steppes' WHERE REF_HABITATS_CODE = 'E6.2';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Dehesa' WHERE REF_HABITATS_CODE = 'E7.3';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Bruckenthalia heaths' WHERE REF_HABITATS_CODE = 'F2.26';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Central European subcontinental thickets' WHERE REF_HABITATS_CODE = 'F3.241';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Wet heaths' WHERE REF_HABITATS_CODE = 'F4.1';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Dry heaths' WHERE REF_HABITATS_CODE = 'F4.2';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Macaronesian heaths' WHERE REF_HABITATS_CODE = 'F4.3';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Euphorbia dendroides formations' WHERE REF_HABITATS_CODE = 'F5.52';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Chamaerops humilis brush' WHERE REF_HABITATS_CODE = 'F5.54';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Mediterranean pre-desert scrub' WHERE REF_HABITATS_CODE = 'F5.55';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Thermo-Mediterranean broom fields (retamares)' WHERE REF_HABITATS_CODE = 'F5.56';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Cabo de Sao Vicente brushes' WHERE REF_HABITATS_CODE = 'F5.5B';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Mediterranean gypsum scrubs' WHERE REF_HABITATS_CODE = 'F6.7';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Xero-halophile scrubs' WHERE REF_HABITATS_CODE = 'F6.8';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Spiny Mediterranean heaths (phrygana, hedgehog-heaths and related coastal cliff vegetation)' WHERE REF_HABITATS_CODE = 'F7';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Riverine scrub' WHERE REF_HABITATS_CODE = 'F9.1';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Southern riparian galleries and thickets' WHERE REF_HABITATS_CODE = 'F9.3';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Riverine Salix woodland' WHERE REF_HABITATS_CODE = 'G1.11';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Boreo-alpine riparian galleries' WHERE REF_HABITATS_CODE = 'G1.12';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Southern Alnus and Betula galleries' WHERE REF_HABITATS_CODE = 'G1.13';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Riverine Fraxinus - Alnus woodland, wet at high but not at low water' WHERE REF_HABITATS_CODE = 'G1.21';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Eastern Carpathian Alnus glutinosa swamp woods' WHERE REF_HABITATS_CODE = 'G1.4115';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Steppe swamp Alnus glutinosa woods' WHERE REF_HABITATS_CODE = 'G1.414';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Wet-ground woodland of the Black and Caspian Seas' WHERE REF_HABITATS_CODE = 'G1.44';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Sphagnum Betula woods' WHERE REF_HABITATS_CODE = 'G1.51';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Fagus woodland' WHERE REF_HABITATS_CODE = 'G1.6';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Thermophilous deciduous woodland' WHERE REF_HABITATS_CODE = 'G1.7';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Acidophilous Quercus-dominated woodland' WHERE REF_HABITATS_CODE = 'G1.8';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Quercus - Fraxinus - Carpinus betulus woodland on eutrophic and mesotrophic soils' WHERE REF_HABITATS_CODE = 'G1.A1';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Ravine and slope woodland' WHERE REF_HABITATS_CODE = 'G1.A4';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Mixed deciduous woodland of the Black and Caspian Seas' WHERE REF_HABITATS_CODE = 'G1.A7';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Broadleaved evergreen woodland' WHERE REF_HABITATS_CODE = 'G2';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Southern Apennine Abies alba forests' WHERE REF_HABITATS_CODE = 'G3.15';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Moesian Abies alba forests' WHERE REF_HABITATS_CODE = 'G3.16';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Balkano-Pontic Abies forests' WHERE REF_HABITATS_CODE = 'G3.17';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Abies pinsapo forests' WHERE REF_HABITATS_CODE = 'G3.19';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Alpine and Carpathian subalpine Picea forests' WHERE REF_HABITATS_CODE = 'G3.1B';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Inner range montane Picea forests' WHERE REF_HABITATS_CODE = 'G3.1C';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Hercynian subalpine Picea forests' WHERE REF_HABITATS_CODE = 'G3.1D';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Picea omorika forests' WHERE REF_HABITATS_CODE = 'G3.1G';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Picea orientalis forests' WHERE REF_HABITATS_CODE = 'G3.1H';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Eastern Alpine siliceous Larix and Pinus cembra forests' WHERE REF_HABITATS_CODE = 'G3.21';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Eastern Alpine calcicolous Larix and Pinus cembra forests' WHERE REF_HABITATS_CODE = 'G3.22';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Carpathian Larix and Pinus cembra forests' WHERE REF_HABITATS_CODE = 'G3.25';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Larix polonica forests' WHERE REF_HABITATS_CODE = 'G3.26';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Pinus uncinata forests with Rhododendron ferrugineum' WHERE REF_HABITATS_CODE = 'G3.31';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Xerocline Pinus uncinata forests' WHERE REF_HABITATS_CODE = 'G3.32';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Caledonian forest' WHERE REF_HABITATS_CODE = 'G3.41';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Sarmatic steppe Pinus sylvestris forests' WHERE REF_HABITATS_CODE = 'G3.4232';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Carpathian steppe Pinus sylvestris woods' WHERE REF_HABITATS_CODE = 'G3.4233';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Pannonic steppe Pinus sylvestris woods' WHERE REF_HABITATS_CODE = 'G3.4234';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Southeastern European Pinus sylvestris forests' WHERE REF_HABITATS_CODE = 'G3.4C';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Ponto-Caucasian Pinus sylvestris forests' WHERE REF_HABITATS_CODE = 'G3.4E';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Subalpine mediterranean Pinus woodland' WHERE REF_HABITATS_CODE = 'G3.6';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Canary Island Pinus canariensis woodland' WHERE REF_HABITATS_CODE = 'G3.8';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Coniferous woodland dominated by Cupressaceae or Taxaceae' WHERE REF_HABITATS_CODE = 'G3.9';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Boreal bog conifer woodland' WHERE REF_HABITATS_CODE = 'G3.D';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Nemoral bog conifer woodland' WHERE REF_HABITATS_CODE = 'G3.E';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Terrestrial underground caves, cave systems, passages and waterbodies' WHERE REF_HABITATS_CODE = 'H1';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Estuaries' WHERE REF_HABITATS_CODE = 'X01';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Saline coastal lagoons' WHERE REF_HABITATS_CODE = 'X02';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Brackish coastal lagoons' WHERE REF_HABITATS_CODE = 'X03';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Raised bog complexes' WHERE REF_HABITATS_CODE = 'X04';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Wooded steppe' WHERE REF_HABITATS_CODE = 'X18';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Salt lake islands' WHERE REF_HABITATS_CODE = 'X29';
UPDATE ref_habitats_emerald SET REF_HABITATS_DESC_EN = 'Inland Sand Dunes', REF_HABITATS_DESC_FR = '' WHERE REF_HABITATS_CODE = 'X35';