insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (1, '0', 'Marine area not covered by a NUTS');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (2, 'AD', 'ANDORRA');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (3, 'AL', 'SHQIPERIA');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (4, 'AL000001', 'BERAT');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (5, 'AL000002', 'DIBER');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (6, 'AL000003', 'DURRES');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (7, 'AL000004', 'ELBASAN');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (8, 'AL000005', 'FIER');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (9, 'AL000006', 'GJIROKASTER');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (10, 'AL000007', 'GRAMSH');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (11, 'AL000008', 'KOLONJE');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (12, 'AL000009', 'KORCE');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (13, 'AL000010', 'KRUJE');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (14, 'AL000011', 'KUKES');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (15, 'AL000012', 'LEZHE');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (16, 'AL000013', 'LIBRAHZD');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (17, 'AL000014', 'LUSHNJE');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (18, 'AL000015', 'MAT');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (19, 'AL000016', 'MIRDITE');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (20, 'AL000017', 'PERMET');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (21, 'AL000018', 'POGRADEC');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (22, 'AL000019', 'PUKE');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (23, 'AL000020', 'SARANDE');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (24, 'AL000021', 'SHKODER');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (25, 'AL000022', 'SKRAPAR');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (26, 'AL000023', 'TEPELENE');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (27, 'AL000024', 'TIRANE');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (28, 'AL000025', 'TROPOJE');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (29, 'AL000026', 'VLORE');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (30, 'AM', 'ARMENIA');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (31, 'AM01', 'Aragatsotn marz');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (32, 'AM02', 'Ararat marz');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (33, 'AM03', 'Armavir marz');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (34, 'AM04', 'Gegharkunik marz');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (35, 'AM05', 'Lori marz');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (36, 'AM06', 'Kotayk marz');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (37, 'AM07', 'Shirak marz');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (38, 'AM08', 'Syunik marz');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (39, 'AM09', 'Vayots Dzor marz');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (40, 'AM10', 'Tavush marz');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (41, 'AZ', 'AZERBAIJAN');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (42, 'BY', 'BELARUSIJA / BELORUSSIJA');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (43, 'BY0001', 'BRESTSKAYA VOBLASTS');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (44, 'BY0002', 'HRODZENSKAYA VOBLASTS');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (45, 'BY0003', 'HOMYEL\'SKAYA VOBLASTS');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (46, 'BY0004', 'MINSKAYA VOBLASTS');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (47, 'BY0005', 'MAHILYOWSKAYA VOBLASTS');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (48, 'BY0006', 'VITSYEBSKAYA VOBLASTS');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (49, 'CH', 'SCHWEIZ/SUISSE/SVIZZERA');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (50, 'CH01', 'Région lémanique');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (51, 'CH011', 'Vaud');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (52, 'CH012', 'Valais');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (53, 'CH013', 'Genève');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (54, 'CH02', 'Espace Mittelland');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (55, 'CH021', 'Bern');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (56, 'CH022', 'Freiburg');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (57, 'CH023', 'Solothurn');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (58, 'CH024', 'Neuchâtel');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (59, 'CH025', 'Jura');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (60, 'CH03', 'Nordwestschweiz');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (61, 'CH031', 'Basel-Stadt');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (62, 'CH032', 'Basel-Landschaft');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (63, 'CH033', 'Aargau');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (64, 'CH04', 'Zürich');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (65, 'CH05', 'Ostschweiz');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (66, 'CH051', 'Glarus');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (67, 'CH052', 'Schaffhausen');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (68, 'CH053', 'Appenzell Ausserrhoden');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (69, 'CH054', 'Appenzell Innerrhoden');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (70, 'CH055', 'St. Gallen');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (71, 'CH056', 'Graubünden');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (72, 'CH057', 'Thurgau');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (73, 'CH06', 'Zentralschweiz');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (74, 'CH061', 'Luzern');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (75, 'CH062', 'Uri');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (76, 'CH063', 'Schwyz');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (77, 'CH064', 'Obwalden');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (78, 'CH065', 'Nidwalden');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (79, 'CH066', 'Zug');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (80, 'CH07', 'Ticino');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (81, 'CV', 'CABO VERDE');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (82, 'DZ', 'AL JAZA\'IR');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (83, 'GE', 'GEORGIA');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (84, 'IS', 'ÍSLAND');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (85, 'KZ', 'KAZAKHSTAN');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (86, 'LI', 'LIECHTENSTEIN');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (87, 'MA', 'AL MAGHRIB');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (88, 'MC', 'MONACO');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (89, 'MD', 'MOLDOVA');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (90, 'MD000001', 'Anenii Noi ');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (91, 'MD000002', 'Basarabeasca ');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (92, 'MD000003', 'Briceni ');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (93, 'MD000004', 'Cahul ');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (94, 'MD000005', 'Cantemir ');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (95, 'MD000006', 'Calarasi ');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (96, 'MD000007', 'Causeni ');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (97, 'MD000008', 'Cimislia ');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (98, 'MD000009', 'Criuleni ');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (99, 'MD000010', 'Donduseni ');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (100, 'MD000011', 'Drochia ');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (101, 'MD000012', 'Dubasari ');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (102, 'MD000013', 'Edinet ');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (103, 'MD000014', 'Falesti ');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (104, 'MD000015', 'Floresti ');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (105, 'MD000016', 'Glodeni ');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (106, 'MD000017', 'Hîncesti ');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (107, 'MD000018', 'Ialoveni');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (108, 'MD000019', 'Leova ');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (109, 'MD000020', 'Nisporeni ');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (110, 'MD000021', 'Ocnita ');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (111, 'MD000022', 'Orhei ');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (112, 'MD000023', 'Rezina ');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (113, 'MD000024', 'Rîscani ');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (114, 'MD000025', 'Sîngerei ');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (115, 'MD000026', 'Soroca ');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (116, 'MD000027', 'Straseni ');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (117, 'MD000028', 'Soldanesti ');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (118, 'MD000029', 'Stefan Voda ');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (119, 'MD000030', 'Taraclia ');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (120, 'MD000031', 'Telenesti ');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (121, 'MD000032', 'Ungheni');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (122, 'MD000033', 'U.T.A. Gagauzia (Autonomous Unit Gagauzia)');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (123, 'MK', 'FYR of Macedinia');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (124, 'MR', 'MURITANIYAH');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (125, 'NO', 'NORGE');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (126, 'NO01', 'Oslo og Akershus');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (127, 'NO011', 'Oslo');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (128, 'NO012', 'Akershus');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (129, 'NO02', 'Hedmark og Oppland');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (130, 'NO021', 'Hedmark');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (131, 'NO022', 'Oppland');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (132, 'NO03', 'Sør-Østlandet');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (133, 'NO031', 'Østfold');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (134, 'NO032', 'Buskerud');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (135, 'NO033', 'Vestfold');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (136, 'NO034', 'Telemark');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (137, 'NO04', 'Agder og Rogaland');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (138, 'NO041', 'Aust-Agder');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (139, 'NO042', 'Vest-Agder');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (140, 'NO043', 'Rogaland');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (141, 'NO05', 'Vestlandet');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (142, 'NO051', 'Hordaland');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (143, 'NO052', 'Sogn og Fjordane');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (144, 'NO053', 'Møre og Romsdal');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (145, 'NO06', 'Trøndelag');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (146, 'NO061', 'Sør-Trøndelag');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (147, 'NO062', 'Nord-Trøndelag');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (148, 'NO07', 'Nord-Norge');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (149, 'NO071', 'Nordland');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (150, 'NO072', 'Troms');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (151, 'NO073', 'Finnmark');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (152, 'RS', 'Serbia');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (153, 'RU', 'ROSSIJA');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (154, 'RU01', 'Republic of Adygeya (Adygeya)');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (155, 'RU02', 'Bashkortostan Republic');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (156, 'RU03', 'Republic of Buryatia');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (157, 'RU04', 'Republic of Altai');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (158, 'RU05', 'Republic of Daghestan');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (159, 'RU06', 'Republic of Ingushetia');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (160, 'RU07', 'Kabardino-Balkarian Republic');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (161, 'RU08', 'Republic of Kalmykia');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (162, 'RU09', 'Karachayevo-Circassian Republic');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (163, 'RU10', 'Republic of Karelia');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (164, 'RU11', 'Republic of Komi');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (165, 'RU12', 'Republic of Marii El');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (166, 'RU13', 'Republic of Mordovia');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (167, 'RU14', 'Republic of Yakutia (Sakha)');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (168, 'RU15', 'Republic of North Ossetia-Alania');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (169, 'RU16', 'Republic of Tatarstan (Tatarstan)');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (170, 'RU17', 'Republic of Tyva');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (171, 'RU18', 'Republic of Udmurtia');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (172, 'RU19', 'Republic of Khakassia');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (173, 'RU20', 'Chechen Republic');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (174, 'RU21', 'Chuvash Republic - Chuvashia');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (175, 'RU22', 'Altai Territory');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (176, 'RU23', 'Krasnodar Territory');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (177, 'RU24', 'Krasnoyarsk Territory');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (178, 'RU25', 'Primorie Territory');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (179, 'RU26', 'Stavropol Territory');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (180, 'RU27', 'Khabarovsk Territory');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (181, 'RU28', 'Amur Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (182, 'RU29', 'Arkhangelsk Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (183, 'RU30', 'Astrakhan Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (184, 'RU31', 'Belgorod Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (185, 'RU32', 'Bryansk Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (186, 'RU33', 'Vladimir Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (187, 'RU34', 'Volgograd Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (188, 'RU35', 'Vologda Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (189, 'RU36', 'Voronezh Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (190, 'RU37', 'Ivanovo Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (191, 'RU38', 'Irkutsk Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (192, 'RU39', 'Kaliningrad Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (193, 'RU40', 'Kaluga Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (194, 'RU41', 'Kamchatka Territory');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (195, 'RU42', 'Kemerovo Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (196, 'RU43', 'Kirov Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (197, 'RU44', 'Kostroma Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (198, 'RU45', 'Kurgan Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (199, 'RU46', 'Kursk Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (200, 'RU47', 'Leningrad Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (201, 'RU48', 'Lipetsk Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (202, 'RU49', 'Magadan Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (203, 'RU50', 'Moscow Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (204, 'RU51', 'Murmansk Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (205, 'RU52', 'Nizhni Novgorod Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (206, 'RU53', 'Novgorod Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (207, 'RU54', 'Novosibirsk Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (208, 'RU55', 'Omsk Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (209, 'RU56', 'Orenburg Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (210, 'RU57', 'Orel Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (211, 'RU58', 'Penza Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (212, 'RU59', 'Perm Territory');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (213, 'RU60', 'Pskov Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (214, 'RU61', 'Rostov Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (215, 'RU62', 'Ryazan Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (216, 'RU63', 'Samara Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (217, 'RU64', 'Saratov Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (218, 'RU65', 'Sakhalin Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (219, 'RU66', 'Sverdlovsk Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (220, 'RU67', 'Smolensk Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (221, 'RU68', 'Tambov Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (222, 'RU69', 'Tver Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (223, 'RU70', 'Tomsk Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (224, 'RU71', 'Tula Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (225, 'RU72', 'Tyumen Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (226, 'RU73', 'Ulyanovsk Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (227, 'RU74', 'Chelyabinsk Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (228, 'RU75', 'Zabaykalsky Territory');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (229, 'RU76', 'Yaroslavl Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (230, 'RU77', 'Moscow');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (231, 'RU78', 'St. Petersburg');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (232, 'RU79', 'Jewish Autonomous Region');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (233, 'RU83', 'Nenets Autonomous District');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (234, 'RU86', 'Khanty-Mansijsk Autonomous District');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (235, 'RU87', 'Chukotka Autonomous District');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (236, 'RU89', 'Yamalo-Nenets Autonomous District');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (237, 'SM', 'SAN MARINO');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (238, 'SN', 'SENEGAL');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (239, 'TN', 'TUNIS');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (240, 'TR', 'TURKIYE');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (241, 'TR000001', 'EDIRNE');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (242, 'TR000002', 'KIRKLARELI');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (243, 'TR000003', 'TEKIRDAG');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (244, 'TR000004', 'ISTANBUL');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (245, 'TR000005', 'CANAKKALE');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (246, 'TR000006', 'OTHER TURKEY');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (247, 'UA', 'UKRAJINA / UKRAIANA');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (248, 'UA01', 'Autonomous Republic of Crimea');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (249, 'UA05', 'Vinnytsya Oblast');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (250, 'UA07', 'Volyn Oblast');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (251, 'UA12', 'Dnipropetrovs\'k Oblast');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (252, 'UA14', 'Donets\'k Oblast');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (253, 'UA18', 'Zhytomyr Oblast');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (254, 'UA21', 'Zakarpattya Oblast');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (255, 'UA23', 'Zaporizhya Oblast');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (256, 'UA26', 'Ivano-Frankivs\'k Oblast');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (257, 'UA32', 'Kyiv  oblast');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (258, 'UA35', 'Kirovohrad Oblast');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (259, 'UA44', 'Luhans\'k Oblast');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (260, 'UA46', 'L\'viv Oblast');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (261, 'UA48', 'Mykolayiv Oblast');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (262, 'UA51', 'Odesa Oblast');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (263, 'UA53', 'Poltava Oblast');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (264, 'UA56', 'Rivne Oblast');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (265, 'UA59', 'Sumy Oblast');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (266, 'UA61', 'Ternopil\' Oblast');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (267, 'UA63', 'Kharkiv Oblast');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (268, 'UA65', 'Kherson Oblast');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (269, 'UA68', 'Khmelnytskyi Oblast');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (270, 'UA71', 'Cherkasy Oblast');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (271, 'UA73', 'Chernivtsi Oblast ');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (272, 'UA74', 'Chernihiv Oblast');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (273, 'UA80', 'Kyiv');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (274, 'UA85', 'Sevastopol\'');
insert ignore INTO natura2000.ref_nuts_emerald (`REF_NUTS_ID`, `REF_NUTS_CODE`, `REF_NUTS_DESCRIPTION`) VALUES (275, 'VA', 'HOLY SEE');
