insert ignore into country_emerald VALUES(1,'AM', 'Armenia');
insert ignore into country_emerald VALUES(2,'AZ', 'Azerbaijan');
insert ignore into country_emerald VALUES(3,'BY', 'Belarus');
insert ignore into country_emerald VALUES(4,'GE', 'Georgia');
insert ignore into country_emerald VALUES(5,'MD', 'Moldova');
insert ignore into country_emerald VALUES(6,'UA', 'Ukraine');
insert ignore into country_emerald VALUES(7,'RU', 'Russia');
insert ignore into country_emerald VALUES(8,'AL', 'Albania');
insert ignore into country_emerald VALUES(9,'BA', 'Bosnia-Herzegovina');
insert ignore into country_emerald VALUES(10,'MK', 'FYR Macedonia');
insert ignore into country_emerald VALUES(11,'ME', 'Montenegro');
insert ignore into country_emerald VALUES(12,'RS', 'Serbia');
insert ignore into country_emerald VALUES(13,'IS', 'Iceland');
insert ignore into country_emerald VALUES(14,'NO', 'Norway');
insert ignore into country_emerald VALUES(15,'CH', 'Switzerland');
insert ignore into country_emerald VALUES(16,'MA', 'Morocco');
insert ignore into country_emerald VALUES(17,'AD', 'Andorra');
insert ignore into country_emerald VALUES(18,'LI', 'Liechtenstein');
insert ignore into country_emerald VALUES(19,'MC', 'Monaco');
insert ignore into country_emerald VALUES(20,'TR', 'Turkey');
insert ignore into country_emerald VALUES(21,'BF', 'Burkina Faso');
insert ignore into country_emerald VALUES(22,'SN', 'Senegal');
insert ignore into country_emerald VALUES(23,'TN', 'Tunisia');
