package sdf_manager;

import java.awt.*;
import java.io.IOException;
import java.util.Properties;

import javax.swing.JFrame;

import org.hibernate.Session;

import pojos.DocLink;
import sdf_manager.util.SDF_Util;

/**
 *
 * @author charbda
 */
public class EditorDocLink extends javax.swing.JFrame {

    int index;
    DocLink docLink;
    boolean editing = false;
    private final static org.apache.logging.log4j.Logger log = org.apache.logging.log4j.LogManager.getLogger(EditorDocLink.class .getName());

    /** Creates new form EditorRegions. */
    private SDFEditor parent;

    /**
     *
     * @param parent
     */
    public EditorDocLink(SDFEditor parent) {
        this.parent = parent;
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        centerScreen();
    }


    /**
     * Loads the data of the doc
     * @param s
     * @param index
     */
    public void loadDoc(DocLink link, int index) {
        this.index = index;
        docLink = link;
        this.txtLink.setText(link.getDocLinkUrl());
        this.editing = true;
    }

    /**
     *
     */
    private void exit() {
       this.dispose();
    }

    /**
     *
     */
    private void centerScreen() {
      Dimension dim = getToolkit().getScreenSize();
      Rectangle abounds = getBounds();
      setLocation((dim.width - abounds.width) / 2,
          (dim.height - abounds.height) / 2);
      super.setVisible(true);
      requestFocus();
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLink = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        Properties p = new Properties();
        try {
            p.load(getClass().getResourceAsStream("resources/EditorDocLink.properties"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        setTitle(p.getProperty("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jLabel3.setFont(new Font(p.getProperty("jLabel3.font"), 12, 18)); // NOI18N
        jLabel3.setText(p.getProperty("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(p.getProperty("jPanel3.border.title"))); // NOI18N
        jPanel3.setName("jPanel3"); // NOI18N

        jLabel1.setText(p.getProperty("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        txtLink.setColumns(20);
        txtLink.setRows(5);
        txtLink.setText(p.getProperty("txtLink.text")); // NOI18N
        txtLink.setName("txtLink"); // NOI18N
        jScrollPane1.setViewportView(txtLink);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setAutoscrolls(true);
        jPanel4.setName("jPanel4"); // NOI18N

        btnSave.setText(p.getProperty("btnSave.text")); // NOI18N
        btnSave.setName("btnSave"); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText(p.getProperty("btnCancel.text")); // NOI18N
        btnCancel.setName("btnCancel"); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(18, 18, 18)
                .addComponent(btnCancel)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnSave)
                .addComponent(btnCancel))
        );

        //jLabel2.setIcon(new ImageIcon(p.getProperty("jLabel2.icon")); // NOI18N
        jLabel2.setIcon(SDF_Util.getIconForLabel(p, "jLabel2.icon", SDF_ManagerApp.getMode()));
        jLabel2.setText(p.getProperty("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3)))
                .addGap(22, 22, 22)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    } // </editor-fold>//GEN-END:initComponents
    /**
     *
     * @param evt
     */
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {
        if (this.txtLink.getText().equals("")) {
            EditorDocLink.log.error("No url ");
            javax.swing.JOptionPane.showMessageDialog(this, "Please provide a valid URL.");
        } else {
            Session session = HibernateUtil.getSessionFactory().openSession();
            try {
	            //String hql = "from DocLink link where link.docLinkUrl like '" + this.txtLink.getText() + "'";
	            //Query q = session.createQuery(hql);
	            //if (q.uniqueResult() != null) {
	            if (this.parent.isLinkInSite(this.txtLink.getText())) {
	               EditorDocLink.log.error("The link already exists. Can't save.");
	               javax.swing.JOptionPane.showMessageDialog(this, "The link already exists. Can't save.");
	               setVisible(true);
	            } else {
	                if (this.editing) {
	                    System.out.println(":: EDITING");
	                    this.docLink.setDocLinkUrl(this.txtLink.getText());
	                    this.parent.updateLink(docLink, index); ;
	                    EditorDocLink.log.info("Link saved.");
	                    javax.swing.JOptionPane.showMessageDialog(this, "Link saved.");
	                    this.exit();
	                } else {
	                    System.out.println(":: IS NOT EDITING");
	                    this.parent.addLink(this.txtLink.getText());
	                    EditorDocLink.log.info("Link saved.");
	                    javax.swing.JOptionPane.showMessageDialog(this, "Link saved.");
	                    this.exit();
	                }
	            }	        
            } catch (Exception ex) {
	     	   log.error("Error while fetching data: " + ex);
	        } finally {
	        	session.close();	            
	        }
        }
    }
    /**
     *
     * @param evt
     */
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_btnCancelActionPerformed
        this.exit();
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtLink;
    // End of variables declaration//GEN-END:variables

}
