update ref_birds SET REF_BIRDS_NAME = 'Anthus berthelotii' where REF_BIRDS_CODE = 'A432';
update ref_birds SET REF_BIRDS_NAME = 'Tachymarptis melba' where REF_BIRDS_CODE = 'A228';
update ref_birds SET REF_BIRDS_NAME = 'Aquila adalberti' where REF_BIRDS_CODE = 'A405';
update ref_birds SET REF_BIRDS_NAME = 'Chloris chloris' where REF_BIRDS_CODE = 'A363';
update ref_birds SET REF_BIRDS_NAME = 'Emberiza leucocephalos' where REF_BIRDS_CODE = 'A541';
update ref_birds SET REF_BIRDS_NAME = 'Iduna pallida' where REF_BIRDS_CODE = 'A438';
update ref_birds SET REF_BIRDS_NAME = 'Lagopus lagopus hibernica' where REF_BIRDS_CODE = 'A463';
update ref_birds SET REF_BIRDS_NAME = 'Emberiza calandra' where REF_BIRDS_CODE = 'A383';
update ref_birds SET REF_BIRDS_NAME = 'Muscicapa dauurica' where REF_BIRDS_CODE = 'A441';
update ref_birds SET REF_BIRDS_NAME = 'Oenanthe finschii' where REF_BIRDS_CODE = 'A532';
update ref_birds SET REF_BIRDS_NAME = 'Regulus ignicapilla' where REF_BIRDS_CODE = 'A318';
update ref_birds SET REF_BIRDS_NAME = 'Saxicola torquatus' where REF_BIRDS_CODE = 'A276';
update ref_birds SET REF_BIRDS_NAME = 'Catharacta skua' where REF_BIRDS_CODE = 'A175';
update ref_birds SET REF_BIRDS_NAME = 'Morus bassanus' where REF_BIRDS_CODE = 'A016';
update ref_birds SET REF_BIRDS_NAME = 'Sylvia ruppeli' where REF_BIRDS_CODE = 'A440';
insert ignore into ref_birds values(457,'A362','Carduelis citrinella',0,0,0,0,0,'0','Carduelis citrinella');
