


UPDATE ref_species SET ref_species_name = 'Aconitum firmum subsp. moravicum' WHERE  ref_species_code = '4109';
UPDATE ref_species SET ref_species_name = 'Anarrhinum longipedicellatum' WHERE  ref_species_code = '1724';
UPDATE ref_species SET ref_species_name = 'Aquilegia pyrenaica subsp. cazorlensis' WHERE  ref_species_code = '1472';
UPDATE ref_species SET ref_species_name = 'Arenaria ciliata subsp. pseudofrigida' WHERE  ref_species_code = '1943';
UPDATE ref_species SET ref_species_name = 'Argyranthemum pinnatifidum subsp. succulentum' WHERE  ref_species_code = '1761';
UPDATE ref_species SET ref_species_name = 'Armeria pseudoarmeria' WHERE  ref_species_code = '1638';
UPDATE ref_species SET ref_species_name = 'Artemisia campestris subsp. bottnica' WHERE  ref_species_code = '1945';
UPDATE ref_species SET ref_species_name = 'Astragalus macrocarpus subsp. lefkarensis' WHERE  ref_species_code = '2131';
UPDATE ref_species SET ref_species_name = 'Biscutella sempervirens subsp. vicentina' WHERE  ref_species_code = '6174';
UPDATE ref_species SET ref_species_name = 'Bombina pachypus' WHERE  ref_species_code = '5357';
UPDATE ref_species SET ref_species_name = 'Centaurea attica subsp. megarensis' WHERE  ref_species_code = '1806';
UPDATE ref_species SET ref_species_name = 'Centaurea micrantha subsp. herminii' WHERE  ref_species_code = '1793';
UPDATE ref_species SET ref_species_name = 'Ceropegia dichotoma subsp. krainzii' WHERE  ref_species_code = '6295';
UPDATE ref_species SET ref_species_name = 'Chaenorhinum serpyllifolium subsp. lusitanicum' WHERE  ref_species_code = '1721';
UPDATE ref_species SET ref_species_name = 'Chalcides viridanus' WHERE  ref_species_code = '1270';
UPDATE ref_species SET ref_species_name = 'Convolvulus lopezsocasi' WHERE  ref_species_code = '1667';
UPDATE ref_species SET ref_species_name = 'Cottus koshewnikowi' WHERE  ref_species_code = '5319';
UPDATE ref_species SET ref_species_name = 'Crepis tectorum subsp. nigrescens' WHERE  ref_species_code = '1953';
UPDATE ref_species SET ref_species_name = 'Dianthus arenarius subsp. arenarius' WHERE  ref_species_code = '1954';
UPDATE ref_species SET ref_species_name = 'Dianthus arenarius subsp. bohemicus' WHERE  ref_species_code = '4073';
UPDATE ref_species SET ref_species_name = 'Dianthus cintranus subsp. cintranus' WHERE  ref_species_code = '1447';
UPDATE ref_species SET ref_species_name = 'Dianthus laricifolius subsp. marizii' WHERE  ref_species_code = '6213';
UPDATE ref_species SET ref_species_name = 'Dianthus plumarius subsp. regis-stephani' WHERE  ref_species_code = '4077';
UPDATE ref_species SET ref_species_name = 'Doronicum plantagineum subsp. tournefortii' WHERE  ref_species_code = '	1797';
UPDATE ref_species SET ref_species_name = 'Dorycnium pentaphyllum subsp. transmontanum' WHERE  ref_species_code = '1542';
UPDATE ref_species SET ref_species_name = 'Herniaria lusitanica subsp. berlengiana' WHERE  ref_species_code = '1449';
UPDATE ref_species SET ref_species_name = 'Holcus setiglumis subsp. duriensis' WHERE  ref_species_code = '1892';
UPDATE ref_species SET ref_species_name = 'Hypochaeris oligocephala' WHERE  ref_species_code = '2266';
UPDATE ref_species SET ref_species_name = 'Iberis procumbens subsp. microcarpa' WHERE  ref_species_code = '1503';
UPDATE ref_species SET ref_species_name = 'Iris aphylla subsp. hungarica' WHERE  ref_species_code = '4097';
UPDATE ref_species SET ref_species_name = 'Iris humilis subsp. arenaria' WHERE  ref_species_code = '4098';
UPDATE ref_species SET ref_species_name = 'Jacobaea vulgaris subsp. gotlandica' WHERE  ref_species_code = '6288';
UPDATE ref_species SET ref_species_name = 'Jasione crispa subsp. serpentinica' WHERE  ref_species_code = '1752';
UPDATE ref_species SET ref_species_name = 'Kogia sima' WHERE  ref_species_code = '2623';
UPDATE ref_species SET ref_species_name = 'Leptodirus hochenwartii' WHERE  ref_species_code = '4019';
UPDATE ref_species SET ref_species_name = 'Limonium arboreum' WHERE  ref_species_code = '7030';
UPDATE ref_species SET ref_species_name = 'Linum mulleri' WHERE  ref_species_code = '1572';
UPDATE ref_species SET ref_species_name = 'Malcolmia lacera subsp. gracilima' WHERE  ref_species_code = '1489';
UPDATE ref_species SET ref_species_name = 'Melilotus segetalis subsp. fallax' WHERE  ref_species_code = '1556';
UPDATE ref_species SET ref_species_name = 'Murbeckiella pinnatifida subsp. herminii' WHERE  ref_species_code = '1504';
UPDATE ref_species SET ref_species_name = 'Narcissus pseudonarcissus subsp. nobilis' WHERE  ref_species_code = '1857';
UPDATE ref_species SET ref_species_name = 'Narcissus triandrus subsp. capax' WHERE  ref_species_code = '1868';
UPDATE ref_species SET ref_species_name = 'Nepeta argolica subsp. dirphya' WHERE  ref_species_code = '6283';
UPDATE ref_species SET ref_species_name = 'Osmoderma italicum' WHERE  ref_species_code = '5381';
UPDATE ref_species SET ref_species_name = 'Paeonia clusii subsp. rhodia' WHERE  ref_species_code = '1481';
UPDATE ref_species SET ref_species_name = 'Paeonia officinalis subsp. banatica' WHERE  ref_species_code = '2097';
UPDATE ref_species SET ref_species_name = 'Platanthera obtusata subsp. oligantha' WHERE  ref_species_code = '1967';
UPDATE ref_species SET ref_species_name = 'Poa granitica subsp. disparilis' WHERE  ref_species_code = '4122';
UPDATE ref_species SET ref_species_name = 'Podarcis raffoneae' WHERE  ref_species_code = '5795';
UPDATE ref_species SET ref_species_name = 'Podarcis siculus' WHERE  ref_species_code = '1250';
UPDATE ref_species SET ref_species_name = 'Podarcis waglerianus' WHERE  ref_species_code = '1244';
UPDATE ref_species SET ref_species_name = 'COD NO PRESENTE' WHERE  ref_species_code = '7032';
UPDATE ref_species SET ref_species_name = 'Proterebia afra dalmata' WHERE  ref_species_code = '6350';
UPDATE ref_species SET ref_species_name = 'Pulsatilla pratensis subsp. hungarica' WHERE  ref_species_code = '4110';
UPDATE ref_species SET ref_species_name = 'Pulsatilla vulgaris subsp. gotlandica' WHERE  ref_species_code = '1970';
UPDATE ref_species SET ref_species_name = 'COD NO PRESENTE' WHERE  ref_species_code = '7031';
UPDATE ref_species SET ref_species_name = 'Rhynchosinapis erucastrum subsp. cintrana' WHERE  ref_species_code = '1492';
UPDATE ref_species SET ref_species_name = 'Salix salvifolia subsp. australis' WHERE  ref_species_code = '1434';
UPDATE ref_species SET ref_species_name = 'Sambucus nigra subsp. palmensis' WHERE  ref_species_code = '6294';
UPDATE ref_species SET ref_species_name = 'Saussurea alpina subsp. esthonica' WHERE  ref_species_code = '4086';
UPDATE ref_species SET ref_species_name = 'Senecio lagascanus subsp. lusitanicus' WHERE  ref_species_code = '1769';
UPDATE ref_species SET ref_species_name = 'Silene involucrata subsp. tenella' WHERE  ref_species_code = '6181';
UPDATE ref_species SET ref_species_name = 'Tephroseris longifolia subsp. moravica' WHERE  ref_species_code = '4088';
UPDATE ref_species SET ref_species_name = 'Teucrium salviastrum subsp. salviastrum' WHERE  ref_species_code = '1691';
UPDATE ref_species SET ref_species_name = 'Thymelaea broteriana' WHERE  ref_species_code = '1582';
UPDATE ref_species SET ref_species_name = 'Thymus villosus subsp. villosus' WHERE  ref_species_code = '1698';
UPDATE ref_species SET ref_species_name = 'Viola rupestris subsp. relicta' WHERE  ref_species_code = '1978';
