-- temporarily turn on auto increment to insert new rows
ALTER TABLE `ref_designations_emerald` CHANGE `REF_DESIGNATIONS_ID` `REF_DESIGNATIONS_ID` int(11) AUTO_INCREMENT NOT NULL;
-- new values
INSERT INTO ref_designations_emerald (`REF_DESIGNATIONS_CODE`, `REF_DESIGNATIONS_DESCR`, `REF_DESIGNATIONS_CATEGORY`) VALUES ('NO01', '', 'A');
INSERT INTO ref_designations_emerald (`REF_DESIGNATIONS_CODE`, `REF_DESIGNATIONS_DESCR`, `REF_DESIGNATIONS_CATEGORY`) VALUES ('NO02', '', 'A');
INSERT INTO ref_designations_emerald (`REF_DESIGNATIONS_CODE`, `REF_DESIGNATIONS_DESCR`, `REF_DESIGNATIONS_CATEGORY`) VALUES ('NO03', '', 'A');
INSERT INTO ref_designations_emerald (`REF_DESIGNATIONS_CODE`, `REF_DESIGNATIONS_DESCR`, `REF_DESIGNATIONS_CATEGORY`) VALUES ('NO04', '', 'A');
INSERT INTO ref_designations_emerald (`REF_DESIGNATIONS_CODE`, `REF_DESIGNATIONS_DESCR`, `REF_DESIGNATIONS_CATEGORY`) VALUES ('NO05', '', 'A');
INSERT INTO ref_designations_emerald (`REF_DESIGNATIONS_CODE`, `REF_DESIGNATIONS_DESCR`, `REF_DESIGNATIONS_CATEGORY`) VALUES ('NO11', '', 'A');
INSERT INTO ref_designations_emerald (`REF_DESIGNATIONS_CODE`, `REF_DESIGNATIONS_DESCR`, `REF_DESIGNATIONS_CATEGORY`) VALUES ('NO13', '', 'A');
INSERT INTO ref_designations_emerald (`REF_DESIGNATIONS_CODE`, `REF_DESIGNATIONS_DESCR`, `REF_DESIGNATIONS_CATEGORY`) VALUES ('NO15', '', 'A');
INSERT INTO ref_designations_emerald (`REF_DESIGNATIONS_CODE`, `REF_DESIGNATIONS_DESCR`, `REF_DESIGNATIONS_CATEGORY`) VALUES ('NO16', '', 'A');
INSERT INTO ref_designations_emerald (`REF_DESIGNATIONS_CODE`, `REF_DESIGNATIONS_DESCR`, `REF_DESIGNATIONS_CATEGORY`) VALUES ('NO17', '', 'A');
INSERT INTO ref_designations_emerald (`REF_DESIGNATIONS_CODE`, `REF_DESIGNATIONS_DESCR`, `REF_DESIGNATIONS_CATEGORY`) VALUES ('NO19', '', 'A');
INSERT INTO ref_designations_emerald (`REF_DESIGNATIONS_CODE`, `REF_DESIGNATIONS_DESCR`, `REF_DESIGNATIONS_CATEGORY`) VALUES ('NO21', '', 'A');
INSERT INTO ref_designations_emerald (`REF_DESIGNATIONS_CODE`, `REF_DESIGNATIONS_DESCR`, `REF_DESIGNATIONS_CATEGORY`) VALUES ('NO22', '', 'B');
INSERT INTO ref_designations_emerald (`REF_DESIGNATIONS_CODE`, `REF_DESIGNATIONS_DESCR`, `REF_DESIGNATIONS_CATEGORY`) VALUES ('NO23', '', 'A');
INSERT INTO ref_designations_emerald (`REF_DESIGNATIONS_CODE`, `REF_DESIGNATIONS_DESCR`, `REF_DESIGNATIONS_CATEGORY`) VALUES ('NO31', '', 'A');
INSERT INTO ref_designations_emerald (`REF_DESIGNATIONS_CODE`, `REF_DESIGNATIONS_DESCR`, `REF_DESIGNATIONS_CATEGORY`) VALUES ('NO33', '', 'A');
INSERT INTO ref_designations_emerald (`REF_DESIGNATIONS_CODE`, `REF_DESIGNATIONS_DESCR`, `REF_DESIGNATIONS_CATEGORY`) VALUES ('NO34', '', 'A');
INSERT INTO ref_designations_emerald (`REF_DESIGNATIONS_CODE`, `REF_DESIGNATIONS_DESCR`, `REF_DESIGNATIONS_CATEGORY`) VALUES ('NO39', '', 'A');
INSERT INTO ref_designations_emerald (`REF_DESIGNATIONS_CODE`, `REF_DESIGNATIONS_DESCR`, `REF_DESIGNATIONS_CATEGORY`) VALUES ('NO43', '', 'A');
INSERT INTO ref_designations_emerald (`REF_DESIGNATIONS_CODE`, `REF_DESIGNATIONS_DESCR`, `REF_DESIGNATIONS_CATEGORY`) VALUES ('NO53', '', 'A');
INSERT INTO ref_designations_emerald (`REF_DESIGNATIONS_CODE`, `REF_DESIGNATIONS_DESCR`, `REF_DESIGNATIONS_CATEGORY`) VALUES ('NO90', '', 'A');
INSERT INTO ref_designations_emerald (`REF_DESIGNATIONS_CODE`, `REF_DESIGNATIONS_DESCR`, `REF_DESIGNATIONS_CATEGORY`) VALUES ('NO99', '', 'A');
-- disable auto increment again
ALTER TABLE `ref_designations_emerald` CHANGE `REF_DESIGNATIONS_ID` `REF_DESIGNATIONS_ID` int(11) NOT NULL;