package pojos;

import java.util.HashSet;
import java.util.Set;

/**
 * Biogeo generated by hbm2java
 */
public class Biogeo  implements java.io.Serializable {


     private int biogeoId;
     private String biogeoName;
     private String biogeoCode;
     private Set siteBiogeos = new HashSet(0);
    /**
     *
     */
    public Biogeo() {
    }

    /**
     *
     * @param biogeoId
     */
    public Biogeo(int biogeoId) {
        this.biogeoId = biogeoId;
    }
    /**
     *
     * @param biogeoId
     * @param biogeoName
     * @param biogeoCode
     * @param siteBiogeos
     */
    public Biogeo(int biogeoId, String biogeoName, String biogeoCode, Set siteBiogeos) {
       this.biogeoId = biogeoId;
       this.biogeoName = biogeoName;
       this.biogeoCode = biogeoCode;
       this.siteBiogeos = siteBiogeos;
    }
   /**
    *
    * @return biogeo identifier
    */
    public int getBiogeoId() {
        return this.biogeoId;
    }
    /**
     *
     * @param biogeoId
     */
    public void setBiogeoId(int biogeoId) {
        this.biogeoId = biogeoId;
    }
    /**
     *
     * @return the name of the biogeo
     */
    public String getBiogeoName() {
        return this.biogeoName;
    }
    /**
     *
     * @param biogeoName
     */
    public void setBiogeoName(String biogeoName) {
        this.biogeoName = biogeoName;
    }
    /**
     *
     * @return the code of the biogeo
     */
    public String getBiogeoCode() {
        return this.biogeoCode;
    }
    /**
     *
     * @param biogeoCode
     */
    public void setBiogeoCode(String biogeoCode) {
        this.biogeoCode = biogeoCode;
    }
    /**
     *
     * @return the set of the boigeo of the site
     */
    public Set getSiteBiogeos() {
        return this.siteBiogeos;
    }
    /**
     * 
     * @param siteBiogeos
     */
    public void setSiteBiogeos(Set siteBiogeos) {
        this.siteBiogeos = siteBiogeos;
    }

}


