package pojos;
// Generated 01-fvr.-2011 13:10:18 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Doc generated by hbm2java
 */
public class Doc  implements java.io.Serializable {


     private int docId;
     private String docDescription;
     private Set docLinks = new HashSet(0);
     private Set sites = new HashSet(0);

   /**
    *
    */
    public Doc() {
    }

    /**
     *
     * @param docId
     */
    public Doc(int docId) {
        this.docId = docId;
    }
    /**
     *
     * @param docId
     * @param docDescription
     * @param docLinks
     * @param sites
     */
    public Doc(int docId, String docDescription, Set docLinks, Set sites) {
       this.docId = docId;
       this.docDescription = docDescription;
       this.docLinks = docLinks;
       this.sites = sites;
    }
    /**
     *
     * @return the identifoer of the document
     */
    public int getDocId() {
        return this.docId;
    }
    /**
     *
     * @param docId
     */
    public void setDocId(int docId) {
        this.docId = docId;
    }
    /**
     *
     * @return The description of the document
     */
    public String getDocDescription() {
        return this.docDescription;
    }
    /**
     *
     * @param docDescription
     */
    public void setDocDescription(String docDescription) {
        this.docDescription = docDescription;
    }
    /**
     *
     * @return The set of the documents of the site
     */
    public Set getDocLinks() {
        return this.docLinks;
    }
    /**
     *
     * @param docLinks
     */
    public void setDocLinks(Set docLinks) {
        this.docLinks = docLinks;
    }
    /**
     *
     * @return
     */
    public Set getSites() {
        return this.sites;
    }
    /**
     *
     * @param sites
     */
    public void setSites(Set sites) {
        this.sites = sites;
    }

}


