package pojos;
// Generated 01-fvr.-2011 13:10:18 by Hibernate Tools 3.2.1.GA


/**
 * DocLink generated by hbm2java
 */
public class DocLink  implements java.io.Serializable, Comparable {


     private int docLinkId;
     private Doc doc;
     private String docLinkUrl;
     /**
      *
      */
     public DocLink() {
     }

     /**
      *
      * @param docLinkId
      */
     public DocLink(int docLinkId) {
        this.docLinkId = docLinkId;
     }
     /**
      *
      * @param docLinkId
      * @param doc
      * @param docLinkUrl
      */
     public DocLink(int docLinkId, Doc doc, String docLinkUrl) {
       this.docLinkId = docLinkId;
       this.doc = doc;
       this.docLinkUrl = docLinkUrl;
     }

     public int compareTo(Object o){
        if (o.getClass().equals(this.getClass())){
            DocLink l = (DocLink)o;
            return this.getDocLinkUrl().compareTo(l.getDocLinkUrl());
        } else {
            return -1;
        }
     }


     /**
      *
      * @return The identifier of the link of the document
      */
     public int getDocLinkId() {
        return this.docLinkId;
     }
     /**
      *
      * @param docLinkId
      */
     public void setDocLinkId(int docLinkId) {
        this.docLinkId = docLinkId;
     }
     /**
      *
      * @return The Document
      */
     public Doc getDoc() {
        return this.doc;
     }
     /**
      *
      * @param doc
      */
     public void setDoc(Doc doc) {
        this.doc = doc;
     }
     /**
      *
      * @return The link of the document
      */
     public String getDocLinkUrl() {
        return this.docLinkUrl;
     }
     /**
      * 
      * @param docLinkUrl
      */
     public void setDocLinkUrl(String docLinkUrl) {
        this.docLinkUrl = docLinkUrl;
     }
}


