package pojos;
// Generated 01-f�vr.-2011 13:10:18 by Hibernate Tools 3.2.1.GA



/**
 * HabitatClass generated by hbm2java
 */
public class HabitatClass  implements java.io.Serializable , Comparable{


     private int habitatClassId;
     private Site site;
     private String habitatClassCode;
     private String habitatClassDescription;
     private Double habitatClassCover;
    /**
     *
     */
    public HabitatClass() {
    }

    /**
     *
     * @param habitatClassId
     */
    public HabitatClass(int habitatClassId) {
        this.habitatClassId = habitatClassId;
    }
    /**
     *
     * @param habitatClassId
     * @param site
     * @param habitatClassCode
     * @param habitatClassDescription
     * @param habitatClassCover
     */
    public HabitatClass(int habitatClassId, Site site, String habitatClassCode, String habitatClassDescription, Double habitatClassCover) {
       this.habitatClassId = habitatClassId;
       this.site = site;
       this.habitatClassCode = habitatClassCode;
       this.habitatClassDescription = habitatClassDescription;
       this.habitatClassCover = habitatClassCover;
    }
    /**
     *
     * @return The identifier of the habitat class
     */
    public int getHabitatClassId() {
        return this.habitatClassId;
    }
    /**
     *
     * @param habitatClassId
     */
    public void setHabitatClassId(int habitatClassId) {
        this.habitatClassId = habitatClassId;
    }
    /**
     *
     * @return The site
     */
    public Site getSite() {
        return this.site;
    }
    /**
     *
     * @param site
     */
    public void setSite(Site site) {
        this.site = site;
    }
    /**
     *
     * @return
     */
    public String getHabitatClassCode() {
        return this.habitatClassCode;
    }
    /**
     *
     * @param habitatClassCode
     */
    public void setHabitatClassCode(String habitatClassCode) {
        this.habitatClassCode = habitatClassCode;
    }
    /**
     *
     * @return The description of the habitat class
     */
    public String getHabitatClassDescription() {
        return this.habitatClassDescription;
    }
    /**
     *
     * @param habitatClassDescription
     */
    public void setHabitatClassDescription(String habitatClassDescription) {
        this.habitatClassDescription = habitatClassDescription;
    }
    /**
     *
     * @return The cover of the habitat class
     */
    public Double getHabitatClassCover() {
        return this.habitatClassCover;
    }
    /**
     * 
     * @param habitatClassCover
     */
    public void setHabitatClassCover(Double habitatClassCover) {
        this.habitatClassCover = habitatClassCover;
    }

    @Override
    public String toString() {
        return getHabitatClassCode();
    }


    public int compareTo(Object o) {
        HabitatClass r = (HabitatClass) o;
        return this.getHabitatClassCode().compareTo(r.getHabitatClassCode());
    }
}


