package pojos;
// Generated 01-fvr.-2011 13:10:18 by Hibernate Tools 3.2.1.GA




/**
 * NationalDtype generated by hbm2java
 */
public class NationalDtype  implements java.io.Serializable {


     private int nationalDtypeId;
     private Site site;
     private String nationalDtypeCode;
     private Double nationalDtypeCover;
     

    public NationalDtype() {
    }


    public NationalDtype(int nationalDtypeId) {
        this.nationalDtypeId = nationalDtypeId;
    }
    public NationalDtype(int nationalDtypeId, Site site, String nationalDtypeCode, Double nationalDtypeCover) {
       this.nationalDtypeId = nationalDtypeId;
       this.site = site;
       this.nationalDtypeCode = nationalDtypeCode;
       this.nationalDtypeCover = nationalDtypeCover;
    }

    public int getNationalDtypeId() {
        return this.nationalDtypeId;
    }

    public void setNationalDtypeId(int nationalDtypeId) {
        this.nationalDtypeId = nationalDtypeId;
    }
    public Site getSite() {
        return this.site;
    }

    public void setSite(Site site) {
        this.site = site;
    }
    public String getNationalDtypeCode() {
        return this.nationalDtypeCode;
    }

    public void setNationalDtypeCode(String nationalDtypeCode) {
        this.nationalDtypeCode = nationalDtypeCode;
    }
    public Double getNationalDtypeCover() {
        return this.nationalDtypeCover;
    }

    public void setNationalDtypeCover(Double nationalDtypeCover) {
        this.nationalDtypeCover = nationalDtypeCover;
    }

    }


