package pojos;
// Generated 01-f�vr.-2011 13:10:18 by Hibernate Tools 3.2.1.GA




/**
 * OtherSpecies generated by hbm2java
 */
public class OtherSpecies  implements java.io.Serializable , Comparable {


     private int otherSpeciesId;
     private Site site;
     private String otherSpeciesGroup;
     private String otherSpeciesCode;
     private String otherSpeciesName;
     private Short otherSpeciesSensitive;
     private Short otherSpeciesNp;
     private Integer otherSpeciesSizeMin;
     private Integer otherSpeciesSizeMax;
     private String otherSpeciesUnit;
     private Character otherSpeciesCategory;

     private String otherSpeciesMotivation;
    
    public OtherSpecies() {
    }


    public OtherSpecies(int otherSpeciesId) {
        this.otherSpeciesId = otherSpeciesId;
    }
    public OtherSpecies(int otherSpeciesId, Site site, String otherSpeciesGroup, String otherSpeciesCode, String otherSpeciesName,
            Short otherSpeciesSensitive, Short otherSpeciesNp, Integer otherSpeciesSizeMin,
            Integer otherSpeciesSizeMax, String otherSpeciesUnit, Character otherSpeciesCategory,
            String otherSpeciesMotivation) {
       this.otherSpeciesId = otherSpeciesId;
       this.site = site;
       this.otherSpeciesGroup = otherSpeciesGroup;
       this.otherSpeciesCode = otherSpeciesCode;
       this.otherSpeciesName = otherSpeciesName;
       this.otherSpeciesSensitive = otherSpeciesSensitive;
       this.otherSpeciesNp = otherSpeciesNp;
       this.otherSpeciesSizeMin = otherSpeciesSizeMin;
       this.otherSpeciesSizeMax = otherSpeciesSizeMax;
       this.otherSpeciesUnit = otherSpeciesUnit;
       this.otherSpeciesCategory = otherSpeciesCategory;
       this.otherSpeciesMotivation = otherSpeciesMotivation;

    }

    public int getOtherSpeciesId() {
        return this.otherSpeciesId;
    }

    public void setOtherSpeciesId(int otherSpeciesId) {
        this.otherSpeciesId = otherSpeciesId;
    }
    public Site getSite() {
        return this.site;
    }

    public void setSite(Site site) {
        this.site = site;
    }
    public String getOtherSpeciesGroup() {
        return this.otherSpeciesGroup;
    }

    public void setOtherSpeciesGroup(String otherSpeciesGroup) {
        this.otherSpeciesGroup = otherSpeciesGroup;
    }
    public String getOtherSpeciesCode() {
        return this.otherSpeciesCode;
    }

    public void setOtherSpeciesCode(String otherSpeciesCode) {
        this.otherSpeciesCode = otherSpeciesCode;
    }
    public String getOtherSpeciesName() {
        return this.otherSpeciesName;
    }

    public void setOtherSpeciesName(String otherSpeciesName) {
        this.otherSpeciesName = otherSpeciesName;
    }
    public Short getOtherSpeciesSensitive() {
        return this.otherSpeciesSensitive;
    }

    public void setOtherSpeciesSensitive(Short otherSpeciesSensitive) {
        this.otherSpeciesSensitive = otherSpeciesSensitive;
    }
    public Short getOtherSpeciesNp() {
        return this.otherSpeciesNp;
    }

    public void setOtherSpeciesNp(Short otherSpeciesNp) {
        this.otherSpeciesNp = otherSpeciesNp;
    }
    public Integer getOtherSpeciesSizeMin() {
        return this.otherSpeciesSizeMin;
    }

    public void setOtherSpeciesSizeMin(Integer otherSpeciesSizeMin) {
        this.otherSpeciesSizeMin = otherSpeciesSizeMin;
    }
    public Integer getOtherSpeciesSizeMax() {
        return this.otherSpeciesSizeMax;
    }

    public void setOtherSpeciesSizeMax(Integer otherSpeciesSizeMax) {
        this.otherSpeciesSizeMax = otherSpeciesSizeMax;
    }
    public String getOtherSpeciesUnit() {
        return this.otherSpeciesUnit;
    }

    public void setOtherSpeciesUnit(String otherSpeciesUnit) {
        this.otherSpeciesUnit = otherSpeciesUnit;
    }
    public Character getOtherSpeciesCategory() {
        return this.otherSpeciesCategory;
    }

    public void setOtherSpeciesCategory(Character otherSpeciesCategory) {
        this.otherSpeciesCategory = otherSpeciesCategory;
    }

    /**
     * @return the otherSpeciesMotivation
     */
    public String getOtherSpeciesMotivation() {
        return otherSpeciesMotivation;
    }

    /**
     * @param otherSpeciesMotivation the otherSpeciesMotivation to set
     */
    public void setOtherSpeciesMotivation(String otherSpeciesMotivation) {
        this.otherSpeciesMotivation = otherSpeciesMotivation;
    }

       @Override
    public String toString() {
        return getOtherSpeciesCode();
    }

    public int compareTo(Object o) {
        OtherSpecies r = (OtherSpecies) o;
        return this.getOtherSpeciesName().compareTo(r.getOtherSpeciesName());
    }

   }


