package pojos;
// Generated 01-fvr.-2011 13:10:18 by Hibernate Tools 3.2.1.GA



/**
 * RefBirds generated by hbm2java
 */
public class RefBirds  implements java.io.Serializable {


     private int refBirdsId;
     private String refBirdsCode;
     private String refBirdsName;
     private Short refBirdsAnnexi;
     private Short refBirdsAnnexiipa;
     private Short refBirdsAnnexiipb;
     private Short refBirdsAnnexiiipa;
     private Short refBirdsAnnexiiipb;
     private String refCodeNew;
     private String refAltBirdsName;

    public RefBirds() {
    }


    public RefBirds(int refBirdsId) {
        this.refBirdsId = refBirdsId;
    }
    public RefBirds(int refBirdsId, String refBirdsCode, String refBirdsName, Short refBirdsAnnexi, Short refBirdsAnnexiipa, Short refBirdsAnnexiipb, Short refBirdsAnnexiiipa, Short refBirdsAnnexiiipb) {
       this.refBirdsId = refBirdsId;
       this.refBirdsCode = refBirdsCode;
       this.refBirdsName = refBirdsName;
       this.refBirdsAnnexi = refBirdsAnnexi;
       this.refBirdsAnnexiipa = refBirdsAnnexiipa;
       this.refBirdsAnnexiipb = refBirdsAnnexiipb;
       this.refBirdsAnnexiiipa = refBirdsAnnexiiipa;
       this.refBirdsAnnexiiipb = refBirdsAnnexiiipb;
    }

    public int getRefBirdsId() {
        return this.refBirdsId;
    }

    public void setRefBirdsId(int refBirdsId) {
        this.refBirdsId = refBirdsId;
    }
    public String getRefBirdsCode() {
        return this.refBirdsCode;
    }

    public void setRefBirdsCode(String refBirdsCode) {
        this.refBirdsCode = refBirdsCode;
    }
    public String getRefBirdsName() {
        return this.refBirdsName;
    }

    public void setRefBirdsName(String refBirdsName) {
        this.refBirdsName = refBirdsName;
    }
    public Short getRefBirdsAnnexi() {
        return this.refBirdsAnnexi;
    }

    public void setRefBirdsAnnexi(Short refBirdsAnnexi) {
        this.refBirdsAnnexi = refBirdsAnnexi;
    }
    public Short getRefBirdsAnnexiipa() {
        return this.refBirdsAnnexiipa;
    }

    public void setRefBirdsAnnexiipa(Short refBirdsAnnexiipa) {
        this.refBirdsAnnexiipa = refBirdsAnnexiipa;
    }
    public Short getRefBirdsAnnexiipb() {
        return this.refBirdsAnnexiipb;
    }

    public void setRefBirdsAnnexiipb(Short refBirdsAnnexiipb) {
        this.refBirdsAnnexiipb = refBirdsAnnexiipb;
    }
    public Short getRefBirdsAnnexiiipa() {
        return this.refBirdsAnnexiiipa;
    }

    public void setRefBirdsAnnexiiipa(Short refBirdsAnnexiiipa) {
        this.refBirdsAnnexiiipa = refBirdsAnnexiiipa;
    }
    public Short getRefBirdsAnnexiiipb() {
        return this.refBirdsAnnexiiipb;
    }

    public void setRefBirdsAnnexiiipb(Short refBirdsAnnexiiipb) {
        this.refBirdsAnnexiiipb = refBirdsAnnexiiipb;
    }

    /**
     * @return the refCodeNew
     */
    public String getRefCodeNew() {
        return refCodeNew;
    }

    /**
     * @param refCodeNew the refCodeNew to set
     */
    public void setRefCodeNew(String refCodeNew) {
        this.refCodeNew = refCodeNew;
    }

    /**
     * @return the refAltBirdsName
     */
    public String getRefAltBirdsName() {
        return refAltBirdsName;
    }

    /**
     * @param refAltBirdsName the refAltBirdsName to set
     */
    public void setRefAltBirdsName(String refAltBirdsName) {
        this.refAltBirdsName = refAltBirdsName;
    }
}


