package pojos;
// Generated 01-fvr.-2011 13:10:18 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Resp generated by hbm2java
 */
public class Resp  implements java.io.Serializable {


    private int respId;
    private String respName;
    private String respAddress;
    private String respEmail;
    private String respAdminUnit;
    private String respLocatorDesig;
    private String respLocatorName;
    private String respAddressArea;
    private String respPostName;
    private String respPostCode;
    private String respThoroughFare;
    private Set sites;
    


     public Resp()
    {
        sites = new HashSet(0);
    }

    public Resp(int respId)
    {
        sites = new HashSet(0);
        this.respId = respId;
    }

    public Resp(int respId, String respName, String respAddress, String respEmail, String respAdminUnit, String respLocatorDesig, String respLocatorName,
            String respAddressArea, String respPostName, String respPostCode, String respThoroughFare, Set sites)
    {
        this.sites = new HashSet(0);
        this.respId = respId;
        this.respName = respName;
        this.respAddress = respAddress;
        this.respEmail = respEmail;
        this.respAdminUnit = respAdminUnit;
        this.respLocatorDesig = respLocatorDesig;
        this.respLocatorName = respLocatorName;
        this.respAddressArea = respAddressArea;
        this.respPostName = respPostName;
        this.respPostCode = respPostCode;
        this.respThoroughFare = respThoroughFare;
        this.sites = sites;
    }

    public int getRespId()
    {
        return respId;
    }

    public void setRespId(int respId)
    {
        this.respId = respId;
    }

    public String getRespName()
    {
        return respName;
    }

    public void setRespName(String respName)
    {
        this.respName = respName;
    }

    public String getRespAddress()
    {
        return respAddress;
    }

    public void setRespAddress(String respAddress)
    {
        this.respAddress = respAddress;
    }

    public String getRespEmail()
    {
        return respEmail;
    }

    public void setRespEmail(String respEmail)
    {
        this.respEmail = respEmail;
    }

    public Set getSites()
    {
        return sites;
    }

    public void setSites(Set sites)
    {
        this.sites = sites;
    }

    public String getRespAdminUnit()
    {
        return respAdminUnit;
    }

    public String getRespLocatorDesig()
    {
        return respLocatorDesig;
    }

    public String getRespAddressArea()
    {
        return respAddressArea;
    }

    public String getRespPostName()
    {
        return respPostName;
    }

    public String getRespPostCode()
    {
        return respPostCode;
    }

    public void setRespPostCode(String respPostCode)
    {
        this.respPostCode = respPostCode;
    }

    public String getRespThoroughFare()
    {
        return respThoroughFare;
    }

    public void setRespAdminUnit(String respAdminUnit)
    {
        this.respAdminUnit = respAdminUnit;
    }

    public void setRespLocatorDesig(String respLocatorDesig)
    {
        this.respLocatorDesig = respLocatorDesig;
    }

    public String getRespLocatorName()
    {
        return respLocatorName;
    }

    public void setRespLocatorName(String respLocatorName)
    {
        this.respLocatorName = respLocatorName;
    }

    public void setRespAddressArea(String respAddressArea)
    {
        this.respAddressArea = respAddressArea;
    }

    public void setRespPostName(String respPostName)
    {
        this.respPostName = respPostName;
    }

    public void setRespThoroughFare(String respThoroughFare)
    {
        this.respThoroughFare = respThoroughFare;
    }

  }


