insert ignore into ref_unit VALUES(1,'individuals','i');
insert ignore into ref_unit VALUES(2,'adults','adults');
insert ignore into ref_unit VALUES(3,'subadults','subadults');
insert ignore into ref_unit VALUES(5,'breeding females','bfemales');
insert ignore into ref_unit VALUES(6,'calling males','cmales');
insert ignore into ref_unit VALUES(7,'males','males');
insert ignore into ref_unit VALUES(8,'pairs','p');
insert ignore into ref_unit VALUES(9,'shoots','shoots');
insert ignore into ref_unit VALUES(10,'tufts','tufts');
insert ignore into ref_unit VALUES(11,'localities','localities');
insert ignore into ref_unit VALUES(12,'colonies','colonies');
insert ignore into ref_unit VALUES(13,'inhabited logs','logs');
insert ignore into ref_unit VALUES(14,'inhabited trees','trees number of');
insert ignore into ref_unit VALUES(15,'inhabited stones/boulders','stones');
insert ignore into ref_unit VALUES(16,'length of inhabited feature in km','length');
insert ignore into ref_unit VALUES(17,'area coverd by population in m2','area');
insert ignore into ref_unit VALUES(18,'1x1 km grid','grids1x1');
insert ignore into ref_unit VALUES(19,'5x5 km grid','grids5x5');
insert ignore into ref_unit VALUES(20,'10x10 km grid','grids10x10');
commit;
