insert ignore into ref_species_group VALUES(1,'Amphibians','A','S');
insert ignore into ref_species_group VALUES(2,'Birds','B','S');
insert ignore into ref_species_group VALUES(3,'Fish','F','S');
insert ignore into ref_species_group VALUES(4,'Invertebrates','I','S');
insert ignore into ref_species_group VALUES(5,'Mammals','M','S');
insert ignore into ref_species_group VALUES(6,'Plants','P','S');
insert ignore into ref_species_group VALUES(7,'Reptiles','R','S');
insert ignore into ref_species_group VALUES(8,'Fungi','Fu','O');
insert ignore into ref_species_group VALUES(9,'Lichens','L','O');
commit;